### ISSUE TITLE
Dumb dump...

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#103]
Coucou @Yomguithereal 

J'arriverai tout à l'heure avec une difficulté quand à la mise en place du CMS en local.
Je n'arrive pas à lancer la commande `dump`

Cela fait quelques jours que je me débat avec ce soucis et force est de constater que je bloque.
J'ai essayé de réinstaller les dépendances de zéro ainsi que nodes, toujours de zéro.
Résultat : Zéro...

Voici l'épineux en question.
Si tu pouvais m'en dire plus tout à l'heure ?

```
Beni@DESKTOP-E1KH5TV:/mnt/b/_Software/UniServerZ/www/medialab/website$ npm run hydrate:json

> medialab-website-api@1.0.0 hydrate:json /mnt/b/_Software/UniServerZ/www/medialab/website
> rm -rf data/* && mkdir -p data/assets && touch data/assets/dummy && cp specs/samples/json/*.json data

Beni@DESKTOP-E1KH5TV:/mnt/b/_Software/UniServerZ/www/medialab/website$ npm run dump

> medialab-website-api@1.0.0 dump /mnt/b/_Software/UniServerZ/www/medialab/website
> node ./scripts/dump.js

/mnt/b/_Software/UniServerZ/www/medialab/website/node_modules/jsonfile/index.js:67
      throw err
      ^

Error: data/settings.json: ENOENT: no such file or directory, open 'data/settings.json'
    at Object.openSync (fs.js:450:3)
    at Object.readFileSync (fs.js:350:35)
    at Object.readFileSync (/mnt/b/_Software/UniServerZ/www/medialab/website/node_modules/jsonfile/index.js:61:22)
    at dump (/mnt/b/_Software/UniServerZ/www/medialab/website/api/dump.js:16:23)
    at Object.<anonymous> (/mnt/b/_Software/UniServerZ/www/medialab/website/scripts/dump.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medialab-website-api@1.0.0 dump: `node ./scripts/dump.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the medialab-website-api@1.0.0 dump script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     `/home/Beni/.npm/_logs/2018-12-19T10_04_02_603Z-debug.log
```

Et le fichier log dont il est ici question ne me donne pas d'information supplementaire

**Comment by oncletom** [comment]
L'erreur dit qu'il manque le fichier `data/settings.json`. Il y a quoi comme fichiers dans ton répertoire `data` ?

**Comment by oncletom** [comment]
Je confirme, j'ai le même problème sur ma machine (avec un dépôt Git à jour).

**Comment by Yomguithereal** [comment]
Pour pouvoir dumper il faut une base complète et pour cela il faut lancer le CMS au moins une fois. Je suis d'accord qu'il faudrait que le load gère le cas où les settings n'ont pas été initialisés mais cela est un usage curieux.

**Comment by BenjmnG** [comment]
Merci je me sens moins seul ^^
Le dossier Data contient :

````
Assets /
activities.json
news.json
people.json
publication.json
````

pas de settings.json donc

Le mer. 19 déc. 2018 à 11:46, Guillaume Plique <notifications@github.com> a
écrit :

**Comment by Yomguithereal** [comment]
Oui parce que le CMS n'a jamais été lancé. Fais `npm run dev`  attends que tout soit fait, puis ctrl+c et relance le dump et là ça va marcher. Cela dit je ne vois pas trop pourquoi tu as besoin de dump une base vide.

**Comment by oncletom** [comment]
> il faudrait que le load gère le cas où les settings n'ont pas été initialisés mais cela est un usage curieux

L'intégration continue ?

**Comment by oncletom** [comment]
Ça marche en tous cas après avoir fait `npm run dev` et après avoir attendu que tout soit mouliné.

**Comment by Yomguithereal** [comment]
:7000 pour l'admin :8000 pour la preview. Ca serait pas mal de l'ajouter sur la doc oui :)

**Comment by BenjmnG** [comment]
Merci Yom-Gui,
Cela marche aussi pour moi.
Je clos ce bazar
