### ISSUE TITLE
liste typée de liens

### ISSUE THREAD

**Issue by boogheta** [medialab/website#106]
Dans les productions on pourrait vouloir stocker plusieurs liens :
- dans spire on a plusieurs liens: PDF et liens qui pointent vers le site de l'éditeur, une présentation, une vidéo...
- source URL pour les productions de type outils

Avoir une liste typé de lien ressemble au besoin de : 
- contacts dans people
- documentation dans activities

Nous avons besoin de définir une manière commune de gérer ces cas non ?

**Comment by AmelieVRL** [comment]
Ça semble équivalent aux "attachments" des people; il faudrait aussi le mettre pour le news.
Donc à ajouter pour : 
- [ ] news
- [ ] productions

Et surement à remettre dans les specs...

**Comment by paulgirard** [comment]
Mmm c'est pas complètement clair.
On en parle Mercredi prochain

**Comment by paulgirard** [comment]
Je clos et isole le dernier morceau dans #197
