### ISSUE TITLE
transformer les vieux HTML dans le format de l'éditeur

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#107]
pour importer les contenus HTML de l'ancien site il faut transformer le HTML pour respecter cette spec : [https://github.com/medialab/website/blob/master/specs/HTML.md](https://github.com/medialab/website/blob/master/specs/HTML.md)

**Comment by paulgirard** [comment]
done by @Yomguithereal Je lui dois une masse

**Comment by Yomguithereal** [comment]
Une masse + 1 à ailettes? Je peux avoir un morgenstern magique?
