### ISSUE TITLE
Repasser sur les actvitiés importées (25 items)

### ISSUE THREAD

**Issue by oncletom** [medialab/website#119]

**Comment by oncletom** [comment]
C'est un doublon de #118 (qu'on a reformulé en commençant à s'y attaquer).

**Comment by paulgirard** [comment]
Vous faites erreur... 
L'autre carte concernait les activités et non les actualités.
Le but est de repasser sur toutes activités, nettoyer les contenus qui sont souvent dupliqué dans les deux langues, vérifier la catégorisation et les liens people.
Je rouvre celle-là que je renomme du coup **activités**.

**Comment by oncletom** [comment]
Dac, merci @paulgirard 🙂
