### ISSUE TITLE
publier un contenu de page People ou Objet très précise

### ISSUE THREAD

**Issue by oncletom** [medialab/website#120]

**Comment by AmelieVRL** [comment]
pour un project : voir Algoglitch (http://website-prod.medialab.sciences-po.fr/admin/#/activities/5ec9bfeb-37cc-492d-991b-4ebe7d2ba224)
pour un people : voir Thomas Tari (http://website-prod.medialab.sciences-po.fr/admin/#/people/1efb7d1f-a0b8-4e9e-8bac-255e88094f8a)
