### ISSUE TITLE
transmettre les ratios des images de couverture

### ISSUE THREAD

**Issue by oncletom** [medialab/website#121]
- [x] petit et grand pour activité/actualité/production
- [x] petit et grand ? pour people

# réponses 
image de couverture 
ratio 4/3
3 versions : 25 ,75, 150 caractères par ligne

@Yomguithereal 
Ratio des images People 4/3
La résolution d'image sur la page People peut aller jusqu'à 800px de largeur
Quid d'une version réduite de ces images pour la page Listing People ? ( 300 ou 400px de large )

**Comment by paulgirard** [comment]
Je ferme donc cette issue, @Yomguithereal intègre dans le système CMS.
