### ISSUE TITLE
Définir la singularité du médialab

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#13]
@julieblanc et Benjamin ont besoin de comprendre la singularité du médialab 
afin de proposer une conception adaptée

Sur proposition de @oncletom on a lancé un formulaire à l'équipe pour que chacun propose une réponse à la question.

**Comment by oncletom** [comment]
@paulgirard est-ce qu'il y a un artéfact qui contient les éléments qui répondent à cette question ?

**Comment by oncletom** [comment]
D'ac, merci :-)

**Comment by BenjmnG** [comment]
Nous avons synthétisé les notes que nous avons prises jusque là : 

[website/docs/2018-10-31-element_de_singularite/index.md](https://github.com/medialab/website/blob/master/docs/2018-10-31-element_de_singularite/index.md)
      
La liste est susceptible d'évoluer avec la discussion.
N’hésitez pas à ajouter vos idées ou mettre en doute les affirmations.
