### ISSUE TITLE
Premier Echec : plantage aprés "deploy"

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#130]
<img width="1126" alt="capture d ecran 2019-01-10 a 17 57 18" src="https://user-images.githubusercontent.com/37452370/50984111-4a776500-1501-11e9-9391-e8c4ebb18b61.png">

**Comment by paulgirard** [comment]
à priori un problème siùple à régler et non impactant.
Pas d'inquiétude mais à résoudre plus tard
