### ISSUE TITLE
CMS: page listing bug dans le filtrage du titre 

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#131]
le chamsp de filtrage ne retourne pas tous les résultats.
Exemple dasn news "controverse"
![image](https://user-images.githubusercontent.com/193478/50986332-d9d34700-1506-11e9-86e2-92fbd1d14571.png)
alors que 
![image](https://user-images.githubusercontent.com/193478/50986358-efe10780-1506-11e9-9643-71553f3a1873.png)

**Comment by Yomguithereal** [comment]
Je pense que je vais lâcher `fuse.js` et faire ma propre recherche floue.

**Comment by paulgirard** [comment]
all good
