### ISSUE TITLE
Rediscuter le nombre de tokens des slugs

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#133]

**Comment by oncletom** [comment]
C'est quoi un _token de slug_ ?

**Comment by Yomguithereal** [comment]
C’est le nombre de jetons par limaces :)

**Comment by Yomguithereal** [comment]
Plus sérieusement c’est le nombre maximum de « mots » qu’on accepte d’utiliser pour les urls. Du genre `seminaire-de-cloture-toflit18` ya 4 tokens. Pour l’instant on autorise que 6 tokens max mais peut etre qu’il faut augmenter ce max.

**Comment by oncletom** [comment]
Ça roule je comprends mieux, merci :-)

Y'a besoin d'une limite ?

**Comment by paulgirard** [comment]
On fixe une limite max à 15 tokens.
