### ISSUE TITLE
Impossible de modifier l'URL d'un lien existant dans un champ de texte riche

### ISSUE THREAD

**Issue by oncletom** [medialab/website#139]
Quand on clique à nouveau sur 🔗 , le champ s'affichera comme vide, et il faudra deviner/se souvenir quelle URL correspondait à cette portion de texte.

**Comment by Yomguithereal** [comment]
Oui il faut que je trouve un moyen de montrer/éditer le lien. Je pensais faire une forme de popover. Ca me semble moins contraignant que la modale. En tous les cas, un workaround pour le moment consiste à selectionner le lien et a ajouter un lien dessus (cela écrase l'existant).

**Comment by oncletom** [comment]
Ça roule. Si ça réouvre la même modale/popover que pour ajouter un lien, mais avec sa valeur actuelle, c'est amplement suffisant.

Ce qui est le plus simple/moins contraignant à implémenter de ton côté.
