### ISSUE TITLE
CMS : les select des "Related objects" ne sont pas perçus comme autocomplétables

### ISSUE THREAD

**Issue by oncletom** [medialab/website#142]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/138627/51090416-ee6c4500-177b-11e9-8a31-181e962336c8.png">

Y'a surement une piste facile à implémenter en jetant un œil à https://react-select.com

L'option "Popout" explicite super bien la distinction "taper pour chercher" et "défiler une liste pour cliquer sur un choix".

<img width="629" alt="image" src="https://user-images.githubusercontent.com/138627/51090454-5e7acb00-177c-11e9-8536-7b5512ae1cd9.png">

**Comment by Yomguithereal** [comment]
Tu peux me dire où tu as pris ce screenshot? On dirait du react-select mais je ne trouve pas ceci dans la doc.

**Comment by oncletom** [comment]
Je l'ai pioché ici : https://react-select.com/advanced#experimental
