### ISSUE TITLE
CMS : increase emphasis on main action button

### ISSUE THREAD

**Issue by oncletom** [medialab/website#143]
The contrast of the button makes it almost invisible when no help was provided.

Example:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/138627/51090595-51f77200-177e-11e9-8727-8f596165f8db.png">

**Comment by Yomguithereal** [comment]
@robindemourat quel kind de bouton on met?

**Comment by robindemourat** [comment]
Si on reste dans la sémantique de couleurs de bulma je tenterais un color `info` ou `warning` - on voit ça ensemble en direct quand tu veut.

**Comment by oncletom** [comment]
`info` ou `primary` c'est bien 🙂 

`warning`, je le vois bien pour un signalement de champs manquants avant même de cliquer sur le submit.
