### ISSUE TITLE
CMS : preview item

### ISSUE THREAD

**Issue by oncletom** [medialab/website#145]
People missed the preview links after creating a content. Likewise when a content was already existing.

As this was an expectation _after publishing_ or _updating_ a content, I suggest to put this action close to the Publish/Save button, in the fixed footer.

Optionnally, the preview link can be grayed out if there is no content created in the relevant language.

<img width="642" alt="image" src="https://user-images.githubusercontent.com/138627/51090677-cbdc2b00-177f-11e9-8e43-8080ce93e642.png">

**Comment by AmelieVRL** [comment]
Actions à réaliser au vue de ces commentaires:
- [ ] move the preview links to the fixed footer
- [ ] Deal the not saved/preview conflict and add a warning

**Comment by Yomguithereal** [comment]
Le bug "effaçant" les modifications a été corrigé.

**Comment by oncletom** [comment]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/138627/53431905-cebe7280-39f1-11e9-829e-f89bd513bb9b.png">

Ça fait le job 👍 Merci !
