### ISSUE TITLE
CMS : add an explicit content creation link

### ISSUE THREAD

**Issue by oncletom** [medialab/website#146]
People did not know what to do after creating/editing a content, in order to create a new one. It was not clear to them this action was solely available when clicking on the top menu item.

If #145 goes through, I suggest adding a "create content link" in the freed space at the top of the screen.

<img width="673" alt="image" src="https://user-images.githubusercontent.com/138627/51090700-3725fd00-1780-11e9-9354-43539234ded1.png">

**Comment by AmelieVRL** [comment]
Not sure the "create content link" should be in the tab area for UX reason : if I click in the area, I assume a new tab (in the same page) will be created and I am pretty sure it won't work that way.
I would rather add some contextual hover menu in the top screen menu.

**Comment by AmelieVRL** [comment]
The "create content link" has been add to the listing page : good job!

But what if I want to create a new object right after a saving operation. 
2 clicks are needed : one to charge the appropriated listing page + one to create the new object.

Should we optimize this?
