### ISSUE TITLE
CMS : confusion around duplicate slug

### ISSUE THREAD

**Issue by oncletom** [medialab/website#148]
It was unclear to participants what had to be done when a slug collision happened because of a similar title. They did not get an action would be offered to them when hitting the Publishing button. There was confusion around the fact the field was not editable.

I suggest moving the action close to the field, which would look like text (like `.button.is-text`), and to remove this information from the Publishing button.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/138627/51090799-24142c80-1782-11e9-9540-448fd7f609b5.png">

**Comment by Yomguithereal** [comment]
This is now fixed.
