### ISSUE TITLE
CMS : wording et explicitation des champs des formulaires

### ISSUE THREAD

**Issue by oncletom** [medialab/website#150]
Distinction pas évidente entre "Description" et "Content"

Par exemple, en créant une nouvelle production.

<img width="597" alt="image" src="https://user-images.githubusercontent.com/138627/51091130-6dff1180-1786-11e9-8a9a-27ad17751f94.png">

Les personnes qui ont manipulé le CMS ne savaient pas comment les distinguer, ni quoi ou comment le mettre.

Ce qui les a aidé après discussion : la longueur attendue, et les emplacements où le contenu s'affiche.

**Comment by AmelieVRL** [comment]
L'ensemble des labels des formulaire doit être explicité par des info-bulle ou des exemples en guise de place-holder.
@AmelieVRL et @paulgirard doivent rédiger un doc dans ce sens.

**Comment by paulgirard** [comment]
On va plutôt changer les noms et ajouter des descriptions des champs directement dans le CMS plutôt que dans un doc.
Vu avec @Yomguithereal faudra juste qu'on se coordonne pour ne pas générer trop de merge.

**Comment by oncletom** [comment]
Du coup, où est-ce que seront saisis les contenus de description si ce n'est pas dans un Google Doc ? (dans les settings du CMS ? C'est pas clair).

**Comment by paulgirard** [comment]
Les descriptions et titres des champs des formulaires seronts écrits directement dans le code des formulaires du CMS.

**Comment by oncletom** [comment]
Dac. Genre dans une Pull Request @Yomguithereal ajoute des placeholders pour ces descriptions, et @AmelieVRL rédige les textes ?
