### ISSUE TITLE
CMS : options/personnalisation des images ?

### ISSUE THREAD

**Issue by oncletom** [medialab/website#152]
J'ai ajouté une image dans un champ de texte riche.

J'aimerais ajouter un lien de sorte à ce que l'image soit cliquable sur le site. Je n'ai pas réussi à sélectionner l'image et cliquer sur "ajouter un lien".

Quand j'ajoute un lien et que j'upload une image, je ne peux plus choisir l'URL du lien : 

<img width="628" alt="screenshot 2019-01-13 at 23 05 09" src="https://user-images.githubusercontent.com/138627/51091203-be2aa380-1787-11e9-879f-a341585841cf.png">

**Comment by AmelieVRL** [comment]
Prévoir les options suivante pour les images :

- [ ] ajout d'un lien sur l'image et la rendre cliquable
- [ ] ajout d'une légende
- [ ] possibilité de resize (à voir en fonction de la maquette)
