### ISSUE TITLE
matérialisation des liens du champ contenu dans les pages objets

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#153]
Bonjour @BenjmnG et @JulieBlanc ,
après avoir vu les pages objets et regarder à nouveau le système de navigation, je me demandais comment vous aviez prévu de matérialiser les liens dans les contenus?
D'avance merci pour vos réponses,
Amélie

**Comment by BenjmnG** [comment]
Avec un léger retard,

Parle tu des hyperliens dans le corps de texte ? Ou des fichiers en liens à la fin de chaque page objet ?

Si c'est le premier cas, nous ferrons apparaitre cela dans la finalisation de la page Objet People, qui est désormais dans nos priorité.

**Comment by AmelieVRL** [comment]
Bonjour Benjamin,
En effet, je parlais des liens dans le corps du texte.
On verra donc ce que ça donne la semaine prochaine.
Merci, et bonne journée,
Amélie

Le mercredi 6 mars 2019, BenjmnG <notifications@github.com> a écrit :
> Avec un léger retard,
>
> Parle tu des hyperliens dans le corps de texte ? Ou des fichiers en liens
à la fin de chaque page objet ?
>
> Si c'est le premier cas, nous ferrons apparaitre cela dans la
finalisation de la page Objet People, qui est désormais dans nos priorité.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/nAD_JglKBUhJ_nf6nGLCDOHIrK2rgAwY1T9JAqEraTlkZhy4Vsm0qDAgsD8J3rI-hN55U7ZVd705UjJpoCirsp06Q5eCUZWZhDb-2xxOd4IFSG-hW6CZPcTWQj-mlcAFpkxdSXt8-_PyPaPGEdxorUxNBg=s0-d-e1-ft#https://github.com/notifications/beacon/Ajt6UqNnmUO6xfSjVgbzW-t_5GlNHMw6ks5vUB6KgaJpZM4Z-J4r.gif
>

-- 

Amélie Vairelles
Chargée de communication
Official Representative (OR) ICPSR
[image: Sciences Po]
CDSP | Médialab
27 rue Saint-Guillaume 75337 Paris cedex 07 France
T. +33 (0)1 45 49 52 75
amelie.vairelles@sciencespo.fr
www.sciencespo.fr
[image: Twitter Sciences Po] <https://twitter.com/sciencespo>
<https://www.facebook.com/sciencespo>
<https://www.linkedin.com/edu/school?id=12454>

**Comment by paulgirard** [comment]
@AmelieVRL toujours d'actualité ?

**Comment by AmelieVRL** [comment]
OK, on aurait pu forcer mais je pinaille, c'est bien comme ça!
