### ISSUE TITLE
CMS : le filtre de listing ne trouve pas un mot s'il suit un article avec apostrophe

### ISSUE THREAD

**Issue by thom4parisot** [medialab/website#154]
Je cherche "art", en pensant trouvé "État de l'art".

![image](https://user-images.githubusercontent.com/138627/51122143-7c4a3d80-1819-11e9-81b8-ce004ea644c7.png)

Même en cherchant le mot complet ("l'art"), il n'y a pas de résultat : 

![image](https://user-images.githubusercontent.com/138627/51122170-8e2be080-1819-11e9-9818-c7209d281096.png)

En cherchant "état", ça roule.

![image](https://user-images.githubusercontent.com/138627/51122208-a3a10a80-1819-11e9-88c2-f0dcbc6133eb.png)

**Comment by AmelieVRL** [comment]
Idem avec des parenthèses.
Je recherche EDGE  (projet n°10):
<img width="719" alt="capture d ecran 2019-01-14 a 16 31 50" src="https://user-images.githubusercontent.com/37452370/51122590-7e60cc00-181a-11e9-9c51-4902fc125af7.png">

En bas de casse, rien (en capital pareil):
<img width="707" alt="capture d ecran 2019-01-14 a 16 31 58" src="https://user-images.githubusercontent.com/37452370/51122635-8fa9d880-181a-11e9-8f5c-b36dfb44cff9.png">

Avec les parenthèses, rien :
<img width="713" alt="capture d ecran 2019-01-14 a 16 32 13" src="https://user-images.githubusercontent.com/37452370/51122639-933d5f80-181a-11e9-9175-0f1a2fe6eb63.png">

**Comment by oncletom** [comment]
YAY. Merci 🙂
