### ISSUE TITLE
CMS : une liste longue de Related People dépasse de mon écran

### ISSUE THREAD

**Issue by thom4parisot** [medialab/website#155]
![image](https://user-images.githubusercontent.com/138627/51122465-4194d500-181a-11e9-8114-47470f4da37c.png)

En 1440x, écran 13", Firefox.

**Comment by oncletom** [comment]
En ajoutant `flex-flow: row wrap;` à `.tags-container`, ça roule 👍 

![image](https://user-images.githubusercontent.com/138627/51122588-7dc83580-181a-11e9-91da-d2c839e18ba2.png)
