### ISSUE TITLE
CMS : est-ce qu'on a besoin d'un blockquote/citation dans le texte riche ?

### ISSUE THREAD

**Issue by oncletom** [medialab/website#158]
Par exemple, pour mettre ce texte (actuellement en italique) en citation : 

![image](https://user-images.githubusercontent.com/138627/51124144-df3dd380-181d-11e9-9a47-8c558f4661d0.png)

**Comment by Yomguithereal** [comment]
@AmelieVRL besoin de blockquote?

**Comment by AmelieVRL** [comment]
Je dirais que c'est mieux de le prévoir mais il faut voir avec Julie et
Benj si ca rentre dans leurs styles.

Amélie

**Comment by BenjmnG** [comment]
Up !

Toujours d'actualité ? Si oui, avez vous un article avec un exemple ?

**Comment by AmelieVRL** [comment]
Yep. Mais comme on n'a pas la fonctionnalité actuellement, on n'a pas d'exemple.
Je pense que ce serait utile en cas d'interview ou pour mettre un truc en exergue dans un article long.

**Comment by BenjmnG** [comment]
J'ai ajouté quelques règles CSS pour les citations.

![Screenshot_2019-08-06 Algoglitch médialab Sciences Po(1)](https://user-images.githubusercontent.com/10298798/62529400-dc004880-b83e-11e9-80f5-b981d7691485.png)





@Yomguithereal, il ne manque plus qu'a s'assurer que le CMS permet leur ajout
