### ISSUE TITLE
CMS / News : correspondance entre la date dans le titre de l'actu et Start Date ?

### ISSUE THREAD

**Issue by oncletom** [medialab/website#159]
Je suis en train de travailler sur #118

![image](https://user-images.githubusercontent.com/138627/51124323-56736780-181e-11e9-9f59-224e8b75cd5e.png)

Est-ce que le Start Date correspond à la date mentionnée dans le titre ? La Start Date n'est pas la "date de publication" ?

cc @AmelieVRL

**Comment by AmelieVRL** [comment]
En effet la start date varie selon le "type" de news et correspond soit à
une date que l'on souhaite définir soit à la date de publication comme suit:
- event : start date = date que l'on définit (date de l'evenement
généralement)
- post : start date = date de publication
- notice : start date = date que l'on definit (une deadline de candidature
par exemple)

Amélie


Le lun. 14 janv. 2019 à 17:14, Thomas Parisot <notifications@github.com> a
écrit :

**Comment by oncletom** [comment]
Merci @AmelieVRL. Du coup, `End Date` n'est vraiment requis que pour une news de type Post ? Ou ça vaut aussi pour Notice ?

**Comment by AmelieVRL** [comment]
En effet, pas nécessaire pour les news de type "post" ; par contre
potentiellement utile pour les Notice.

Amélie


Le sam. 19 janv. 2019 à 00:19, Thomas Parisot <notifications@github.com> a
écrit :
