### ISSUE TITLE
CMS : un bouton "Retour en arrière" dans les textarea ?

### ISSUE THREAD

**Issue by oncletom** [medialab/website#163]
Une personne s'est retrouvée bloquée dans un textarea face à un changement malencontreux. Elle cherchait le bouton "Revenir en arrière" (souvent signifié par ↶ ou autre). Il a fallu lui indiquer la technique du Control+Z pour la débloquer.

Y'a cette fonctionnalité de dispo dans le composant de texte riche ?

**Comment by Yomguithereal** [comment]
Oui, cette fonctionnalité est disponible dans le composant de texte riche. Il est aussi possible d'expliciter cette possibilité avec des boutons de contrôle (juste un booléen à change). On ne voulait pas saturer la barre de contrôle de l'éditeur cependant mais cela se discute.
