### ISSUE TITLE
Import et rendu d'un components

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#164]
Cher @Yomguithereal, cher tous,

Question React épineuse depuis quelques heures...

J'ai créé un _components_ topbar.js
```
import React from 'react';

const topbar = () => {
    return ( <header id="topbar"><p>Bref</p></header>);
}
```

Que je souhaite importer dans un template[ _activity.js_](https://github.com/medialab/website/blob/master/site/src/templates/activity.js)

J'importe donc mon component avec 
`import {topbar} from '../components/fragments/topbar.js';`

Mais où et comment appeler ma constante ensuite ?

Merci !

**Comment by Yomguithereal** [comment]
Bonjour @BenjmnG: ta topbar sera-t-elle affichée dans toutes les pages? Auquel cas je te conseille de l'importer dans le composant [Layout](https://github.com/medialab/website/blob/master/site/src/components/Layout.js) qui représente la structure générale commune à toutes les pages. Est-ce que cela conviendrait?

**Comment by Yomguithereal** [comment]
Une petite note: par convention, on a tendance à nommer les composants en TitleCase pour les distinguer. Dans notre exemple cela voudrait dire appeler le composant `TopBar` (de la même manière, le fichier peut s'appeler `TopBar.js` par cohérence).

**Comment by BenjmnG** [comment]
D'accord je noterai en TileCase

Bien, Layout conviendra dans ce cas.

Mais comment appeler mon composant ? 
Dois-je la placer au sein de la Const Layout ? Dans un return spécifique ? 
Ou est-ce bien plus simple ?

**Comment by Yomguithereal** [comment]
Pour appeler ton composant, il suffit de faire la chose suivante:

```jsx
import TopBar from '.....';

<TopBar />
```

Donc en situation dans `Layout`:

```jsx
const Layout = ({children, lang}) => {

  return (
    <StaticQuery
      query={graphql`
        query SiteTitleQuery {
          site {
            siteMetadata {
              title
            }
          }
        }
      `}
      render={data => (
        <>
          <Helmet
            title={data.site.siteMetadata.title}>
            <html lang={lang} />
          </Helmet>
          <div
            style={{
              margin: '0 auto',
              maxWidth: 960,
              padding: '0px 1.0875rem 1.45rem',
              paddingTop: 0
            }}>
            <TobBar />
            {children}
          </div>
        </>
      )} />
  );
};
```

**Comment by Yomguithereal** [comment]
En un sens, c'est comme si la fonction décrivant ton composant devenait un tag html custom.

@robindemourat me fait remarquer qu'il ne faut pas que tu oublies d'exporter le composant dans son fichier:

```jsx
import React from 'react';

const topbar = () => {
    return ( <header id="topbar"><p>Bref</p></header>);
};

// L'export ici:
export default topbar;
```

**Comment by BenjmnG** [comment]
Parfait, je vais donc appliquer cela.
Merci beaucoup.

Donc si `Layout.js` est commun à toute les pages, je comprends que si j'ai un élément très spécifique à importer sur la page Activité (imaginons une bar latéral), je devrais l'importer directement dans `activity.js`

**Comment by BenjmnG** [comment]
Le composant est bien exporté dans son fichier.
La Topbar s'affiche ^^

**Comment by Yomguithereal** [comment]
> Donc si Layout.js est commun à toute les pages, je comprends que si j'ai un élément très spécifique à importer sur la page Activité (imaginons une bar latéral), je devrais l'importer directement dans activity.js

Plutôt dans le composant `components/ActivityDetail.js`. Le template activity est plutôt la fonction qui s'occupe de formatter les données et de les passer à `ActivityDetail`. A priori, tu ne devrais pas avoir à toucher les fichiers dans le dossier `templates` (à part peut-être `index.js` qui représente la Home, mais on en reparlera).

**Comment by BenjmnG** [comment]
`ActivityDetail.js` D'accord,
Et bien cette affaire vu rondement menée
