### ISSUE TITLE
CMS : uploader les images des 7 projets actifs, ajuster la valeur du gamma et affiner le rendu ASCII

### ISSUE THREAD

**Issue by oncletom** [medialab/website#167]
Évoqué par @AmelieVRL.

**Comment by Yomguithereal** [comment]
Il est désormais possible de faire des expérimentations dans la page `/preview` du CMS (un lien existe sur la home du CMS).

Il me semble que le gamma n'est pas très dépendant de la resolution (nombre de rows). Ce qui est une bonne chose pour nous.
