### ISSUE TITLE
Publication référencées dans Spire, manquante dans le CMS 

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#180]
L'article "Savoirs contés" et de Thomas T. est renseigné dans Spire mais on ne le retrouve pas dans le CMS:
<img width="882" alt="capture d ecran 2019-02-01 a 14 59 58" src="https://user-images.githubusercontent.com/37452370/52127361-2e637100-2632-11e9-8eba-a2f7302eca54.png">

Thomas semble pourtant bien associé au Médialab dans Spire:
<img width="1216" alt="capture d ecran 2019-02-01 a 15 01 35" src="https://user-images.githubusercontent.com/37452370/52127420-4c30d600-2632-11e9-9bd5-c852cfe40294.png">

Que faire?

**Comment by paulgirard** [comment]
Cette publi est attaché à l'université Paris Est car c'est le lieux du doctorat.
```json

affiliation | {…}
-- | --
rec_class | Orgunit
name | PRES Université Paris-Est
rec_id | 2441/48chftgl84838og4sninai2j77
affiliation_role | doctoral-researcher
agent | {…}
rec_class | Person
download_number | 0
name_family | Tari
name_given | Thomas
profile_complet | false
publication_number | 0
rec_id | 2441/21cu4qqsqk8b0ppce1jcdtp9qt
rec_id_name | 2441/21cu4qqsqk8b0ppce1jcdtp9qt{TARI Thomas}
view_number | 0
role | aut
scpo_center_id | 2441/48chftgl84838og4sninai2j77
scpo_center_id_name | 2441/48chftgl84838og4sninai2j77{PRES Université Paris-Est}
```

Soit on voit si c'est possible d'ajouter le médialab qq part dans SPIRE (voir avec la bib) pour cette publi, soit on recopie dans le CMS.

**Comment by AmelieVRL** [comment]
@audreybaneyx il faudra que l'on regarde ça ensemble car je ne crois pas que Thomas puisse régler ça depuis son compte Spire.
