### ISSUE TITLE
Associer des activités

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#182]
Certains projets sont bornés en dates (cf. type de financements), évoluent et se poursuivent par d'autres projets.
Pour mettre cette évolution en perspective, il serait bon de pouvoir lier des activités entres elles.
Ton avis @paulgirard ?

Si ça te semble pertinent, il faudrait ajouter le champ "related activities" dans activities

**Comment by paulgirard** [comment]
Le modèle a été modifié en ce sens mais ni le CMS ni le site.
Je passe ça en souhaitable et on fait plus tard @AmelieVRL ?
Ou tu maintiens indispensable ?

**Comment by AmelieVRL** [comment]
J'ai changé le statut mais je maintiens que c'est une fonctionnalité hyper utile, donc ce serait bien de ne pas l'oublier!
