### ISSUE TITLE
Import Scss in React

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#188]
@YomGuithereal

Avant que j'oublie :
J'ai constaté qu'une fois le site lancé en local avec React, celui-ci a une fâcheuse tendance à importer pour chaque page l'ensemble des feuilles de style du site.

Cela induit un écrasement de certaines propriétés et la migration d'autres vers des pages indut

Ex: Definir un style h3 sur une page reviens a le définir sur l'ensemble des pages.

Je peux aisément palier a ce problème en précisant le parent de chaque élément. Pas de soucis. Toutefois le fais que toute les feuilles de style soit chargé tout le temps me semble un peu inutile.

Tom me suggère que cela a à voir avec le Live Reload. Qu'en penses-tu ?

Je précise, évidemment, que j'importe à chaque template de page une feuille de style spécifique et 'on globale.

Merci, merci !

**Comment by Yomguithereal** [comment]
> Tom me suggère que cela a à voir avec le Live Reload. Qu'en penses-tu ?

Je ne vois pas trop pourquoi, comme ça. Tu peux vérifier ça en faisant `gatsby build` et ensuite `gatsby serve` et voir si ça change qqchose. Si ça change qqchose alors oui c'est probablement lié au live reload.

> Toutefois le fais que toute les feuilles de style soit chargé tout le temps me semble un peu inutile.

En général, aujourd'hui, les sites webs ne chargent qu'une unique feuille de style qui fonctionne pour toutes les pages. Comme ça elle est cachée et chargée une unique fois par le navigateur et n'est plus rechargée ensuite.

> Je précise, évidemment, que j'importe à chaque template de page une feuille de style spécifique et 'on globale.

Il n'y aurait pas un cas où tu importe un composant dans une page qui lui même fait appel à une autre feuille de style d'une autre page, par exemple?

> Je peux aisément palier a ce problème en précisant le parent de chaque élément. Pas de soucis. Toutefois le fais que toute les feuilles de style soit chargé tout le temps me semble un peu inutile.

A défaut oui. Tu peux me pointer un exemple de page où plus de style que nécessaire est chargé? Que je vois d'où peut venir le problème?

**Comment by Yomguithereal** [comment]
J'ai essayé plusieurs truc mais avec des règles sur `body` ya pas vraiment moyen de demander au système d'encapsuler.

**Comment by BenjmnG** [comment]
Conclusion, je me débrouille pour préciser toute mes règles CSS par rapport à ses parents

**Comment by Yomguithereal** [comment]
Seulement celles qui tapent sur des choses aussi larges que le `body` par exemple. Le reste doit déjà utiliser un système de classe, non? Ou alors tu réutilises des noms de classes pour différentes pages alors que ces classes désignent quelque chose de différent? Auquel cas oui il faut wrapper par rapport à un parent logique.

**Comment by oncletom** [comment]
Dans d31880337ce3b86958ccb310f62261814d09796c j'ai rajouté des classes sur le body (si c'est à ça que vous faites référence).

**Comment by BenjmnG** [comment]
@Yomguithereal Il y a quelque cas où nous n'avions pas eu recours aux classes car la logique de la page HTML nous permettait de faire cette économie. Mais bref, en conclusion c'est gérable. 

Exact @oncletom, c'est justement ce sur quoi nous allons nous reposer pour résoudre le problème de méli-mélo entre les feuilles de style. Merci encore par ailleurs !
