### ISSUE TITLE
Image Personne : Definir une class suivant le ratio ?

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#190]
Les photos des personnes sont très jolie mais dans des formats forts hétéroclite ( Portrait, paysage, ... ) notamment disposé sur la page equipe.
Comment faire pour harmoniser tout cela sans étirer ou écraser ? 
L'ajout d'une classe à ces images en fonction de leurs Ratio serait la solution je crois. 

Sauf si tu as, @JulieBlanc , une astuce sans classe et pure CSS.

**Comment by Yomguithereal** [comment]
Les images telles quelles te sont données dans les templates sont toutes en 4:3. Je ne suis pas certain de comprendre ce que tu veux dire.

**Comment by JulieBlanc** [comment]
Nous avions pas convenu que les images seraient recropées dans le CMS ?

**Comment by Yomguithereal** [comment]
> Nous avions pas convenu que les images seraient recropées dans le CMS ?

Si et c'est bien le cas. Amélie définit les crops dans le CMS et ceux-ci sont envoyés au site statique.

**Comment by BenjmnG** [comment]
Mea Culpa,
Le Dump de Donnée contenait des images People en 4:3 et d'autre en format libre.
J'ai malencontreusement fait liens vers les formats libres alors que ton dernier Push @Yomguithereal donne un accés rapide vers chemin via l'argument `coverImage`

**Comment by BenjmnG** [comment]
Je suis quand même bien foutu de passer du temps à faire des liens vers des images inutiles...
