### ISSUE TITLE
comment atteindre "eumid" ?

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#192]
Je cherche à afficher la valeur contenue dans "enumid" pour les types de production, comment je fais ?

j'ai essayé `{p.type.enumId}`, `{p.type.productionTypes}`, `{p.enumId}`, `{p.productionTypes}`

Le modèle de données:
```
"type": {
      "title": "Type de la production",
      "type": "string",
      "enum": [
        "article",
        "book",
        "communication",
        "thesis",
        "grey",
        "datascape",
        "website",
        "software",
        "code",
        "exhibition",
        "simulation",
        "workshop",
        "conference",
        "media"
      ],
      "enumId": "productionTypes"
    },
```

**Comment by Yomguithereal** [comment]
Dans les données tu n'as que `p.type` qui est une chaîne représentant un identifiant technique pouvant avoir une valeur telle que tu les vois listées dans type.enum dans le schéma.

Mais je suppose que tu as besoin du label de ce type, en anglais ou en français, non? Auquel cas, je peux te rajouter un champ `p.typeLabel` avec `p.typeLabel.fr` et `p.typeLabel.en`. Ca te semble bien?

**Comment by Yomguithereal** [comment]
Ou alors j'ai mal compris et tu souhaites itérer sur les types de productions pour faire le sommaire à gauche?

**Comment by JulieBlanc** [comment]
je souhaite avoir à la fois le français et l'anglais mais aussi accéder aux "groupes" de types pour faire le menu à gauche. par exemple les articles, communication, books, thesis, grey appartiennent au groupe "publications"

**Comment by Yomguithereal** [comment]
2 options:

1. Soit je te passe les données nécessaires dans le template (probablement un array avec les différent types et leurs labels etc.).
2. Soit tu en code 2 en dur dans le template et je passe derrière pour faire les branchement avec les données.

**Comment by JulieBlanc** [comment]
j'ai essayé de faire une fonction qui disait quelque chose comme `if (p.type === "artile")` alors tu me retournes "publication" mais ça n'a pas du tout marché. 
Donc soit tu fais l'array direct soit il faut faire la conction

**Comment by Yomguithereal** [comment]
Faisons 2. alors. Template la chose comme tu le ferais en dur dans votre prototype et je passerai derrière pour "dynamiser" avec les données.

**Comment by JulieBlanc** [comment]
Je comprend pas très bien ce que tu veux dire par "template en dur". j'ai indiqué dans le fichier où cela doit apparaître, c'est cela que tu souhaitais ?

```
<p className="type" data-icon="production">
   { {p.productionTypes} - {p.type} }
</p>
```
C'est p.productionType qui ne marche pas du coup

**Comment by Yomguithereal** [comment]
Par template en dur j'entends ne pas utiliser les variables pour les cas qui te posent problème. Là par exemple ça voudrait dire faire:

```jsx
<p className="type" data-icon="production">
   Publication - Article
</p>
```

Par exemple.

**Comment by Yomguithereal** [comment]
Donc ça ne sera pas dynamique, donc pas fonctions des variables du template mais je passe derrière pour ajouter la logique.

**Comment by Yomguithereal** [comment]
J'aurais un peu de temps lundi en milieu d'après-midi pour voir ça en live si tu veux. Sinon dis-moi quand je peux passer sur les fichiers pour dynamiser et/ou ajouter les données dont tu as besoin.

**Comment by oncletom** [comment]
@Yomguithereal je peux m'en occuper :-)

**Comment by oncletom** [comment]
> Mais je suppose que tu as besoin du label de ce type, en anglais ou en français, non?

J'ai l'impression que le label français/anglais serait utile, s'il peut s'obtenir à partir de la valeur du champ `type` (stocké comme un ID si je comprends bien).

J'ai aussi l'impression que pouvoir accéder à la liste de l'`enum` d'une manière ou d'une autre peut être utile mais je n'en suis pas sûr.

**Comment by Yomguithereal** [comment]
> J'ai l'impression que le label français/anglais serait utile, s'il peut s'obtenir à partir de la valeur du champ `type` (stocké comme un ID si je comprends bien).

Pour les items de chaque modèle, oui clairement. Je vais ajouter ça bientôt.

> J'ai aussi l'impression que pouvoir accéder à la liste de l'`enum` d'une manière ou d'une autre peut être utile mais je n'en suis pas sûr.

Je compte l'ajouter comme un node graphql pour pouvoir le passer facilement aux templates. Mais j'ai besoin d'expérimenter un peu parce que je ne sais pas encore quelle serait la meilleure forme pour l'intégration: un index, une liste ordonnée d'objets...

**Comment by JulieBlanc** [comment]
Oui, le français/anglais serai utile.
Pour la liste `"enumId": "productionTypes"` qui est dans un autre fichier json, j'ai besoin d'y accéder d'une 'manière ou d'une autre pour certains endroits. Soit par les données json soit en faisant une fonction à partir des données `type`. (ex: si la production est un article, alors c'est une publication)
Je suis encore en train de travailler sur une autre branche, la branche `filtres-listing`, je vous dis quand je la merge ?

**Comment by Yomguithereal** [comment]
Alors, concernant tout ça:

1. Le template de liste de production a désormais accès à une nouvelle variables `types` contenant les types & sous-types de productions organisés de la manière suivante:

```js
[
  {
    "label": {
      "en": "Publications",
      "fr": "Publications"
    },
    "values": [
      {
        "type": "article",
        "label": {
          "en": "Article",
          "fr": "Article"
        }
      },
      {
        "type": "communication",
        "label": {
          "en": "Communication",
          "fr": "Communication"
        }
      },
      {
        "type": "book",
        "label": {
          "en": "Book",
          "fr": "Livre"
        }
      },
      {
        "type": "thesis",
        "label": {
          "en": "Thesis",
          "fr": "Thèses"
        }
      },
      {
        "type": "grey",
        "label": {
          "en": "Grey literature",
          "fr": "Littérature grise"
        }
      }
    ]
  },
  {
    "label": {
      "en": "Tools",
      "fr": "Outils"
    },
    "values": [
      {
        "type": "software",
        "label": {
          "en": "Software",
          "fr": "Logiciel"
        }
      },
      {
        "type": "code",
        "label": {
          "en": "Code",
          "fr": "Code"
        }
      }
    ]
  },
  {
    "label": {
      "en": "Web editions",
      "fr": "Éditions web"
    },
    "values": [
      {
        "type": "datascape",
        "label": {
          "en": "Datascape",
          "fr": "Datascape"
        }
      },
      {
        "type": "website",
        "label": {
          "en": "Website",
          "fr": "Site web"
        }
      }
    ]
  },
  {
    "label": {
      "en": "Media",
      "fr": "Médias"
    },
    "values": [
      {
        "type": "media",
        "label": {
          "en": "Media",
          "fr": "Média"
        }
      }
    ]
  },
  {
    "label": {
      "en": "Situations",
      "fr": "Situations"
    },
    "values": [
      {
        "type": "exhibition",
        "label": {
          "en": "Exhibition",
          "fr": "Exposition"
        }
      },
      {
        "type": "workshop",
        "label": {
          "en": "Workshop",
          "fr": "Atelier"
        }
      },
      {
        "type": "simulation",
        "label": {
          "en": "Simulation",
          "fr": "Simulation"
        }
      },
      {
        "type": "conference",
        "label": {
          "en": "Conference",
          "fr": "Conférence"
        }
      }
    ]
  }
]
```

2. Les productions ont désormais: `p.typeLabel.en` et `p.typeLabel.fr` dans lequel se trouve le label qui va bien.

Je te laisse me dire si cela te convient @JulieBlanc et le cas échéant je répliquerai cette logique aux autres modèles.

**Comment by JulieBlanc** [comment]
avec ceci:` {lang === "fr" ? p.typeLabel.fr : p.typeLabel.en}` il me met une erreur, je dois refaire `npm run load` avant ? (jai bien pull)

Du coup je ne comprend pas très bien ce à quoi l'on accède avec `p.typeLabel`, aux groupes ? (publication, webpublication, etc.) 

`p.typeLabel` = les groupes de types ?
 `p.type` = les types ?

**Comment by Yomguithereal** [comment]
Tu peux faire ça:

```js
p.typeLabel[lang]
```

à la place de ça:

```js
{lang === "fr" ? p.typeLabel.fr : p.typeLabel.en}
```

`p.type` = le code du type
`p.typeLabel` = les labels du type dans les différentes langues

J'ai oublié de te mettre le groupe. Je vais t'ajouter ça.

> avec ceci:` {lang === "fr" ? p.typeLabel.fr : p.typeLabel.en}` il me met une erreur, je dois refaire `npm run load` avant ? (jai bien pull)

Tu peux me donner une page d'exemple?

**Comment by Yomguithereal** [comment]
Ok. Je viens de push un commit. Tu as désormais `p.group` et `p.groupLabel` en prime et j'ai corrigé le pb qui faisait que ta condition ne pouvait pas marcher parce que j'avais oublié de mettre à jour la query.

**Comment by JulieBlanc** [comment]
Il y a une erreur pour les `group` lors de la compilation: 

<img width="1440" alt="capture d ecran 2019-02-25 a 21 30 55" src="https://user-images.githubusercontent.com/25477334/53366854-e12ea280-3944-11e9-86c9-08eac80eabf4.png">

**Comment by Yomguithereal** [comment]
Je n'arrive pas à reproduire. Tu as bien pullé les derniers commits? Essaye aussi de faire un `npm run clean` dans `site` pour vider toute forme de cache.
