### ISSUE TITLE
GLib-CRITICAL et coverImage

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#193]
Bonsoir,

Petite issue désespéré. Il s'agit d'un plantage du `npm run build` que je ne comprend pas totalement. Ainsi il m'est difficile d'y apporter une solution...

Je comprends que cela a avoir avec l'appel du nœud ` imageCover`. 
Apparement celui-ci se prétend comme manquant et son passage à la moulinette  GraphQL en devient difficile...

Je précise que mon incompréhension vient aussi du fait que cette erreur est inédite, à savoir que la construction des pages se déroulait à merveille la dernière fois...

Si vous avez une idée ?
Bon dimanche ou Bon lundi à tous !

 

```
The GraphQL query from /mnt/b/_Software/UniServerZ/www/medialab/website/site/src/templates/people-list.js failed.

Errors:
  Input file is missing

  GraphQL request (7:9)
  6:         lastName
  7:         coverImage {
             ^
  8:           url

URL path:
  /people
Context:
  {
    "lang": "fr"
  }
Plugin:
  none
Query:
  query mntBSoftwareUniServerZWwwMedialabWebsiteSiteSrcTemplatesPeopleListJs3696475652 {
    allPeopleJson {
      edges {
        node {
          firstName
          lastName
          coverImage {
            url
          }
          slugs
          id
          domain
          active
          membership
          cover {
            file
            crop {
              height
              width
            }
          }
          status {
            fr
            en
          }
          role {
            fr
            en
          }
        }
      }
    }
  }


(sharp:5075): GLib-CRITICAL **: 17:17:56.699: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:5075): GLib-CRITICAL **: 17:17:56.726: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:5075): GLib-CRITICAL **: 17:17:56.757: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:5075): GLib-CRITICAL **: 17:17:56.762: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:5075): GLib-CRITICAL **: 17:17:56.766: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:5075): GLib-CRITICAL **: 17:17:56.771: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:5075): GLib-CRITICAL **: 17:17:56.779: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(sharp:5075): GLib-CRITICAL **: 17:17:56.789: g_hash_table_lookup: assertion 'hash_table != NULL' failed

```

**Comment by Yomguithereal** [comment]
As-tu récemment réinstallé tes dépendances? Il semblerait que la `sharp` ait des problèmes. Sur quelle OS codes-tu?

**Comment by BenjmnG** [comment]
Ah bonsoir Bon samaritain du dimanche soir
J'ai fait une réinstalle cette après-midi après les premiers plantages.
Et je code sur Ubuntu pour Windows ( WSL)

**Comment by BenjmnG** [comment]
Me conseils-tu de reinstaller l'entièreté des dépendances ? Ou de down-grader ma version du module Sharp ?

**Comment by Yomguithereal** [comment]
Sinon essaye de `rm -rf node_modules` dans `site` puis `SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install sharp` puis `npm i`

**Comment by BenjmnG** [comment]
Je m'execute.
SHARP_IGNORE toujours dans site ?

**Comment by Yomguithereal** [comment]
Yup

**Comment by BenjmnG** [comment]
Échec pour le moment  : /

**Comment by BenjmnG** [comment]
`fichtre`

Profite de ta soirée, on regardera cela demain.

**Comment by Yomguithereal** [comment]
Je donne cours demain matin. Je serai disponible dans l'après-midi.

**Comment by BenjmnG** [comment]
D'accord,
Pas de soucis. 
Le problème n'est pas sur ma seconde machine. J'avancerai avec.

**Comment by JulieBlanc** [comment]
Du coup, c'est le même problème de mon côté vu que j'ai mis à jour le master de mon côté avant de faire une merge request... Dis-moi lorsque c'est résolu demain @Yomguithereal, je pourrais faire accepter mon merge-request ensuite

**Comment by Yomguithereal** [comment]
Après ça ressemble vachement à un fichier qui manque qqpart: `Input file is missing`. Comme si il manquait une image vers laquelle pointent vos données. Vous avez changé des données à la main? Je n'arrive pas à reproduire ce problème de mon côté.

**Comment by BenjmnG** [comment]
Des nouvelles : 

En fait j'ai ce problème sur mes deux machines. Le soucis d'hier venat en partie du fait que je me suis borné avec la commande `npm run build` au lieu de `dev`.
Avec la commande `dev` l'erreur est toujours valable mais non contraignante.
Cette erreur est donc valable pour moi depuis mercredi / jeudi

- Pour les données, nope ! Elles sont de premières main.
- J'ai constaté que cela commence à planter lors de la construction de la page _people/warren-sack_

**Comment by JulieBlanc** [comment]
Pourtant, de mon côté, j'ai juste mis à jour la branche `master`  et utilisé uniquement la commande `npm run dev` et j'ai le même problème. Impossible d'accéder à la moindre page... 

Ma fenêtre de navigateur est blanche et il y a écrit dans la console:
> Failed to load resource: the server responded with a status of 404 (Not Found)

![capture d ecran 2019-02-25 a 11 54 04](https://user-images.githubusercontent.com/25477334/53332655-24145a00-38f4-11e9-902e-16416c2dc7c1.png)

**Comment by BenjmnG** [comment]
Sur cette dernière erreur, c'est moi qui ai pushé un commit foireux. Sorry
J'ai d’ailleurs pushé un correctif _Fix the Fix Syntax Image_ il y a une heure

Ce dernier enlève les commentaire de la ligne 11 et 13  de respectivement  `PeopleListing.js` et `PeopleDetail.js`

`import Img from './assets/images/sample/D-Cardon-bis.jpg';
`

Définnisant ainsi la valeur `Img`

**Comment by Yomguithereal** [comment]
@BenjmnG  Ok. J'ai une piste. Est-ce que tu peux essayer de changer le nom du fichier dans `cover.file` de warren sack dans `data/people.json` et de renommer ce fichier dans `data/assets` puis faire `npm run clean` dans `site` et ensuite relancer le bousin? Je me demande si c'est pas un pb avec les charactères unicode du nom de fichier.

**Comment by Yomguithereal** [comment]
@JulieBlanc de ton côté tu travailles sur un linux?

**Comment by BenjmnG** [comment]
Ok j'essaye cela

Ps : Julie travaille sur Mac

**Comment by Yomguithereal** [comment]
> Ps : Julie travaille sur Mac

C'est fou. J'arrive pas à avoir la même erreur que vous. Je suis sur mac aussi. Je pensais que c'était un truc d'OS mais visiblement pas.

**Comment by BenjmnG** [comment]
Il est vrai.

Si cela n'arrive qu'a nous et pas à toi, sache que la seul chose qui lie nos configuration avec Julie est le DUmp de donnée que tu nous as donné Mercredi. 

Alors Bingo !!
Par contre j'ai du modifier ces élément directement dans le `dump` sinon c'étais inopérant.

Je découvre pour la première fois la moue de Warren

``

**Comment by Yomguithereal** [comment]
> le dump de donnée que tu nous as donné Mercredi.

Figure toi que j'ai essayé avec ce dump exact  :).

> Par contre j'ai du modifier ces élément directement dans le `dump` sinon c'étais inopérant.

Marrant. Comme si vos OS avaient refusé de copier les fichiers ou avaient normalisé le chemin en enlevant l'apostrophe unicode.

**Comment by BenjmnG** [comment]
> Figure toi que j'ai essayé avec ce dump exact :).

So professional!

Merci beaucoup pour ton suivi en tout cas
@JulieBlanc Est-ce bon de ton coté ? Je vous laisser fermer cette issue

**Comment by oncletom** [comment]
J'ai poussé un commit dans `filtres-listing`, il n'y a plus d'erreur.
