### ISSUE TITLE
Créer une fonction sur react (avec données)

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#195]
J'essaie de faire quelque chose de très simple, passer des données à travers une fonction et pourtant je n'y arrive pas.

J'ai créé un fichier avec la fonction, qui contient ceci:  
```js
function DateNews(news){
    return <span class="startDate">{news.startDate}</span><span class="endDate">{news.endDate}</span>;
}
export default DateNews;
```

La fonction est ensuite liée à un autre fichier (jusqu'ici tout va bien):
```js
import FilterNews from './fragments/pageListe/FilterNews.js';
```

Puis je l'appelle dans le code: 
```js
<DateNews startDate={news.startDate} endDate={news.endDate} />
```

Les données ne passent pas, je pense que cela provient de `news`dans `function DateNews(news)`, je ne suis pas très sûr que c'est comme cela qu'il faut faire.

@Yomguithereal, @htomas, de l'aide ? Merci :)

**Comment by Yomguithereal** [comment]
Alors,

Ton deuxième exemple de code ne montre pas le bon import (`DateNews` vs. `FilterNews`). Mais je pense que ce n'est qu'une typo de l'issue.

Là comme ça je ne vois pas de soucis autre que celui-ci. N'hésite pas, dans `DateNews` à faire un `console.log(news)` pour regarder dans la console ce qui est effectivement passé à ton composant.

**Comment by Yomguithereal** [comment]
Aussi, en JSX il faut utiliser `className` et non `class`.

**Comment by Yomguithereal** [comment]
N'hésite pas, aussi à commit le code, si il build, et je pourrai directement regarder de mon côté ce qui ne va pas.

**Comment by JulieBlanc** [comment]
Oui pardon, c'est bien 
`import DateNews from './fragments/DateNews.js';` que j'importe

**Comment by JulieBlanc** [comment]
J'ai trouvé, il fallait une balise englobante + importer React

```js

import React from 'react';

function DateNews(news){
	console.log(news);
	return <><span className="startDate">{news.startDate}</span><span className="endDate">{news.endDate}</span></>;
	
}
export default DateNews;
```

**Comment by Yomguithereal** [comment]
Ah oui, je n'avais pas remarqué que ta fonction renvoyait 2 `span`. Désolé.
