### ISSUE TITLE
Formater les dates dans la fonction DateNews

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#198]
J'ai fait un fonction pour formater les dates en fonction de si le jour/mois de début et de fin sont les mêmes.

Il y a des choses qui ne fonctionne pas très bien, par exemple `startDateString.substr(5, 10)`ne va pas donner la même chose en s'affichant dans la console et dans le site lui-même.

Ensuite, il faudrait formater les dates avec les mois en toutes lettres et le faire en fonction de la langue.

Est-ce que quelqu'un peut jeter un coup d'oeil à la fonction et la terminer ? Merci :)

**Comment by Yomguithereal** [comment]
Je suis en train de corriger les données pour que tu n'aies jamais de date avec seulement une heure mais pas l'horaire. En attendant ça peut valoir le coup d'avoir une condition qui vérifie ça et qui agit en condition.

> Ensuite, il faudrait formater les dates avec les mois en toutes lettres et le faire en fonction de la langue.

Je crois qu'on a dit ce matin que @BenjmnG était sur le coup.

Concernant `substr`, je crois que tu confonds la méthode `substr(start, length)` qui coupe la chaîne en partant de `start` jusque `start + length` et la méthode `slice(start, end)` qui coupe la chaîne en partant de `start` jusque `end`.

J'ai essayé vite fait de remplacer tes `substr` par des `slice` et ça avait l'air de corriger le truc. Je te laisse vérifier.

**Comment by BenjmnG** [comment]
Je m'occupe de la traduction.

>  ça peut valoir le coup d'avoir une condition qui vérifie ça et qui agit en condition

J'ai un enjeux similaire sur le composant agenda. Tenez moi au courant si tel fonction existe

**Comment by oncletom** [comment]
> Ensuite, il faudrait formater les dates avec les mois en toutes lettres et le faire en fonction de la langue.

Y'a un exemple de date formatée en FR/EN dans `ProductionListing.js`.

```
import {format as formatDate, getYear, parseISO} from 'date-fns'
import {en, fr} from 'date-fns/locale'
```

Avec des infos d'utilisation https://date-fns.org/v2.0.0-alpha.27/docs/Getting-Started et https://date-fns.org/v2.0.0-alpha.27/docs/I18n

**Comment by BenjmnG** [comment]
Exact, je pensais justement à cet exemple.

**Comment by JulieBlanc** [comment]
Les dates en entrée ne semblent pas être au bon format pour pouvoir utiliser la fonction, j'ai mis en commentaire ce que j'ai fait si tu veux regarder @oncletom
