### ISSUE TITLE
Modèle de donnée - Homepage

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#199]
Hello,

Nous aurions besoins de passer plusieurs information supplémentaire vers la page d'accueil.
Je suis encore en plein milieu de cette intégration, ainsi d'autre besoin s’ajouteront sans doute dans les jours qui arrive.

Agenda (rdv)
- **url** de la page actualité
- **label** pour décrire l'évenement 
![image](https://user-images.githubusercontent.com/10298798/53482409-72099900-3a7f-11e9-8f66-72acbbb20f67.png)

- **place** pour definir le lieu
- **imageProcessed** pour illustrer tout cela

En ce moment (grid)
- **imageProcessed** pour illustrer tout cela

**Comment by Yomguithereal** [comment]
Je t'ai rajouté le label et la place. Pour l'url de la page en question je vais ajouter un truc bien dans le turfu. Je travaille sur les images processed dans l'aprem.

Au cas où, si tu veux rajouter des trucs sans passer par moi, en gros il faut mettre à jour la query graphql ici: https://github.com/medialab/website/blob/master/site/src/templates/index.js#L7-L72
