### ISSUE TITLE
légende/crédit des images

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#202]
Pour toutes images que ce soit dans le contenu du texte ou sur les images de couverture :
- [x] ajouter dans le modèle de donnée : un texte simple
- [ ] rendu en over genre tooltip ou autre

**Comment by BenjmnG** [comment]
Est-ce que cette donnée existe ?
Je vois un lien d'usage avec #203

**Comment by paulgirard** [comment]
En effet il y a un lien.
Non les données n'existent pas encore à ma connaissance.
@AmelieVRL je te laisse mettre la priorité.

**Comment by Yomguithereal** [comment]
@AmelieVRL @paulgirard je viens d'ajouter les crédits pour les images de couverture dans le CMS. Je passe aux crédits des images du contenu.

**Comment by AmelieVRL** [comment]
Merci beaucoup @Yomguithereal 
Je ne le vois ni sur la pprd ni sur la prod? 
Peux tu me signaler où c'est accessible pour que j'ajoute de compléter ce champ à ma todo edito?

**Comment by Yomguithereal** [comment]
Ce ne sera en prod/pprd que ce soir quand je pusherai toutes mes updates de la journee.

**Comment by Yomguithereal** [comment]
J'ai rajouté le support des crédits sur les images dans le contenu riche. On a un petit bug de focus de l'éditeur qui va avec mais ni @robindemourat ni moi n'arrivons à trouver une solution aisée.
