### ISSUE TITLE
trier la liste ProductionListing selon les groupLabel

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#209]
Les listes dans productionListing doit être triée par groupLabel selon le lien de la page.

si le lien de page = /productions, renvoie toutes les productions
si lien de page = productions/publications, renvoie uniquement les p.groupLabel = publications
si lien de page = productions/editionsweb, renvoie uniquement les p.groupLabel = editionsweb
si lien de page = productions/tools, renvoie uniquement les p.groupLabel = tools
si lien de page = productions/situations, renvoie uniquement les p.groupLabel = situations
si lien de page = productions/media, renvoie uniquement les p.groupLabel = media

(mis en commentaire dans le fichier)

**Comment by paulgirard** [comment]
@Yomguithereal il y a un problème(?) dans le routing, les sous-pages n'existent pas elles devraient toutes appeler le même productionsListing.js
Ça dépasse mes capacités gatsby.
Uen fois que le routing est réglé je peux me débrouiller en revanche.
On en reparle

**Comment by Yomguithereal** [comment]
@BenjmnG je viens de m'occuper du routing des sous-pages dans le filtre à gauche dans le dernier commit. Je vais m'occuper des sous-catégories en bas et vérifier que tout roule niveau données.

**Comment by Yomguithereal** [comment]
J'ai fixé 2-3 trucs. Concernant les sous-catégories, il faut que tu me dises si toutes les classes existent déjà dans le CSS ou pas.

**Comment by BenjmnG** [comment]
A ce stade aucune règles CSS ne s'applique aux sous-pages. 
Aucune class spécifique aux sous pages n'est définie dans le CSS

A ce stade nous avons seulement un id #liste-productions.
Soit on change cet ID en fonction de la sous page ( #liste-website, #liste-article, ... )
Soit on prétend que cet id #liste-productions est commun à toutes les pages et on l'affine avec une class.
Cette solution demande de modifier trois pétouille dans le CSS

@JulieBlanc  toi qui a construit ces filtres ?

**Comment by JulieBlanc** [comment]
Je comprends pas ton dernier commentaire Benjamin. C'est normal qu'il y ait que l'id #liste-productions puisqu'on change de page, on a pas besoin de changer cet id, il n'intervient pas dans les filtres. Les "filtres" à ce niveau, c'est simplement aller à une autre page

**Comment by oncletom** [comment]
J'ai l'impression que c'est OK (le tri selon groupLabel) ? Sinon je ne comprends pas ce qui manque et comment observer le problème.

J'ai trié les productions par date décroissante (jusqu'au niveau du mois).

**Comment by BenjmnG** [comment]
Hello, Je ne sais pas si cela est lié mais j'ai ce problème depuis.
Est-ce pareil chez vous ?

`` 
TypeError: b.date is null
ProductionListing/<
src/components/ProductionListing.js:26

  23 |    }
  24 | 
  25 | 
> 26 |    list.sort((a, b) => b.date.localeCompare(a.date)).forEach(production => {
  27 |      let year = getYear(parseISO(production.date));
  28 | 
  29 |      // TODO: this is a temporary workaround
```

**Comment by paulgirard** [comment]
Le problème vient du fait que des productions n'ont pas de date.
Ce qui n'est pas normal... 
J'ai ajouté un filtre pour virer les productions sans date du listing.
C'est un contournement du vrai problème qui réside dans les données.
J'ouvre une issue à ce propos #225
