### ISSUE TITLE
Technical Review - Composant Nav dans Page Objet

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#210]
J'aimerai un avis technique et une confirmation de la bonne marche du composant : 
`fragments/Nav.js`  depuis la **Page Objet Actualité** ( seul cette dernière est fiable à ce stade )

Pour rappel ce composant doit : 
Se composer en fonction des section présentes dans la pages Objet ( Article Principal, Fichiers Associes, Productions associées, ... ).

Une page News sans membre en lien n’afficherai donc pas  " Membre en lien"

![image](https://user-images.githubusercontent.com/10298798/53908143-06ab6280-404f-11e9-8157-f133ad21fe0a.png)

A votre disposition si vous avez des questions
Merci !

**Comment by paulgirard** [comment]
L'image n'est pas chargée.
Je suis dessus.

**Comment by BenjmnG** [comment]
Si les images se chargent c'est top !
Si les modules `nav-item` s'affiche en fonction du contexte, c'est top tip top !

**Comment by paulgirard** [comment]
Pour les images j'ai deux problèmes :
- le withPrefix n'ajoute pas le dossier /static/ ?
- poru les images processed il faut qu'on crée un composant pour les générer. J'ai bien vu comment ça marche côté admin mais là étant côté serveur ça change la done. 
J'ajoute une issue sur ce point précis  #213

**Comment by oncletom** [comment]
Dans ea694d5, j'ai ajouté la couverture de l'objet.

Ça donne ça dans le DOM

<img width="960" alt="image" src="https://user-images.githubusercontent.com/138627/54619974-bf1cd180-4a65-11e9-8304-1151ab9a310f.png">

J'ai l'impression qu'il ne manque pas grand chose pour que ça s'affiche.

@BenjmnG, tu as une idée ? Dis-moi ce sur ce quoi je peux encore être utile sur cette tâche.

**Comment by BenjmnG** [comment]
Chapeau !

J'en ai profité pour englober cette image dans le petit module `ProcessedImage `de YomGui afin d'obtenir les balise `Pre `tout autour de chaque ligne.

L'image ne s'affichait pas à cause d'une erreur Typo sur une feuille de style CSS.

Les objectif pour ce composant sont remplis,
Merci à tous
