### ISSUE TITLE
Technical review - Composant Nav ( Rebelotte)

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#211]
Toujours pour le composant `Nav.js`, Il semble que son inclusion 

` <Nav lang={lang} object={activity} related={relatedElements} />`

 à la ligne 108 avant le `<main>` de la page` ActivityDetail.js ` fasse tout capoter 💥 

Je pense pouvoir m'en sortir si je fouille encore plus, mais cela me semble en lien avec l'issue #210
Il me semble que cela est donc pertinent de dévoiler ce problème.

B.

**Comment by paulgirard** [comment]
ok je regarde

**Comment by paulgirard** [comment]
mmm tu as poussé ton test ? 
Je ne vois pas de Nav à la ligne 108 ?

**Comment by BenjmnG** [comment]
Bien évidemment ! J'ai du virer la Nav.
Même placé en commentaire le serveur décroche. C'est ce pourquoi j'ai fais référence à ce composant dans ma demande.

`{/* <Nav lang={lang} object={activity} related={relatedElements} />*/}`

Comme je disais, je me demande si ce plantage n'est pas en liens avec l'issue précédente. En claire je me demande si la `const relatedElements` censé faire l'interface entre la page Objet et le composant `Nav` ne cause pas plus de problèmes que autre choses.

**Comment by paulgirard** [comment]
ok je vois.
Après avoir tenté de faire marcher les images je regarde de ce côté.

**Comment by paulgirard** [comment]
Tu peux tester avec cette version ? Pour moi ça passe.

**Comment by BenjmnG** [comment]
Ok je regarde

**Comment by paulgirard** [comment]
Je vois pas mal d'erreurs dans les sous composants ***Associes.js 
Je vais nettoyer ça.

**Comment by BenjmnG** [comment]
A première vu, cela marche nickel.
Merci !

Ok, pour ces erreurs.
Si cela est rébarbatif, tu peux en faire 1 ( les quatres sont peu ou prou la même choses) et je m'occupe de répercuter la logique sur les trois autres, en comparant avec le versioning de Git.
Up to you !

**Comment by paulgirard** [comment]
Yo j'ai pas mal nettoyé. J'ai aussi branché les données dans activityDetail. 
Il y a peu voir pas de liens activités activités car le module d'écriture manque dans le CMS j'ajoute une issue.
En revanche je ne suis pas fan de ta gestion des accroches.
Ce serait sans doute plus simple de générer l'accroche depuis le composant parent (AcitvityDetail) et de passer la string au composant 'associés' par une nouvelle prop (attribut).
On peut en causer si besoin.

**Comment by paulgirard** [comment]
ps: je te laisse fermer si c'est bon pour toi ?

**Comment by BenjmnG** [comment]
Pas faux pour l'accroche. Je prends ton conseils. 
A y réfléchir, cela permettrai de déterminer l'accroche une fois pour toute pour les 4 composants. 
Je mets cela sur ma Todo.

Merci pour ton oeil !
