### ISSUE TITLE
rendre les filtres de dates dynamiques

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#212]
Les filtres de dates dans les listings sont pour le moment construits avec une liste de d'année fixe.
On peut les rendre dynamique cad qu'ils se contruisent en fonction des données.

- [x] filtre dans news
- [ ] filtre dans activités
- [ ] filtre dans productions

D'ailleurs on devrait peut être rendre le composant générique ?

**Comment by Yomguithereal** [comment]
J'attends la stabilisation du design de ces filtres pour faire de la magie.
