### ISSUE TITLE
composants de rendu des images processed

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#213]
Pour l'intégration, on a besoin de faire un composant qui génère l'image processed à partir des données du modèle.
On a déjà un composant côté admin qui fait ça mais comme il utilise du canvas je ne sais pas trop comment gérer ça pour l'admin. j'ai peur de me perdre dans un tunnel.

Je laisse @Yomguithereal nous faire ça.

Pour le moment le besoin concerne la home et les pages details (fragment nav) :
  https://github.com/medialab/website/blob/master/site/src/components/fragments/Nav.js#L24
une page détails avec une image : http://localhost:8000/news/la-societe-ne-se-laisse-pas

**Comment by paulgirard** [comment]
Au temps pour moi le composants est déjà codé là : https://github.com/medialab/website/blob/master/site/src/components/ProcessedImage.js

Cependant je ne trouve pas dans le modèle où le résultat du processus génératif est stocké ?

**Comment by Yomguithereal** [comment]
`coverImage.processed.{small,medium,large}`

**Comment by Yomguithereal** [comment]
Je pense qu'on peut ferme ça désormais.
