### ISSUE TITLE
cover.file ne contient pas le préfix static

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#214]
withPrefix n'ajoute aucun prefix.
Il n'y a pas de pathPrefix dans gatsby-config.js !

On l'ajoute avec la valeur '/static/' ? 

voir : https://github.com/medialab/website/blob/master/site/src/components/fragments/Nav.js#L23

**Comment by Yomguithereal** [comment]
Il ne devrait pas y avoir besoin de `withPrefix` dans l'inté. Normalement `cover.file` a la bonne url déjà résolue. Si c'est pas le cas c'est que j'ai merdé. Le préfix est passé au build.

**Comment by paulgirard** [comment]
Ok Donc je renomme l'issue.
le cover.file ne contient pas le préfix.

**Comment by Yomguithereal** [comment]
:(

**Comment by Yomguithereal** [comment]
Ok, je crois que je comprends d'où vient la confusion. `cover.file` possède la donnée originale, et non la donnée résolue. Pour accéder à l'url résolue il faut fouiller dans `coverImage`, qui contient l'url dans `coverImage.url` et les strings des versions processed.
