### ISSUE TITLE
À quoi correspond mainProductions pour une personne ?

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#215]
Dans le modèle de données concernant les membres de l'équipe, il y a les données `mainProductions` et `mainActivities`, à quoi renvoient ces données ? Aux highlights de la personne (les 4/5 éléments mis en avant) ou à toutes les productions et activités de la personne ?

Si cela renvoie aux highlights → comment accéder à toutes les activités et à toutes les productions d'une personne?

Si cela renvoie à toutes les activités et productions d'une personnes → comment accéder aux highlight ?

**Comment by paulgirard** [comment]
les mainActivities et mainProductions sont les highlights.

Pour les autres liens normaux ils sont dans les autres objets.
Pour le moment inaccessible depuis le composant.
On va les ajouter.
On te dit quand c'est prêt.

@Yomguithereal je ne sais pas comment on va gérer ces "backlinks" ?
Je t'assigne le ticket du coup ;)

**Comment by Yomguithereal** [comment]
@paulgirard, au cas où, pour ajouter des backlinks, il faut le déclarer ici: https://github.com/medialab/website/blob/master/site/gatsby-node.js#L491-L496

@JulieBlanc:

Les `mainActivities` et `mainProductions` sont choisis par les personnes elles-mêmes et sont en quantité limitées. Ce sont donc bien les "highlights". Concernant les "backlinks", à savoir, par exemples, toutes les productions d'une personne, ceux-ci sont désormais accessibles dans `p.productions`.

Tu as donc désormais:  `p.activities`, `p.news` et `p.productions`. Je ne te passe que des labels pour le moment mais je peux mettre plus. Pour cela j'ai besoin de savoir de quoi tu as besoin en termes de méta-données les concernant.

**Comment by paulgirard** [comment]
On va avoir besoin des meta : 
- name ou title
- type (pour le rendu ?)
- slugs (pour les liens)
- id (pour le key)

Je ne sais pas si l'image sera nécessaire ?

**Comment by BenjmnG** [comment]
Sur les images il y a débats encore.
La question est : est-ce que cela alourdie la composition.
Ajoutons les pour le moment quitte à y revenir plus tard.

De plus Description ou Baseline pourrait être utile.

Enfin, si nous parlons des actualités liées à une personne, le lieu et la date seront indispensable

**Comment by oncletom** [comment]
Est-ce qu'il manque encore quelque chose ?

J'ai l'impression qu'il y a tout.
Sinon, merci de pointer les champs manquants et/ou où ils sont utilisés dans le template.

**Comment by BenjmnG** [comment]
Je clos cette issue car toute les données sont toute pointées à ce stade.
La persistance de cette issue est confusante
