### ISSUE TITLE
Une fonction pour les gouverner toutes -- Nav, Element associes

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#216]
Bonsoir,
Pas de panique tout fonctionne !
Je veux juste partager avec vous un nœud épineux. 

Pour les besoin du composant Nav, nous avons mis en place une const `relatedElement` présent dans chaque page objet. 

**1. relatedElement**
Cette constante se charge de verifier si dans une catégorie il existe des d’élément associés , et si oui fourni un intitulé français / anglais à cette rubrique.

**2.Nav**
Ensuite le composant Nav se charge de composer un petit menu sur base de ces éléments existants.

**3.Element Associés**
- Dans le même temps, et suivant une logique indépendante. Chaque composant `X-associées.js` se charge de verifier si il existe des éléments dans sa catégorie. Si oui il les affiche.
- De plus il va, par facilité, chercher l'intitulé de la catégorie, directement traduit dans la constante `relatedElement`
- A ce stade, cet intitulé est invariable que l'on parle d'un objet ou d'une personne. Il faudra affiner ce point.

Cela fonctionne, mais je me demande si il n'y a pas plus simple. 

- Notamment concaténer les étape 1 et 3 ?
- Importer une constante `relatedElement `generaliste au lieu de la déclarer à chaque page ?
- Etablir en amont les intitulés destinés à la Nav ( ex : Activités Associés ) et ceux destinées à `X-associées.js` (Dominique Cardon est impliqué dans ces activités / Cette activité est liée à plusieurs productions )

**Comment by Yomguithereal** [comment]
Je ne suis pas certain de tout comprendre. Mais si tu me pointe les fichiers concernés et les endroits de l'interface affectés, je peux regarder ça jeudi et tenter de simplifier.

**Comment by BenjmnG** [comment]
Ce serait super !

Tu peux partir de la page NewsDetail.js comme de toute les autres page
Detail.js.
Repère la Const RelatedElement et suis le fil jusqu'a n'importe quel
composant X-associes.js
Dans le même temps suis le chemin jusqu'à l'élement Nav.js

Nav et X-associes.js sont visible sur les pages objets. Tu peux te
concentré sur une Actualité par exemple.

A dispo si je peux aider,

B.


Le mar. 12 mars 2019 à 17:11, Guillaume Plique <notifications@github.com> a
écrit :

**Comment by paulgirard** [comment]
Si je comprends bien ton relatedElements sert à deux choses : 
- tester si tel éléments associés est peuplé pour cet objet
- définir les titres des blocs des éléments associés.

Ce que je ferai c'est plus simplement : 
- Le component Nav pourrait se construire tout seul à partir de l'objet seul. Il ajoute les blocs si les variables qui contiennent les éléments associés de l'objet sont non vides.
- Pour Les associés, tu passes déjà la variable concernées uniquement 
- pour les titres des blocs je mettrais en dur dans les composants nav et associés. Si on veut que ce soit les mêmes titres, il faut juste écrie la même choses dans les codes.

ps: tu as un seul composant nav mais des components associés séparé par modèle. On pourrait faire un component associé global aussi qui ferait tous les blocs associés d'un coup comme le Nav le fait.

**Comment by BenjmnG** [comment]
Oui, tu as bien compris le fonctionnement de *relatedElement*.
Oui un component associées global ferait tout aussi bien l'affaire. Il y a
beaucoup de redite entre ces multiples *components *associées.

@Yomguithereal, c'est exactement ces composants qui poseront soucis lors de
mon envoi de demain midi.

Bonne soirée,

B.

Le mer. 13 mars 2019 à 16:14, Paul Girard <notifications@github.com> a
écrit :

**Comment by paulgirard** [comment]
Ok je vois bien ce qu'il faut faire. Suis en atelier demain mais dispo par
IRC pour éclaircir si besoin.

**Comment by Yomguithereal** [comment]
Pour l'instant les pages d'éléments associées ne bénéficieraient pas tellement d'une abstraction. Je pense qu'on peut les garder comme ça et ça marche. Il sera toujours temps d'abstraire plus tard.

**Comment by Yomguithereal** [comment]
Ce qu'il faudra faire, cependant, c'est d'abstraire les arrays mal foutus de `relatedElements` pour éviter de se répéter pour rien à chaque fois.

**Comment by oncletom** [comment]
J'ai l'impression que c'est déjà pas mal comme ça, et que ça vaudra le coup de s'énerver à le nettoyer après. L'impact est faible sur la base de code et passer du temps dessus n'a pas d'impact sur ce que voit les utilisateurices du site.

Correct ?

**Comment by BenjmnG** [comment]
Apparemment vous êtes tous sur un consensus.
Je clos cette issue pour le moment.
