### ISSUE TITLE
Page Personne : dynamiser les highlight

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#217]
Bonjour @AmelieVRL , @Yomguithereal 

J'ai donc envoyé dans l'espace les dernières modifications quant aux pages objets et personnes.

- Le CSS demandera à être fignolé,
- La pertinence de chaque module à être critiqué,
- Le _responsive_ à être maitrisé.

Mais cela fonctionnera pour le moment.

@Yomguithereal  pourrais-tu zieuter du coté des éléments associées ? D'une part car ces éléments ne sont pas totalement dynamiques et surtout car notre conversation #216 tend à envisager une "légère" restructuration de ces composants en un seul.

Bon appétit,
B.

Ps : Il existe plusieurs composant `Highlight `sur la page personne. Ce sont des versions de travail. Peut-être pourrions nous garder uniquement `Highlight2 `dans la version du site qui accompagnera les membres du Medialab durant le remplissage de leurs Biographie. Histoire de ne pas être confusant.

**Comment by Yomguithereal** [comment]
Je commence les travaux.

**Comment by BenjmnG** [comment]
Excellent, je reste pas loin si besoin

**Comment by Yomguithereal** [comment]
Bon je viens de finir une passe de dynamisation etc. sur la codebase du site. N'oubliez pas de pull et de faire tourner un petit `npm run reinstall` pour bénéficier de la mise à jour des dépendances. Je laisse la main jusque lundi.

**Comment by BenjmnG** [comment]
J'ai vu tout tes changement, petits et gros.
Merci !

**Comment by paulgirard** [comment]
Je dynamise les highlights

**Comment by paulgirard** [comment]
@BenjmnG j'ai terminé avec les hightlights.
J'ai utilisé la version 3 et renommer en highlights car j'ai rassemblé les deux types de highlights.
Faut que tu vérifies l'inté j'ai un peu interprété... 
Si ok pour toi, vire les highlight et highlitgh2 STP.

**Comment by paulgirard** [comment]
ps je te laisse fermer l'issue quand c'est bon pour toi.

**Comment by BenjmnG** [comment]
Top, je prends la main et m'occupe de cloturer le cas échéant

Le jeu. 21 mars 2019 à 17:45, Paul Girard <notifications@github.com> a
écrit :

**Comment by BenjmnG** [comment]
Merci @paulgirard ,
C'est Parfait, maintenant c'est une histoire de CSS
