### ISSUE TITLE
Optimize images when building

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#218]

**Comment by BenjmnG** [comment]
@Yomguithereal Je te confirme que nous avons bien besoin des 3 Résolutions d'images. 
La compilation n'en sera qu'aussi longue.
Sorry...

**Comment by Yomguithereal** [comment]
Oui on avait bien confirmé qu'il faut les 3. Mais j'ai accéléré le build depuis. Cepedant cette issue concerne autre chose: l'optimisation des images pour minimiser leur taille et qu'elles soient plus légère si besoin.

**Comment by BenjmnG** [comment]
Très bien

Le jeu. 4 juil. 2019 à 12:16, Guillaume Plique <notifications@github.com> a
écrit :
