### ISSUE TITLE
Intégration et images processed

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#220]
Donc @BenjmnG, concernant les images processed, je remarque deux choses:

1) La fonte 'Bel' ne marche pas correctement sur Chrome (notamment sur macOs). Les caractères n'ont pas la même taille.

2) J'ai l'impression que le scaling n'est pas correct. On ne voit pas l'intégralité de l'image mais seulement son coin haut gauche il me semble.

**Comment by BenjmnG** [comment]
Bien reçus

**Comment by BenjmnG** [comment]
Les déclinaisons du BEL en woff et woff2 étaient foireuse. Autant pour moi. 
Le script qui les a converties dans ces formats web a préféré supprimer les caractère non latin afin d'alléger le fichier en sortie... Résultat une font vide.
Chose est désormais corrigée

J'ai modifié la hauteur des caractères dans le fichier font.
Le résultat est meilleur chez moi ( Chrome et Firefox )
Et toi ?

Yep le _scaling_ est foireux. 
Je peux ajuster les images en prenant le centre comme référent. 
Pour un ajustement parfait en fonction des écrans et des emplacements, je mets cela en attentes jusqu'au moment ou nous reprendrais la Home.

**Comment by paulgirard** [comment]
@BenjmnG tu as clos cette issue par erreur non ?

**Comment by BenjmnG** [comment]
Autant pour moi

**Comment by BenjmnG** [comment]
Effectivement le scaling est ouvertement foireux

![image](https://user-images.githubusercontent.com/10298798/54815857-2c617a00-4c93-11e9-99d3-e2a381e8c90f.png)

@Yomguithereal Je devine que c'est une chose à changer dans le script JS qui "convertit" l'image Jpeg en Texte.
Auquel cas il nous faut un ratio exacte Hauteur x Largeur des glyphes BEL.
Niet ?

**Comment by Yomguithereal** [comment]
Oui. Il me faut la taille en pixels width et height pour avoir un ratio correct. Je remarque cependant que la fonte Bel doit être un peu différente de la Courier New parce que la Courier New passe plutot bien côté CMS (essaye le playground dans le cms ou edite une page news etc. tu vas voir que les ratio marchent plutot bien).

Après c'est pas impossible que ce soit un pb de CSS?

**Comment by BenjmnG** [comment]
Exact, 

Je vérifie les différences de tracés entre les deux fonts. Et il n'y en a aucune.
Je cherche de mon coté dans les paramètre d'export de la fonte et dans le CSS.
On va essayer de rester sur les paramètre de la Courrier News qui fonctionne bien

**Comment by BenjmnG** [comment]
@Yomguithereal  je fais joujou avec le petit outils Image Playground sur le CMS.
Sur une échelle allant de _1_ à _"tu fais caguer"_ : 
Est-il facile d'ajouter un paramètre _extra-large_ équivalent à 250 glyphes par ligne ?


![image](https://user-images.githubusercontent.com/10298798/55028924-31168d00-5009-11e9-8475-9a1ba9bb5e50.png)


Et ce pour prendre de cours la remarque prochaine sur "On ne reconnait pas le motif des images"

**Comment by Yomguithereal** [comment]
Ben le soucis là en l'occurrence c'est que je ne sais pas quel résultat ça peut avoir vu qu'on a calibré le gamma pour `200`. Après, le cas échéant tu ne voudrait pas remplacer la dimension large par celle-ci plutôt que d'en ajouter une?

**Comment by BenjmnG** [comment]
On peut remplacer Large par le paramètre _250_
Rappelle toi, tu me la dis de tes mots. Le gamma n’interfére pas avec le nombre de glyphe.
Si il est bien réglé, il fonctionnera avec toute les valeurs.

Je précise que j'envisage cela dans une démarche expérimentale

**Comment by Yomguithereal** [comment]
> Rappelle toi, tu me la dis de tes mots. Le gamma n’interfere pas avec le nombre de glyphe.

Oui mais on a surtout essayé le downscaling, pas le upscaling. Mais ça veut pas dire qu'on peut pas essayer.

Si tu veux essayer des trucs de ton côté, tu peux aller dans `site/schema.js` ligne 282 et changer le nombre.

**Comment by Yomguithereal** [comment]
Faudra relancer `npm run dev` pour essayer à chaque fois que tu changes ce nombre though.

**Comment by BenjmnG** [comment]
Excellent ! Merci, je le tente d'abord en local avant de tous vous enquiquiner.

**Comment by paulgirard** [comment]
@Yomguithereal @BenjmnG quel est le statut ?

**Comment by Yomguithereal** [comment]
Pas de nouvelles de mon côté. @BenjmnG tu avais essayé le `250`?

**Comment by BenjmnG** [comment]
Le 250 est désormais un 240. Cela afin de satisfaire la logique suivante (
60, 120, 240 ).

Les images passent.
La font fonctionne sur la plupart des navigateurs,
Nous maitrisons désormais le facteur d'étirement.
Le degrés de détails qu'apportent les images nous satisfait.

Bref, nous maitrisons le processus,
Je vous propose de clore.




Le lun. 13 mai 2019 à 18:57, Guillaume Plique <notifications@github.com> a
écrit :
