### ISSUE TITLE
Bug complement listes associées

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#221]
L'effet hover sur les éléments des listes associées ne fonctionne que sur Firefox mais pas sur Chrome.

**Comment by BenjmnG** [comment]
En cours

**Comment by BenjmnG** [comment]
J'ai fait une correction.
Je suis preneur de vos retours. 
Toujours un bug sur Chrome ?

**Comment by Yomguithereal** [comment]
Ca a l'air de marcher sur chrome maintenant.
