### ISSUE TITLE
La raison du FOUC

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#222]
Après moult investigation j'ai trouvé la source du **F**lash **o**f **U**nstyled **C**ontent (FOUC). Il est du au fait que la classe du body est mise à jour par `Helmet` dans le `Layout` de manière debounced. Cela veut dire que le contenu de la page est mis à jour avant, puis cette classe. Or cette classe est visiblement nécessaire pour rendre le contenu de la bonne manière. Il faudrait donc trouver un moyen de shunter le debouncing ou apposer ces classes autre part que sur `body`. Mais voyons ça plus tard.

**Comment by Yomguithereal** [comment]
@BenjmnG, est-ce qu'il serait compliqué pour vous d'utiliser un élement wrapper plutôt que le body pour avoir vos classes comme `page-people` par exemple? Genre, si dans le `Layout`, à la place de:

```jsx
<TopBar lang={lang} permalinks={permalinks} />
{children}
<Footer />
```

on avait plutôt:

```jsx
<div className="page-people">
  <TopBar lang={lang} permalinks={permalinks} />
  {children}
  <Footer />
</div>
```

ça le ferait? Parce que là, le fait que la mise à jour de la classe du body et du contenu de la page soit désynchronisées fout le dawa et provoque l'espèce de flash de contenu sans style bizarre qu'on observe au changement de page.

**Comment by BenjmnG** [comment]
Nope !
Zéro difficultés.
Il faut juste une balise qui englobe Topbar, footer et le contenut.

Garde les noms des ID proposés et je me chargerai de modifier le CSS demain
après midi

Le lun. 18 mars 2019 15:51, Guillaume Plique <notifications@github.com> a
écrit :

**Comment by BenjmnG** [comment]
Perfecto !
