### ISSUE TITLE
activité sans date ?

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#225]
Certaines production n'ont pas de date.
Ce champs devrait être indispensable.

- [x] comprendre pourquoi il n'y a des prod sans date
- [x] corriger ces données manquantes
~rendre ce champs obligatoire dans le schéma~

**Comment by robindemourat** [comment]
Même bug avec activités sans dates apparemment :

* aller à `/how-not-to-be-a-bad` (activité "how not to be a bad trader")
* résultat :

<img width="1280" alt="Capture d’écran 2019-05-14 à 10 39 25" src="https://user-images.githubusercontent.com/1876890/57683772-ae877280-7634-11e9-8ac6-2c598ada6f80.png">
