### ISSUE TITLE
Activer le filtre correct des news de la home

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#227]
l'agenda de l'a home devrait ne présenter que les 7 prochains événements.
On veut ne mettre que les événements qui ont une date de début ou une date de fin >= à hier.

**Comment by Yomguithereal** [comment]
Je ferai peut-être ça en bout de course parce que sinon je sens que ça va être pénible pour tester l'intégration, non?

**Comment by paulgirard** [comment]
Bien vu.
Autre solution : on crafte la bonne requête mais que on triche sur la définition de aujourd'hui dans cette requête ?

**Comment by Yomguithereal** [comment]
Tricher c'est tricher.

**Comment by Yomguithereal** [comment]
C'est bon. J'ai mis une vieille date en dur. Il suffira de changer ça au passage en prod. Du coup je vais renommer l'issue.
