### ISSUE TITLE
NEWS : Add filters by type on the left

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#230]

**Comment by Yomguithereal** [comment]
@BenjmnG j'ai des problèmes de CSS pour ajouter ça. Ya moyen que tu mettes des placeholders steupl?

**Comment by BenjmnG** [comment]
Tu veux dire une des Règles CSS pour afficher ce filtre car pour le moment ces checkbox s'affichent dans les choux?
@JulieBlanc ,tu es sur la page filtre cette après-midi ?
Si quenini je m'en occupe.

**Comment by JulieBlanc** [comment]
Il y a des filtres par types pour les news ? Dans le document "page-listing.md", il est noté qu'il n'y a pas d'autres tri possible. Quels sont les tris ?

**Comment by Yomguithereal** [comment]
Je pense qu'on parle bien de filtrer par type. Et après il y a les années mais c'est déjà fait.

**Comment by BenjmnG** [comment]
Selon le shéma et si je comprend bien il y a les types :

        "event",
        "post",
        "notice"

Quand aux sous-types j'ai listé : 

- Atelier 
- rencontre 
- Séminaire de recherche 
- Emploi
- Appel à candidature 
- Stage 
- Intervention

Je ne suis pas certain que cette liste soit exaustive
Est-ce un champ ouvert ?

**Comment by Yomguithereal** [comment]
Ce que tu appelles le sous-type (appelé "label" dans le modèle je crois) est un champ ouvert mais suggéré oui. Cependant on n'a pas besoin de filtrer dessus.

**Comment by JulieBlanc** [comment]
Je suis en train d'ajouter les filtres pour la liste de news. Il semblerait qu'il n'y ait pas de précisions pour l'anglais et le français pour les "types". Peux-tu les ajouter au modèle de donnée @Yomguithereal ?

**Comment by Yomguithereal** [comment]
J'ai ajouté le champ `typeLabel` avec le fr et l'en. C'est ça qu'il te fallait?
