### ISSUE TITLE
Drop useless items in graphql queries such as ids

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#236]

**Comment by paulgirard** [comment]
Ça m'est arrivé d'ajouter des ids pour rempli le champ key de react.
Si tu vires fais attention ça peut être utilisé.

**Comment by Yomguithereal** [comment]
J'ai déjà enlevé de lard. Idéalement faudrait refaire une passe à la fin pour s'assurer qu'il n'y a pas de données chargées inutilement.
