### ISSUE TITLE
Page Liste : Bug Filtre par année

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#237]
Je suis sur les filtres, je souhaite "Aller à l'année" 2010 et ainsi voir la liste des Productions de cette années. Le trie s'effectue bien, mais l'année 2019 reste persistante dans le filtre

![image](https://user-images.githubusercontent.com/10298798/54750321-90bf0380-4bd7-11e9-8861-0428c18f6da2.png)

**Comment by paulgirard** [comment]
Fermé par erreur ?

**Comment by JulieBlanc** [comment]
Le seul moyen de changer cela est par javascript, c'était laissé pour la fin: les amélioration de l'expérience par des petits scripts javascript

**Comment by BenjmnG** [comment]
Nous avons enlevé la mention "pseudo-dynamique" de l'année.
Il est désormais inutile d'utiliser une solution JS sauf si vous souhaitez rouvrir cette issue

![image](https://user-images.githubusercontent.com/10298798/59683733-0176bb80-91d9-11e9-8168-72e4f92c2ed8.png)
