### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#241]
Impossible pour moi de compiler après les derniers pull, l'erreur semblerait provenir du template/index.js

Je ne sais pas corriger cette erreur.

![Capture d’écran 2019-03-25 à 17 30 42](https://user-images.githubusercontent.com/25477334/54936893-bcb5ee00-4f23-11e9-884f-d233293c77fd.png)

**Comment by Yomguithereal** [comment]
Peux-tu faire un `npm run reinstall` à la racine du projet puis un `npm run clean` et réessayer?

**Comment by JulieBlanc** [comment]
Ça marche, je ferme l'issue
