### ISSUE TITLE
Agenda : filtrer les actualités de type annonce

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#242]
Il y a du mieux !
Maintenant l'agenda recense les dernières news.
Toutefois je ne trouve pas très heureux que les offres d'emplois soit listée comme rendez-vous.
Vos avis ?

Ps : Cela étant dis, et si il y a un enjeux sur le recrutement, nous pourrions envisager un module (discret mais immanquable) sur la page d'accueil si un recrutement est en cours. Juste une hypothèse pour le futur de demain.

**Comment by paulgirard** [comment]
Les annonces de postes sont des actualités de type "annonce".
Dans cette catégorie on a aussi des sorties de livre...
La colonne rendz-vous est censée n'afficher que des événement de type 'rendez-vous' et donc pas les annonces de postes.
Les actualités d'autres types anonce ou chronique iront dans le carrousel ou A la une si on le souhaite mettre en Une.

C'est donc bien un bug de filtrage.
On fera le changement sur la nouvelle home.
