### ISSUE TITLE
Activités actives ?

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#243]
J'ai travaillé sur les filtres en CSS pour la page activités. Je veux simplement savoir s'il y a ou non dans les activités des activités qui sont actives. Dans l'affichage je n'ai que des activités passées mais je voulais savoir si cela provient des données ou si c'est une erreur dans le template react.

C'est à vérifier à la ligne 33 du fichier `ActivityListing.js`:  `{a.active ? 'active' : 'past'}`est-il correct ?

**Comment by oncletom** [comment]
En regardant le schéma, on dirait qu'oui, à première vue : 

https://github.com/medialab/website/blob/860ccec579d65bdf2f88c2650128ea0d5334df1a/specs/schemas/activities.json#L171-L174
