### ISSUE TITLE
Signifier si l'activité/le people est active dans les pages ActivityDetail.js et PeopleDetail.js

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#244]

**Comment by Yomguithereal** [comment]
Il me semble que c'est bon pour les people mais pas les activités, non?

**Comment by AmelieVRL** [comment]
Exactement.
Mais il faudrait qu'on parvienne a rendre ça plus visible (j'en ai marre des guss qui m'écrivent pour contacter Gemenne).
J'ajoute @robindemourat pour qu'on y réfléchisse ensemble.

**Comment by robindemourat** [comment]
@AmelieVRL on pourrait p-ereprendre ce qu'on a fait sur la page des tools pour médialab/pas médialab ? -->

![Capture d’écran 2020-03-19 à 12 00 05](https://user-images.githubusercontent.com/1876890/77060653-336fb500-69d9-11ea-9726-82297a969701.png)

**Comment by AmelieVRL** [comment]
oui, ce serait pas mal.
On peux tester ça dans un premier temps te voir si ça fonctionne.

**Comment by robindemourat** [comment]
Fait, à passer en revue ensemble quand tu le souhaites.

**Comment by Yomguithereal** [comment]
@robindemourat note que tu peux passer des trucs en pprd en faisant npm run upgrade:pprd, après il faut attendre ~1h au max et ce sera en pprd si tu veux montrer des trucs par ce truchement.

**Comment by robindemourat** [comment]
@Yomguithereal super merci je ne savais pas je viens de le faire.

@AmelieVRL du coup tu devrais pouvoir regarder le résultat actuel sur la PPRD d'ici 1h.

**Comment by AmelieVRL** [comment]
ok, je regarde donc dans 40 minutes...


Le jeu. 19 mars 2020 à 13:54, Robin de Mourat <notifications@github.com> a
écrit :

**Comment by Yomguithereal** [comment]
J'ai l'impression qu'on peut clore cette issue. @AmelieVRL je te laisse la ré-ouvrir si j'ai loupé quelque chose.
