### ISSUE TITLE
titres dans le texte pages objets

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#246]
Pour les titres à l'intérieur des textes des pages objets, ajouter des class en fonction du nombre de niveaux de titre sur la page. (Attention, ce ne sont pas les mêmes class en fonction du nombre de niveaux)

Si il n'y a qu'un seul niveaux de titre:
```
<h3 class="title-style-level-2"><h3>
```

Si deux niveaux de titre:
```
<h3 class="title-style-level-1"><h3>
<h4 class="title-style-level-2"><h4>
```

Si trois niveaux de titre:
```
<h3 class="title-style-level-1"><h3>
<h4 class="title-style-level-2"><h4>
<h5 class="title-style-level-3"><h5>
```

**Comment by BenjmnG** [comment]
J'ai une suggestion :
Est-ce que, suivant ce même principe, l'utilisation des attributs
data-level="1" comme dans d'autres composants ne serait pas une solution
d'autant plus élégante ?

**Comment by JulieBlanc** [comment]
Oui, je vais changer. Mais il faut que cela soit `data-style-level`.
Ce qui donnerait: 

Si il n'y a qu'un seul niveaux de titre:

<h3 data-style-level="2"><h3>

Si deux niveaux de titre:

<h3 data-style-level="1"><h3>
<h4 data-style-level="2"><h4>

Si trois niveaux de titre:

<h3 data-style-level="1"><h3>
<h4 data-style-level="2"><h4>
<h5 data-style-level="3"><h5>

**Comment by Yomguithereal** [comment]
Ca devrait être bon. Je vous laisse fermer l'issue une fois vérifié que cela marche.

**Comment by JulieBlanc** [comment]
ça ne semble pas marcher.
Si je prend l'actu Algoglitch par exemple (`/news/algoglitch-dans-la-revue-techniquesandculture`), il y a qu'un seul niveau de titre, donc le h3 devrait correspondre à `<h3 data-style-level="2"><h3> `or il est indiqué `data-style-level="1"`

![Capture d’écran 2019-05-05 à 15 49 43](https://user-images.githubusercontent.com/25477334/57195023-e532fe00-6f4d-11e9-8276-eaa5a4fd8168.png)

**Comment by Yomguithereal** [comment]
Je viens de corriger ça. Je te laisse fermer l'issue quand tu confirmes.

**Comment by Yomguithereal** [comment]
@JulieBlanc ça marche maintenant?

**Comment by AmelieVRL** [comment]
Salut @JulieBlanc ,
nous sommes en train de nettoyer les issues : peux tu nous dire si celle-ci est traitée selon toi (et la clore le cas échéant)?
Merci!
