### ISSUE TITLE
filtrage équipe : montrer que les anciens ? 

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#249]
Contrainte CSS, on doit garder un checkbox toujours actif pour que le système actuel marche.
Julie propose de garder actif toujours coché.
On ne peut donc pas voir que les "anciens" mais de permettre de voir les anciens en plus.

soit on passe en Javascript soit on passe au filtrage passif/actif en précompilation (une page par chaque filtre).

**Comment by paulgirard** [comment]
On choisit l'option Contrainte CSS mais dans ce cas on cache le filtre actif et on renomme le filtre passé en : "voir les anciens membres" ou autre expression mieux que ça

**Comment by paulgirard** [comment]
@AmelieVRL on peut fermer ça la solution actuelle convient n'est ce pas ?

**Comment by AmelieVRL** [comment]
OK pour moi!
