### ISSUE TITLE
Quelle langue pour documenter ?

### ISSUE THREAD

**Issue by oncletom** [medialab/website#25]
En voyant les issues et les labels en français puis le README en anglais, je me demandais 

- dans quels cas on utilisait l'un ou l'autre ?
- par extension, dans quelle langue est attendue la documentation projet ?

**Comment by Yomguithereal** [comment]
En règle générale on documente nos projets open source en anglais mais vu que ce projet n’a pas vraiment vocation a etre reutilisé par des tiers le français est possible.

**Comment by paulgirard** [comment]
Je me suis posé la question. J''ai opté pour le français pour le issues pour limiter la difficulté d'écriture et de lecture alors même que ce projet n'a aps vocation à être repris dons pas besoin de la langue anglaise.
