### ISSUE TITLE
Passer les données dans la page Archive

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#257]
Bonjour à tous,
 
Sauf erreur de ma part, la page Archive n'existait pas.
Je l'ai donc créé. 
Pourriez vous passer la tuyauterie Json jusqu'a cette page ?
Mes premières tentatives sont trop crade pour être concluante.

Jusqu'ici nous avons besoin des données Activities, News, Production.

Merci !

**Comment by Yomguithereal** [comment]
Je viens d'ajouter la tuyauterie. Tu n'as que des titres et des permaliens mais je suis certain que tu sauras ajouter les éléments manquants si besoin. Au pire, reping moi.

**Comment by BenjmnG** [comment]
Excellent ! Merci beaucoup,
Je pense pouvoir m'en dépatouiller à partir de là.

Le ven. 5 avr. 2019 à 16:02, Guillaume Plique <notifications@github.com> a
écrit :
