### ISSUE TITLE
remontée des publis spire

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#263]
Bon retour de vacances @paulgirard !
Lors de l'atelier de ce mardi, nous avons remarqué que les publi de Christophe ne remontaient pas sur sa page, alors qu'elles apparaissent bien dans Spire.
Je ne sais pas si ça vient d'un problème depuis Spire ou si le problème vient de l'identification de l'auteur (par rapport à notre liste de people) -> ce serait pour toi ça @Yomguithereal , non?

**Comment by Yomguithereal** [comment]
Probablement un problème d'association depuis la liste des auteurs de spire oui.

**Comment by paulgirard** [comment]
C'est possible que Christophe ne soit plus membre du médialab pour SPIRE.
Il faut que j'enquête je ele ferai en traitant #248 et #265

**Comment by paulgirard** [comment]
Dorénévanant le scritp d'import de spire tente de retrouver les auterus manquants et renvois la liste de ceux qu'on n'a pas pu résoudre à l'utilisateur.rice
