### ISSUE TITLE
temps de chargement de la page actualités

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#266]
la page qui liste des actualités est longue à charger à cause des nombreux éléments et de leurs images.

Discussion à mener pour trouver une solution.

**Comment by paulgirard** [comment]
On a décidé de ne pas respecter la règle du no javascript : 
- pas de javascript pas d'image
- javascript => lazy load

**Comment by JulieBlanc** [comment]
J'ai regardé d'un peu plus près les performances de chargement de la page, 90% du temps de chargement provient du script ProcessedImage. 
C'est un script qui s'exécute côté React et que l'utilisateur final ne devrait pas avoir une fois le site statique déployé.
Du coup, il n'y aurait pas besoin du lazyload. 
@paulgirard comment on peut faire la vérification ?

**Comment by paulgirard** [comment]
Très bien ce test. Nous allons testé avec un vrai déploiement de prod.
Je mets la carte en "Question" mais on écarte ce besoin pour le moment.
Je m'occupe de vérifier cela.
