### ISSUE TITLE
Un espace fine insécable avant tout les ? et ! en langue française

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#267]
@Yomguithereal tu pense que cela est possible ? 
Pour les éléments de titrailles prioritairement.

Tak!

**Comment by Yomguithereal** [comment]
Toujours d'actualité?

**Comment by BenjmnG** [comment]
Lors du dernier atelier nous parlions d'une Regex pour améliorer ce point
typo. Je ne crois pas que cela fut fait.

Le jeu. 27 juin 2019 15:49, Guillaume Plique <notifications@github.com> a
écrit :

**Comment by paulgirard** [comment]
J'ai une regexp de Donato dans mes emails à ajouter un jour. Toujours d'actualités oui.

**Comment by Yomguithereal** [comment]
Ok. Je vais faire ça dans gatsby-node en affectant toute la titraille. Le seul pb c’est le name des activités qui n’est pas traduit. Est ce que c’est grave si on a la meme chose pour l’anglais?

**Comment by paulgirard** [comment]
Je dirais que le name des activités ne devrait pas être affecté. Au porteur du projet de gérer ça si il le souhaite sachant que ça ne va pas être courant comme cas.
Je te transfers l'email de Donato du coup.

**Comment by Yomguithereal** [comment]
Je viens de commiter un truc à ce sujet. Je change pour le moment le titre des news et le titre des productions. Je n'ai fait que l'espace insécable. Le reste des indications de Donato me semble overkill vu les chaînes qu'on a mais j'attends de voir. Dites moi si ça fait le taf et quels autres titres changer.
