### ISSUE TITLE
Les images qui sont vides - à gauche - dans les listings 

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#268]
dans les pages listing activités et actualités, si une image n'a pas de pixel en colonne de gauche, l'extrait utilisé comme référence visuelle dans al liste est vide (tout blanc).
C'est pas glop.
Il faut réfléchir à une solution (on décale si vide, on prend le centre ?)

**Comment by AmelieVRL** [comment]
#278 m'a tuer
