### ISSUE TITLE
Ordonnancement des activités sur la page listing

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#269]
- [x]  créer un settings général pinnedActivities qui est une liste ordonnée d'id d'activités
- [ ] virer le champs important du modèle activity
- [x] ajouter les données pinnedActivities dans le payload du composant listing Activities
- [x] changer l'ordre des activités du listing en commençant par les pinnedActivities puis par actif/passé puis par date de début par ordre décroissant

**Comment by Yomguithereal** [comment]
Le champ `important` qui servait à cela avant qu'on ne le déprécie existe encore dans le schéma et dans les données. Est-ce que je réintroduit son existence dans le CMS? Quel est le statut de cela?

**Comment by AmelieVRL** [comment]
The thing is.... que si c'est directement visible dans la page de l'activité, c'est un peu "dégradant" pour les activités qui ne sont pas importante.
J'aurais vu ça un peu caché dans les settings.

**Comment by Yomguithereal** [comment]
Il s'appelle `important` dans le schéma mais ça veut pas dire qu'on a besoin de l'appeler comme ça ou même lui donner un nom dans le site.

**Comment by Yomguithereal** [comment]
Genre dans le CMS ça peut être appelé 'pinned' ou 'mis en avant' ou whatever.

**Comment by AmelieVRL** [comment]
Oui ce serait mieux... mais les avoir centralisés, c'est bien aussi.
Tu crois que dans les settings on pourrait voir -et seulement voir- ceux qui qu'ont a pingés

**Comment by paulgirard** [comment]
C'est en effet faisable de les traiter comme les sélections de la home.
Ça permettrait de choisir l'ordre exact parmi ceux qui ont été choisis.

Donc la nouvelle proposition pour cette feature est : 
- [ ]  créer un settings général pinnedActivities qui est une liste ordonnée d'id d'activités
- [ ] virer le champs important du modèle activity
- [ ] ajouter les données pinnedActivities dans le payload du composant listing Activities
- [ ] changer l'ordre des activités du listing en commençant par les pinnedActivities puis par ???

@AmelieVRL c'est quoi le critère d'ordre des activités pour celles qui ne sont pas  "pinned" ?

**Comment by BenjmnG** [comment]
En ce cas, je vous laisse injecter les "pinned activities" dans le template.
Le template à cet endroit étant une succession de `<li>`, aucune intervention CSS ne me semble nécéssaire.
