### ISSUE TITLE
Materialisation/visibilité des liens

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#271]
Les liens hypertextes ne sont pas matérialisés.
On ne les devine qu'au survol avec l'apparition du "doigt" à la place de la "souris" 
-> Et oui, j'ai l'impression d’avoir 80ans quand j’écris ça ;)

Un exemple ici:
<img width="1440" alt="lien non visible" src="https://user-images.githubusercontent.com/37452370/56897462-e9af7080-6a8e-11e9-8d55-afd0b9e7296f.png">

**Comment by JulieBlanc** [comment]
Fixed by 3eb488cb3ed62963c770b27461bd227043787d8e
