### ISSUE TITLE
Depassement du texte descriptif d'activité au survol

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#272]
Lors du survol des activités dans une page people, il arrive que le texte soit plus long que ne le permet la zone (le pb se retrouve certainement dans toutes les pages qui utilise cette structuration).
Actuellement, le texte est coupé à mi hauteur de la ligne : ce serait peut être mieux de prévoir des "..." sur la ligne d'avant.

En image:
<img width="1440" alt="descriptif activite - D Cardon" src="https://user-images.githubusercontent.com/37452370/56898338-182e4b00-6a91-11e9-824f-bebac47b7f48.png">

**Comment by paulgirard** [comment]
Proposition : la hauteur des boxs s'ajuste à la taille des contenus.

**Comment by paulgirard** [comment]
#275 m'a tuer
