### ISSUE TITLE
Hauteur des sauts de fin de section

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#273]
Il me semble que la hauteur du padding aprés la zone éditorialisée et aprés la zone des choses "en lien" est très (trop?) important : 
<img width="1440" alt="hauteur apres zone ediorialisee" src="https://user-images.githubusercontent.com/37452370/56902139-ebcafc80-6a99-11e9-9cd7-f9d73f5fe701.png">
<img width="1440" alt="hauteur apres zone en lien" src="https://user-images.githubusercontent.com/37452370/56902142-ecfc2980-6a99-11e9-8818-058c2ce6d453.png">

**Comment by JulieBlanc** [comment]
Fixed
