### ISSUE TITLE
Style des listes

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#274]
Les puces des listes sont rendues chez moi par des étoiles dans des carrés : 
<img width="618" alt="puces des listes" src="https://user-images.githubusercontent.com/37452370/56903271-39486900-6a9c-11e9-953b-c56a37da1b31.png">

Je suis assez réservée sur ce style, il faudrait peut-être faire des essais avec de nouvelles puces.
Aussi, ce serait bien de regarder à diminuer l'interligne pour l'interligne pour que les listes de publi/ouvrages dans les pages people soient moins hautes.

Merci

**Comment by BenjmnG** [comment]
Certes.. C'est une petite fantaisie..
Quelque chose de plus sobre ?

**Comment by AmelieVRL** [comment]
Ce serait mieux oui.

**Comment by paulgirard** [comment]
Amélie je te laisse clore si ça te va.
