### ISSUE TITLE
Page objet - ordonnancement des contenus en lien

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#276]
Actuellement, l'ordre des contenus en lien est le suivant :
Productions en lien
Activités en lien
Actualités en lien

La liste des production pouvant être trés trés trés longue, il faudrait inverser "Productions en lien" et "Activités en lien" pour faire remonter les activités au dessus des productions.
L'ordre des contenus en lien sera donc le suivant :
Activités en lien
Productions en lien
Actualités en lien

Merci!

**Comment by BenjmnG** [comment]
D'accord !
Sur la Todo

**Comment by JulieBlanc** [comment]
Fixed by 3ebe4a66be1b309b6af54e53df6bf4d2e7f22208
