### ISSUE TITLE
Productions extérieures

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#277]
pour distinguer les productions faites par nos membres avant qu'ils soient membre, nous proposons d'ajouter un champs boolean à ces productions.
champs 'hors médialab'

Ce champs aurait pour conséquence de : 
- [x] production n'est pas listée dans la page productions
- [x] aucune page production n'est créée pour cette production
- [x] la production apparaît en revanche dans les listings des membres auteurs
- [x] cette production listée dans une page auteur renvois vers l'url externe si il y a sinon pas d'actions sur le click

**Comment by BenjmnG** [comment]
Il faudra alors trouver un moyen visuel subtil pour marquer cette différence.
Pas de problème.

**Comment by BenjmnG** [comment]
Sur ce point je vous propose de nous alerter une fois que cette donnée pourra être passé dans le template.
Et comment y accéder, bien entendu !

**Comment by paulgirard** [comment]
Oui.
On s'occupe de mettre en place le filtrage.
il faudra juste éventuellement créer un élément de style graphique pour les listings dans les pages people (hightlight et normal).

**Comment by Yomguithereal** [comment]
C'est toujours d'actualité ça?

**Comment by paulgirard** [comment]
oui... Je vais m'y mettre
