### ISSUE TITLE
Zone de déclenchement du hover pour les images des listes

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#278]
Pour contenir le problème de lecture des contenus lors du hover dans les listes (cf. capture suivante), on propose de  limiter déclenchement de l’animation à la colonne de gauche (celle de l’image) et non à toute la ligne (cf. le fonctionnement de l’image sur les pages « activités» ).

NB : il faudra répercuter cette modif sur l’ensemble des listes/zones où sont utilisées les listes (par exemple la partie highlights de la page people)

<img width="926" alt="Capture d’écran 2019-05-05 à 10 30 39" src="https://user-images.githubusercontent.com/37452370/57190979-deda5d00-6f20-11e9-971a-b45eded573ad.png">

**Comment by JulieBlanc** [comment]
J'ai fait le changement hier, je l'ai limité à l'image elle-même.
Fixed by 3eb488cb3ed62963c770b27461bd227043787d8e
