### ISSUE TITLE
Zonage/centrage de l’image pour les listes

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#279]
Pour éviter les zones blanches dans les images des listes (cf. Capture ci-dessous), on propose d’utiliser la zone du premier
Pixel coloré

<img width="1005" alt="Capture d’écran 2019-05-05 à 10 07 07" src="https://user-images.githubusercontent.com/37452370/57191013-3c6ea980-6f21-11e9-9d69-cff166f17580.png">

**Comment by JulieBlanc** [comment]
Je ne sais pas comment nous pouvons trouver cette zone sans javascript (et même avec, c'est un peu compliqué)

**Comment by Yomguithereal** [comment]
Je viens de pusher une tentative en ce sens. @paulgirard @AmelieVRL @robindemourat je vous laisse me dire si ça le fait. Je vais probablement passer ça en prod ce soir en partant.

**Comment by paulgirard** [comment]
je clos ça me semble bien.
