### ISSUE TITLE
Utilisation de l’image associée sur les pages activités

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#280]
Pour donner accentuer la présence de de l’image, nous souhaiterions tenter une utilisation de l’image plus centrale.
Nous proposons de tester son utilisation en hero avec les titre et résumé par dessus dans des blocs blanc/avec une opacité (cf. home)

**Comment by JulieBlanc** [comment]
Je ne suis pas sûre de bien comprendre

**Comment by JulieBlanc** [comment]
Nous avons une nouvelle proposition pour les images sur laquelle noue pourrons discuter la prochaine fois. Elle est dans la branch `proposition-img-object`. C'est une proposition plus en accord avec les listings et les higlights.

<img width="1439" alt="Capture d’écran 2019-05-06 à 16 44 45" src="https://user-images.githubusercontent.com/25477334/57233457-f566de00-701e-11e9-9d3e-d8ba494f1345.png">

Sur le hover:
<img width="1439" alt="Capture d’écran 2019-05-06 à 16 44 58" src="https://user-images.githubusercontent.com/25477334/57233461-f8fa6500-701e-11e9-98ac-0bdd38d9141b.png">

**Comment by BenjmnG** [comment]
Je m'appelle Benjamin et j'approuve ce message !

**Comment by paulgirard** [comment]
on réfléchit de notre côté à cette proposition et on fait un retour rapidement.

**Comment by BenjmnG** [comment]
> 
> 
> on réfléchit de notre côté à cette proposition et on fait un retour rapidement.

Cette proposition née de la branche `proposition-img` a été _mergé_ dans la branche  `proposition-home` pour les besoin de notre dernier atelier.
Or je viens de _merger_  `proposition-home` branche dans le `master` car 90% des apports on été validés oralement.

Reste cette histoire d'Image associées, à vous de jouer avec !
