### ISSUE TITLE
Texte de présentation sur les pages listing

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#281]
Comme signalé lors de la précédente réunion, nous sommes moyennement convaincus par le texte en rouge dans les pages listing.
A la reflexion, comme ce texte -un peu lourd- est deja utilisé dans la page « about », il n’est  pas forcément nécessaire de lui donner autant d’importance.
Nous avons réfléchis à deux pistes pour « alléger » sa présence:
- Tooltip sur le titre de la page dans la colonne de gauche
- lien vers la page about avec ancre idoine

**Comment by JulieBlanc** [comment]
Le texte de présentation apparaît maintenant au hover sur le titre.
Fixed by 0f77d8c87b2845dc285036dcd8c8abab571abda8
