### ISSUE TITLE
Langue de la valeur name pour les activités

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#285]
Il me semble que l'on ne peut pas sélectionner de langue pour la valeur `name` dans les activités. Est-ce qu'on peut faire passer l'option de langue ?
Pour l'instant, la valeur name est sélectionné comme suit: `activities.name`; et on aimerait pouvoir choisir `activities.name.fr` ou `activities.name.en`

**Comment by paulgirard** [comment]
Il n'y a pas de valeurs en et fr pour name.
Il n'existe qu'une seule version on utilise la même quelque soit la langue demandée.
Je te laisse la clore.
