### ISSUE TITLE
Données à passer dans le slider de la home

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#286]
Il y a certaines données que je n'arrive pas à faire passer dans le slider de la home, je les ai commentées dans `home/fragments/slideshow.js`
Je travaille pour le moment sur la branch `proposition-home`, c'est là que le fichier se trouve

**Comment by Yomguithereal** [comment]
Je commence ça. Je vais modifier en profondeur le fichier pour enlever toutes les conditions sur les langues qui peuvent être simplifiées pour éviter de la répétition.

**Comment by Yomguithereal** [comment]
@JulieBlanc j'ai fait le ménage et corrigé les points que tu avais mis en commentaire. Je te laisse fermer l'issue si la solution te convient. J'ai aussi simplifié le code pour ne plus avoir de conditions sur la langue et passe par de la récupération de valeur dynamique comme ceci:

```js
slide.data.title[lang]
```

**Comment by BenjmnG** [comment]
Super utile merci !
Est-ce valable pour toutes les données a caractère bilingue ? Ou seulement
le carousel ?

Le mar. 14 mai 2019 11:42, Guillaume Plique <notifications@github.com> a
écrit :

**Comment by Yomguithereal** [comment]
C’est valable pour toutes les données bilingues. Tu verras ce pattern à plusieurs endroits du code.

**Comment by JulieBlanc** [comment]
Merci @Yomguithereal, c'est beaucoup plus élégant comme cela
