### ISSUE TITLE
Liste Associées - Rendre l'esthetique plus proches des Highlights

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#290]
![image](https://user-images.githubusercontent.com/10298798/57585636-12058900-74eb-11e9-8096-fcdd03046e30.png)

Rendre l’esthétique plus proches des Highlights mais avec ses specificités
Cela est une conséquence du passage au 1 colonne

**Comment by paulgirard** [comment]
+1 
Par ailleurs on milite pour réduire leur hauteur .

**Comment by BenjmnG** [comment]
Très bien, la hauteur de chaque cellule tendra a décroître

**Comment by JulieBlanc** [comment]
Done by 6ff83eb7149cdbfbebf38c67e7b5d3ddef740fa5
