### ISSUE TITLE
Home : Les Bullets doivent t'elle rester en dehors de l'animation ?

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#292]
![image](https://user-images.githubusercontent.com/10298798/57585792-36626500-74ed-11e9-9510-0692e680d535.png)

**Comment by paulgirard** [comment]
@AmelieVRL et moi pensons que ce serait mieux si les bullets ne bougent pas mais c'est pas très important.

**Comment by BenjmnG** [comment]
Ok. Si les avis convergent ce détail devrait pouvoir se faire.

**Comment by Yomguithereal** [comment]
Ya des soucis d’animation aussi dans certains cas les transitions ne sont pas animées mais je n’arrive pas à mettre le doigt sur ce qui pose problème.

**Comment by BenjmnG** [comment]
Certain cas à savoir certain navigateur ? Lesquels ?
Ou certain article ( plus surprenant )

Dis m'en plus et je regarderai,

B.

Le jeu. 16 mai 2019 à 13:07, Guillaume Plique <notifications@github.com> a
écrit :
