### ISSUE TITLE
Build spécifique (home + ordre page people) automatiquement toutes les 15? minutes

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#294]
La home contient des données très fraiches venant de github et de twitter.

Pour la faire vivre il faudrait mettre un script dans un CRON qui : 
- [x] lance les scripts de récupération des données GITHUB, TWITTER
- [x] build si possible que la home et de l'ordre du listing people ou plus simplement de tout mais basé sur les données de git et non celle en cours d'édition sur le CMS
- [x] deploy en prod par rsync donc que le diff.

**Comment by jri-sp** [comment]
Hello,

Quelle est la commande à lancer ?
