### ISSUE TITLE
 specify mandatory fields in CMS

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#295]

**Comment by AmelieVRL** [comment]
Une simple astérisque à coté du titre du champ suffira.
L'idée étant juste de préciser clairement ces champs obligatoires pour éviter à l'usager de cliquer sur save avant d'avoir saisi ces champs obligatoire (et de ce retrouver avec le message contextuel qui dit "Hep, t'as pas rempli ce champ obligatoire")
