### ISSUE TITLE
script hydrate

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#3]
@Yomguithereal a besoin pour lfuidifier le développement d'un script qui hidrate le CMS avec un jeux de données de tests. 
C'est souhaitable comme test du modèle et pour ne pas avoir à recréer des contenus de test à la main à chaque itération/déploiement.

- [x] json
- [ ] markdown

**Comment by Yomguithereal** [comment]
Fait pour la version json de dev. Reste le markdown, le cas échéant, si on n'a pas une stack de PPRD valide d'ici là.

**Comment by paulgirard** [comment]
On laisse tomber le markdown.
Normalement on devrait pouvoir se passer de cet import qui n'est utile que temporairement.
