### ISSUE TITLE
CMS : liste des objets

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#30]
# structure commune
- en entête des search et filtres
- un tableau avec un 'minimum' de lignes dont les entêtes peuvent permettre de changer le tri
- pour chaque ligne un léger barckground indique si c'est draft.

# Activities
## filtres

Name : search plein texte
actif : filtre par un select monovalué
draft : filtre par un select monovalué => tout, draft, public
type : filtre sur l'enum select multivalué
Les filtres sont cumulés par un ET.

## colonnes 
- name : sort alphabétique
- type : pas de sort 
- lastUpdated : sort par date et heure mais en fait ça marche avec alphabétique ?)
- nombre de liens people : sort 

Par défaut tri par 'name' alphabétique.
Note: Rien sur les dates ? 

# People

## filtres
Search : sur 'firstName LastName' **et** role
actif : filtre par select monovalué (vrai par défaut)
draft : filtre par select monovalué

## colonnes
- 'firstName lastName' : sort alphabétique sur lastName + icône si membership == associé
- role : sort alpha
- lastUpdated : sort par date et temps mais en fait ça marche sans doute avec alphabétique 
Par défaut tri alphabétique sur LastName.
 
# News
## filtres
Search : sur 'title'
draft : filtre par select monovalué
type : filtre sur l'enum select multivalué

# colonnes
- title (fr sinon en): sort alphabétique
- label (fr sinon en): sort alpha + icône pour type 
- startDate : sort par date (alpha sur date iso ?)
- lastUpdated : sort par date et temps mais en fait ça marche avec alphabétique ?)
- nombre de liens : sort

Par défaut tier par startDate

# Productions

## filtres
- Search : sur ref 
- spire : filtre si le champs spire.id existe
- draft : boolean sort
- type : filtre sur l'enum en multivalué

## colonnes :
- title (fr sinon en): sort alphabétique
- authors of the labo : que les LastName
- year : year of date sort possible
- type + group en icône (groupe = aggrégation des types)
- lastUpdated : sort par date et temps mais en fait ça marche avec alphabétique ?)

Par défaut tri par date (antéchronologique) en dernier

**Comment by Yomguithereal** [comment]
Je viens de faire une passe sur les listes. Il manque les filtre custom et les boutons pour sort mais ça avance. Ca devrait passer en prod après 18h.

**Comment by Yomguithereal** [comment]
Je viens d'ajouter les filtres et ai affiné la recherche (la recherche prend en compte tous les champs voulus et normalize mieux les champs). Passage en prod dans la nuit.

**Comment by Yomguithereal** [comment]
J'ai ajouté le sort. Passage en prod plus tard.

**Comment by paulgirard** [comment]
C'est top !

Je veux bien un tri sur la colonne links pour un usage data curation.

**Comment by paulgirard** [comment]
icône 'membre associé' : https://material.io/tools/icons/?icon=compare_arrows&style=baseline

news
type === 'notice' https://material.io/tools/icons/?icon=announcement&style=baseline
type === 'event' https://material.io/tools/icons/?icon=event&style=baseline
type === 'chronique' https://material.io/tools/icons/?icon=receipt&style=baseline

Productions' groups
publications : https://material.io/tools/icons/?icon=book&style=baseline
webEditions : https://material.io/tools/icons/?icon=desktop_windows&style=baseline
tools : https://material.io/tools/icons/?icon=build&style=baseline
situations : https://material.io/tools/icons/?icon=group&style=baseline
media : https://material.io/tools/icons/?icon=mic&style=baseline

**Comment by Yomguithereal** [comment]
J'ai ajouté les icones.
