### ISSUE TITLE
S'assurer que la structure HTML est accessible ( ARIA )

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#301]
A faire par partie

- [x] Footer
- [x] Topbar
- [x] Nav

--
--
- [ ] **Home**
- [ ] Slider
- [ ] Flux
- [ ] Now

--
--
- [ ] **Pages liste**
- [ ] activity
- [ ] News
- [ ] People
- [ ] Production

--
--
- [ ] **Page objet**
- [ ] Activity
- [ ] News
- [ ] People
- [ ] Production

--
--
- [ ] About
- [ ] Archive

**Comment by Yomguithereal** [comment]
Je crois que c'est pas mal fait maintenant. N'hésite pas à rouvrir si tu penses le contraire.
