### ISSUE TITLE
Issues suite à la réunion du 22/05/2019

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#305]
**HOME**

- [x] Tweet: tweet, retweet, Réponses (Issue #41)
- [x] points du carousels: en dehors, ils ne bougent pas
- [x] passer le footer sur la colonne de gauche + l'aligner à gauche  (Julie)
- [ ] espacement vertical des pre/image bouge lors du hover
- [x] Flux: pour voir où on est dans la liste essayer de laisser le titre en sticky  (Julie)

**PAGE LISTING**

- [x] enlever le point information sur actualités
- [x] fonction search > input type search à mettre dans les filtres  (Julie)
- [x] refaire les filtres en mettant les inputs assemblé dans un endroit (permet d'enlever les fixed element)  (Julie)

**PAGE EQUIPE**

- [x] ordre aléatoire
- [x] ajouter le cursor pointer sur "afficher les anciens"
- [x] problème avec le filtre "membre" > transforme la liste  (Julie)

**PAGE PEOPLE**

- [x] afficher les contact uniquement s'il y en a (voir Pamela)
- [x] enlever les guillemets si le champs "statut" n'est pas rempli
- [x] menu à gauche disparait sur le footer (Julie)
- [x] mettre le lien uniquement sur le CV

  

**PAGE OBJET**

- [x] pour les écran plus haut que large, mettre l'image sur toute la hauteur (même si l'image est coupée)
- [x] pour les sites/fichiers associés = rajouter un title sur le `<a>` ?

  

**TOUTES LES PAGES**

- [x] vérifier tous les liens: si c'est un lien extérieur mettre un `<a>` au lieu d'un `<link>` et ajouter  `target="_blank" rel="noopener"`

**Comment by JulieBlanc** [comment]
@BenjmnG je n'arrive pas à faire fonctionner les titres en sticky dans le flux, peux-tu y jeter un coup d'oeil ?

**Comment by BenjmnG** [comment]
Yep, je m'en charge

**Comment by JulieBlanc** [comment]
"Refaire les filtres en mettant les inputs assemblé dans un endroit (permet d'enlever les fixed element)" > Done by ce54e836662f9de9be01ce3d05061cdd73529a29

**Comment by JulieBlanc** [comment]
* Problème avec le filtre "membre"
* Refaire les filtres en mettant les inputs assemblé dans un endroit (permet d'enlever les fixed element)
→ Done by ce54e83

**Comment by BenjmnG** [comment]
> pour les écran plus haut que large, mettre l'image sur toute la hauteur (même si l'image est coupée)

→ Done mais à vérifier l'élégance par l'usage

**Comment by BenjmnG** [comment]
> espacement vertical des pre/image bouge lors du hover

J'ai du mal à visualiser ce Bug sur ma config. @JulieBlanc le vois tu ?

**Comment by JulieBlanc** [comment]
Je ne sais plus où tu m'as parlé du problème de target sur le flux. En tous les cas c'est fixé (1dadf536bcf44f6ee1cf749d4239c2bea4b01379)

**Comment by BenjmnG** [comment]
C'était directement dans un commit,
Top merci !

**Comment by JulieBlanc** [comment]
Passer le footer sur la colonne de gauche pour la home: Fixed by af59549eba696b957f8982919332d0690a511d9e
