### ISSUE TITLE
fonction SearchInput ne passe pas

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#312]
@Yomguithereal @paulgirard 

J'ai une fonction React qui ne passe pas et je n'arrive pas à trouver pourquoi, l'un de vous peut-il regarder ?

Dans la branche `search-function`, j'ai ajouté un module SearchInput.js (components/helpers/SearchInput.js) qui contient une fonction `SearchInput`. 
La fonction est ajouté dans le module FilterProduction.js

Lorsque je vais sur la page Production, voilà le message d'erreur:
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Merci !

**Comment by paulgirard** [comment]
Tu as utilisé un export par défaut.

Donc tu dois importer dans filterPrroduction comme ça je pense : 
import SearchInput from '../../helpers/SearchInput.js';

Je n'ai pas le temps de tester là maintenant mais si ça ne marche pas dis moi.

**Comment by JulieBlanc** [comment]
Même problème.
Ce n'est pas urgent, j'ai fait une branch spécialement pour avancer sans

**Comment by Yomguithereal** [comment]
En gros le message d’erreur dit que tu essaies d’utiliser qqpart ce que tu crois être un composant mais qui ne l’est pas. Vérifie ton export/import et typos.

**Comment by paulgirard** [comment]
je regarderai ça.

**Comment by BenjmnG** [comment]
Passant par là, j'ai pense que c'était un simple problème de {}
Tu confirme que cela fonctionne comme tu veux @JulieBlanc

**Comment by JulieBlanc** [comment]
Fixed by fc697ab6753473705c3c7132c8a08bcfe0f93d32
