### ISSUE TITLE
Balise P entre deux elements figures

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#314]
Dans le CMS, J'ai placé deux images classés `serie-paire` l'une après l'autre, sans aucun saut de ligne désiré.
Or je me retrouve avec une balise P indésirable enter ces deux images.
```

<figure class="serie-pair">
          <img src="/static/B_dddad558-3edd-4383-87fd-0a701d55db02.jpg" alt=""></figure>

<p><br></p>

<figure class="serie-pair">
          <img src="/static/B_17e83c1e-d07a-493b-9a26-2412df7dd309.jpg" alt="">
```

Je pourrais très bien annihiler cette affreuse balise vide avec une règles CSS.
Mais je risquerai de m'attirer les foudre du futur rédacteur si jamais il souhaite intentionnellement  placé un élément P avec un texte entre deux, trois, cinq... images `serie-paire`.

Bref.. Une règle dans le template pour vérifier que si un élément `<p><br></p>` se dresse entre TOUTES images successive, alors il faut l'enlever ?

**Comment by paulgirard** [comment]
Je propose que ce problème soit réglé en amont dans le CMS.
A voir comment @Yomguithereal 

Si il y a une p entre deux figures considèrent les comne des séries différentes.

**Comment by Yomguithereal** [comment]
Oui cela est à gérer dans le templating. Je regarde ça à mon retour à la civilisation.

**Comment by Yomguithereal** [comment]
On a un exemple de page avec ce cas qui se présente? Que je puisse debug le truc efficacement?

**Comment by Yomguithereal** [comment]
Je m'auto-réponds: algoglitch a l'air pas mal pour ça

**Comment by Yomguithereal** [comment]
@BenjmnG j'ai tenté un truc qui a l'air de marcher. Du coup les images en série, par exemple dans algoglitch, ont désormais les classes correctement alternées en pair/impair et il semble que cela fasse péter votre css/layout.

**Comment by BenjmnG** [comment]
Rien de méchant, ce sera réglé dans quelques instants

Le jeu. 27 juin 2019 à 10:54, Guillaume Plique <notifications@github.com> a
écrit :

**Comment by Yomguithereal** [comment]
On ferme cette issue du coup, c'est bon?

**Comment by BenjmnG** [comment]
Yep,
Merci pour ton taff 😃
