### ISSUE TITLE
Page contexte pour la topbar

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#315]
@paulgirard, @Yomguithereal  Est-il possible d'implémenter la récupération du `pageContext` dans le composant `TopBar.js` ?

**Comment by Yomguithereal** [comment]
@JulieBlanc, de quelle info du contexte de la page as-tu besoin? Je vois que le composant `TopBar` reçoit déjà les permalinks et la langue courante.

**Comment by JulieBlanc** [comment]
J'ai besoin de savoir si on est dans la page liste des productions, des activités, des actualités, la page about ou celle de l'quipe.

**Comment by Yomguithereal** [comment]
C'est pour highlighter le lien de la topbar? Si c'est le cas le composant `Link` peut prendre une prop `activeClassName` qui sera donnée si le lien est la page courante. Est-ce cela dont tu as besoin? Sinon tu peux inférer la page en cours à l'aide de `permalinks`, non?
