### ISSUE TITLE
fallback to french in listing

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#316]
Dans les listings pour les champs baseline/abstract et description (ou autre champs traduit dans les listings).

si langue de l'interface est manquante utilisé l'autre en fallback 
Dans le cas ajouter une balise 
```<span class = 'lang-opacity'></span>```

autour du texte dans la "mauvaise langue"

**Comment by paulgirard** [comment]
J'ai oublié le span class='opacity'

**Comment by AmelieVRL** [comment]
J'ai l'impression qu'on a paumé l'opacité
<img width="1351" alt="Capture d’écran 2019-08-30 à 15 27 26" src="https://user-images.githubusercontent.com/37452370/64025775-bf091d80-cb3d-11e9-879e-6068385307f1.png">

**Comment by AmelieVRL** [comment]
Voir #412
