### ISSUE TITLE
Fichiers Associés : Mauvais lien vers une URL local et non externe

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#319]
Par exemple sur la page Algoglitch, les Blogs et tweeter du projet renvoie vers une URL :
`http://localhost:8000/https:/algoglitch.smvi.co`

**Comment by Yomguithereal** [comment]
Tu as probablement utilisé le composant `Link` qui n'est censé servir que pour les urls internes?

**Comment by BenjmnG** [comment]
Exact, 
Le champ `attachment `si il existe appel un composant Link.
Mais c'est très bien ainsi non ?
Est-ce que le site `algoglitch.smvi.co` ne devrait pas être un URL plutot ?
Auquel cas, il s'agit juste dans ce cas spécifique d'une mauvaise catégorisation du lien ?

**Comment by paulgirard** [comment]
Faut utiliser link si il s'agit d'un fichier local (a.type === 'attachment'), sinon directement dans src.
