### ISSUE TITLE
Ajouter script côté utilisateur

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#321]
Je souhaite ajoute un script côté utilisateur pour améliorer l'expérience des filtres en version mobile. Je dois l'ajouter uniquement dans certaines page, donc je pensais le faire dans les composants Gatsby.
J'ai suivi ce qui est indiqué ici: https://www.gatsbyjs.org/docs/custom-html/#adding-custom-javascript
Je l'ai mis dans le composant site/src/components/pages_list/fragments/FilterProduction.js

Ça ne marche pas, je n'ai pas le "hello world" qui s'affiche dans la console, ni l'élément que j'essaie de récupérer. 
@Yomguithereal, @paulgirard, une idée de  comment le faire fonctionner  ?

**Comment by Yomguithereal** [comment]
@JulieBlanc je parle sous contrôle de @robindemourat mais il me semble que mettre la logique js pour améliorer l'expérience des filtres peut se mettre dans le composant concerné. Pas besoin d'injecter un script dédié dans le html il me semble?

**Comment by JulieBlanc** [comment]
Je ne sais pas comment l'injecter dans le composant concerner alors. Je sais seulement le faire avec du js "classique" et je ne sais pas comment l'injecter.
Par exemple, ici, il y a une liste des scripts que je dois ajouter: https://github.com/medialab/website/issues/324

**Comment by Yomguithereal** [comment]
Dans ce cas la méthode que tu pointes via l'url fonctionnera très bien si elle te permet de faire ce que tu veux. On se chargera avec @robindemourat de remettre ceux-ci dans la logique react plus tard. A moins que nous ayons un temps pour ça dans l'atelier de jeudi et que tu souhaites que l'on travaille ça ensemble.

**Comment by paulgirard** [comment]
Ta balise script est bien ajoutée au DOM.
J'ignore pourquoi le code ne s'execute pas en revanche... Je demande à des experts JS dans la journée.

**Comment by paulgirard** [comment]
@Yomguithereal je te laisse gérer ça.
Voici ce que j'ai compris.
On peut ajouter du code Javscript custom mais que dans le head et donc en passant par le index.js de Gatsby que je n'ai pas trouvé... 

Sinon on peut être passer par cette solution qui utilise la lib loadable component : 
https://www.gatsbyjs.org/docs/using-client-side-only-packages/#workaround-3-load-client-side-dependent-components-with-react-loadable

**Comment by Yomguithereal** [comment]
@JulieBlanc tu peux nous décrire les scripts que tu souhaites ajouter que l'on puisser aviser de la meilleure manière à employer demain à l'atelier, s'il te plaît?

**Comment by JulieBlanc** [comment]
Je les ai décrits rapidement ici : https://github.com/medialab/website/issues/324

3 sont assez simple:
- ajouter la barre de recherche,
- faire apparaître le titre sicky en version mobile pas directement mais après un léger scroll
- en version mobile, dans les pages people, lorsqu'on déploie la navigation et que l'on clique sur une ancre, il faut fermer la navigation lors du clic.

Le 4eme est plus complexe et concerne les filtres productions en version mobile. Nous pourrons en discuter demain.

Dans le principe, je sais faire tous les scripts, c'est juste que je n'arrive pas à appeler un script du côté client avec Gatsby.

**Comment by paulgirard** [comment]
@BenjmnG @JulieBlanc contrètement à ce que je vous disais en atelier c'est assez faciel d'ajouter du JS custom côté client.
Comme montré dans le commit précédent vous pouvez ajouter vos fonctions JS dans le fichier gatsby-browser.js
Pas besoin de relancer le serveur pour tester le watch prend en compte ce fichier.
Ajouter votre test de présence d'un élément DOM + l'ajout des fonctionnalités JS dans la fonction onRouteUpdate.
onRouteUpdate reçoit en argument le nom de la page courante mais à mon avis mieux vaut utiliser le DOM pour définir quelles fonctionnalités activer.
