### ISSUE TITLE
Obfusquer les emails des membres via pseudo elements

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#322]
![image](https://user-images.githubusercontent.com/10298798/59553149-27118400-8f91-11e9-96b7-e23d88ac9769.png)
Suite à nos discutions sur les méchants robots spammeurs, nous avons pris la liberté d'offusquer les adresses email via css.

Conséquence on peut copier le pseudo mais pas le nom de domaine qui reste un pseudo élément CSS.
Pour peu que nous retenions cette solution, il faudrait faire passer le pseudo de chaque membre en lien est place de NEED_SUBSTRING

Je vous laisse en débattre

**Comment by Yomguithereal** [comment]
Oui il faut obfusquer les données elles-même et ne pas passer par le CSS pour éviter les robots. On s'en occupe.

**Comment by Yomguithereal** [comment]
C'est fait. Il faudra qu'on discute aussi du formattage des twitter / github etc.

**Comment by Yomguithereal** [comment]
Pour l'instant on fait un `nom.prenom [at] domain.fr` mais c'est pas très efficace contre les robots. @BenjmnG @JulieBlanc vous auriez un charactère unicode de typo sympa pour remplacer le `[at]` et qui respecte votre design?

**Comment by BenjmnG** [comment]
- On peut hacker un caractère quelconque genre ℻ et le remplacer par un
   arobase dans un fichier font.
   - On peut aussi écrire [chez] avec une ligature qui unirait les 6
   glyphes un arobase.
   - Et / ou simplement utiliser la variante ﹫( Small cap arobase )
   <https://www.compart.com/fr/unicode/U+FE6B> ou ＠ (chasse fixe)
   <https://www.compart.com/fr/unicode/U+FF20>. Variante visuelle efficace
   mais qui est n'est pas reconnu comme un arobase si tu tente d'envoyer un
   mail à une adresse le contenant.


Pour ce qui est du design, si nous utilisons une font custom, nous aurons
un petit traquas, celui d'avoir un dessin de caractère qui se marie aussi
bien à l'helvetica, l'arial, la roboto, l'ubuntu, ... Mais pourquoi pas !
Dans la mesure ou les variantes Small Cap arobase et autres ne seront sans
doute pas reconnu sur certain support comme l'Android de Paul.




Le mer. 26 juin 2019 à 18:01, Guillaume Plique <notifications@github.com> a
écrit :

**Comment by BenjmnG** [comment]
J'ai remplacé le _[at]_ par 💌 puis dans un fichier font, interverti un glyphe _@_ à la place de 💌
Il faut encore que je vérifie le comportement de ces glyphes avec les graisses lights

**Comment by Yomguithereal** [comment]
Petit bémol: est-ce que cela ne risque pas de tromper les utilisateurs qui pourraient éventuellement croire qu’ils peuvent copier coller l’url et se retrouver avec un résultat pour le moins curieux?

**Comment by BenjmnG** [comment]
Définitivement !
Mais j'eu compris que nous assumions cet incohérence et comptions sur la
sagacité du copieur-colleur.
Dans tous les cas, inclure un glyphe qui n'est pas un @ provoquera cette
incohérence ?
A moins de mettre "@sciencepo.fr" ou " 💌sciencespo.fr " en pseudo élément ?

Le jeu. 4 juil. 2019 à 17:03, Guillaume Plique <notifications@github.com> a
écrit :

**Comment by robindemourat** [comment]
Après petit point design avec Amélie, on a choisi d'utiliser l'option : remplacer le @ par un ● soit "amelie.vairelles●sciencespo.fr".

**Comment by BenjmnG** [comment]
Bien reçu,

J'ai fais le nécessaire. 
Un bémol. J'ai, dans le composant `PeopleDetail.js`, ajouté le `●sciencespo.fr` en dur.
Peut être remplacer le nom de domaine par une valeur dynamique si jamais.
