### ISSUE TITLE
La caroussel de la home fonctionne uniquement avec 3 items

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#326]
Et oui !

**Comment by BenjmnG** [comment]
A voir si on change cela.

**Comment by paulgirard** [comment]
le template a été modifié pour générer les bons élements DOM quelque soit le nombre d'éléments dans le slideshow.
Le comportement actuel en cas de nombre différent de l'attendu me semble acceptable : 
- si pas assez (< 3) il y a une ou deux slides vide visible que par le site automatique
- si trop, les lsides surnuméraires sont invisibles (j'ai corrigé les boutons manuels pour limiter à 5).

Nous décidons que le comportement du slidewhow soit marcher pour 3, 4 ou 5 éléments.
une seule slide peut être facile à faire car on désactive le slideshow.
Je peux faire dans le template mais faut me dire quelle classe ne pas utiliser pour ne pas lancer le slideshow ?

**Comment by BenjmnG** [comment]
Je te répond à priori, mettant à peine les mains dans le cambouis

Je m'occupe de virer le slide auto si une seul slide. Pas besoin de classes supplémentairement.

Je vais faire les régles CSS pour les cas de figure 4, 5 slides.

Pour ce qui est du cas de figure seulement 2 slides, j'ai un doute quand au fait de dupliquer les slides.
L'interface et notamment les "bullets" donneront l'information que 4 slides existent or il n'y en aura que deux. Cela me semble (un détail) confusant.

Si tu n'y vois pas d'inconvenient, je vais tenter d'harmoniser tout cela
- 1 slide : Pas de carrousel, juste une slide
- 2 à 5 slides : Carrousels fonctionnel avec un nombre de boutons et une animation correspondantes

**Comment by BenjmnG** [comment]
J'ai ajouté le CSS correspondant. Dis moi si cela te convient, Paul.
A noté que le CMS limite à 4 items le nombre de slide dans le carrousel. 
Je n'ai pas pu testé mon code pour 5 slides.

**Comment by paulgirard** [comment]
J'ai passé l'admin à 5 max et corriger le typo du CSS qui faisait planter les contrôles à 5.
