### ISSUE TITLE
tweets and links

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#328]
- [x] ellipse les liens internes (20 caractères)
- [x] lien vers le twitt dans le bandeau

**Comment by paulgirard** [comment]
Done mais j'ai aussi ajouté une icône de lien dans le bandeau car ce n'est pas évident que cette partie est cliquable. Mais je ne suis pas convaincu.

![image](https://user-images.githubusercontent.com/193478/60034831-b7477b80-96ab-11e9-9e7a-ddd3d224feee.png)

@robindemourat @AmelieVRL @JulieBlanc @BenjmnG vous en dites quoi ? 

Deuxième question est ce qu'on met un lien vers le tweet à l'origine du RT ou de la réponse ?
Dans ce cas on vire le lien vers le compte ou lien que sur l'icône ?

Tant de questions

**Comment by AmelieVRL** [comment]
@paulgirard pour moi ce serait plus logique de mettre le lien vers la réponse (qui inclue le tweet à l'origine du RT)
Pour l'icone je n'ai pas d'avis, je pense que je me rendrai mieux compte "en situation".

**Comment by robindemourat** [comment]
oui rajouter un icône peut être bien - et/ou en complément coder visuellement le nom de compte et/ou la date du bandeau comme les autres liens (en rouge) pour signifier qu'ils sont cliquables ?

Pour les cas RT je pense que le lien du bandeau principal devrait pointer vers le RT. Pour les tweets à l'origine d'une réponse je transformerais tout le bandeau "en réponse à" en lien vers le tweet d'origine (avec même problématique de le coder visuellement comme un lien), possiblement en gardant le lien vers le compte.

**Comment by BenjmnG** [comment]
Je me suis amusé à inclure un icone Link dans le bandeau du RT.

![image](https://user-images.githubusercontent.com/10298798/60273783-29f86700-98f7-11e9-977b-a390ce614c0a.png)


J'ai l'impression que l'on surcharge ce petit interface.
Impression renforcé si on retweet quelque choses sans aucun message

![image](https://user-images.githubusercontent.com/10298798/60274014-983d2980-98f7-11e9-9150-cad49a5eade0.png)


Je garderai le nombre d'information contenu dans le bandeau du tweet original aussi minimal que possible.
Notre objectif est avant tout de donner à voir et renvoyer avant tout vers l'activité _tweetesque_ du Medialab.
Je me range donc de l'avis d'Amelie. Un lien vers le RT effectué par le medialab est suffisant car renvoie vers le tweet original.

Concernant ton insatisfaction Paul, il faut que j'arrive forcer les emojis dans un affichage plus sobre et monochrome. Il sont trop visible dans leurs versions 3D

**Comment by paulgirard** [comment]
Pour terminer ça ce sera plus simple que @robindemourat et @AmelieVRL termine et valide en live ensemble pour éviter les aller-retours.
Pour l'icône, le caractère unicode 🔗 que j'ai mis passe bien sur firefox et chrome sur mon linux.

**Comment by AmelieVRL** [comment]
@robindemourat je suis dispo toute la journée, si tu veux on bloque un créneau pour finaliser ça dans l'aprés-midi?

**Comment by robindemourat** [comment]
@AmelieVRL ok on voit ça cette après-midi
