### ISSUE TITLE
créer des sous-listes actualités et productions qui regroupent les "vieux" objets dans une page 'tout'

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#331]
relates #212 #266

**Comment by Yomguithereal** [comment]
Related to #266. Cela serait une solution au temps de chargement des pages lourdes. Problèmes d'UX à prévoir. Standby.

**Comment by Yomguithereal** [comment]
D'autant que pour l'instant les performances de la version de production sont loins d'être infamantes.

**Comment by Yomguithereal** [comment]
C'est devenu inutile avec Wilson. On pourra toujours passer au système des images loadées en ajax si on veut de la perf le jour où les listes seront trop longues.
