### ISSUE TITLE
[Page listing production] auteurs manquants

### ISSUE THREAD

**Issue by robindemourat** [medialab/website#336]
Sur le listing productions, l'item "Reset modernity!" (de type exposition) est affiché sans auteurs sur la page listing alors qu'il a 3 auteurs visibles une fois sur la page production.

<img width="1280" alt="Capture d’écran 2019-06-20 à 17 08 43" src="https://user-images.githubusercontent.com/1876890/59860042-340de900-937e-11e9-9f84-26d997a31b89.png">

**Comment by paulgirard** [comment]
Le champs authors est différents de la liste des membres du labo qui sont auteurs.
Or pour le champs authors n'est pas éditables dans le CMS... 
Mais c'est misleading donc faudrait remplir authors si vide avec les infos de people... 
Ou alors on rends authors mandatory ?

- [ ] revoir le formulaire production et y ajouter authors à minima (à faire en même temps que #277 )
- [ ] remplir automatiquement authors à partir de people (demande de charge l'index des noms de people à la création des noeuds dans gatsby-node.js => ouvrir le json people en plus de prod) @Yomguithereal ça me semble faisable mais dis moi si tu vois un loup.
