### ISSUE TITLE
Page personne - citation personnelle - mettre des guillemets français pour la version française

### ISSUE THREAD

**Issue by robindemourat** [medialab/website#337]
Nécessité de wrapper le composant de listing des personnes et le composant de la page objet avec une classe informant sur la langue (Robin).

Puis d'adapter les guillemets en fonction de la langue (Benjamin & Julie)

**Comment by BenjmnG** [comment]
@robindemourat il existe un moyen très simple de le faire en CSS en se basant sur l'attribut lang du `<html>`
On s'en occupe !

**Comment by robindemourat** [comment]
Ok !
