### ISSUE TITLE
Add or edit 404 page template

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#338]

**Comment by Yomguithereal** [comment]
@BenjmnG j'ai ajouté la page 404. Pour y accéder en dev il faut taper une url inexistante, et cliquer sur le lien de la page d'helper de dev en haut qui dit, visualiser la page 404 ou un truc approchant.

La page n'est pas bilingue et il faudra donc prévoir un texte dans les deux langues sur la même page.

**Comment by AmelieVRL** [comment]
@robindemourat : on peut regarder ça?

**Comment by robindemourat** [comment]
ok

**Comment by AmelieVRL** [comment]
today?

Amélie


Le lun. 29 juil. 2019 à 11:02, Robin de Mourat <notifications@github.com> a
écrit :

**Comment by boogheta** [comment]
J'ai l'impression que le template n'est pas utilisé ?
Les 404 sont renvoyés directement par nginx, par exemple ici https://medialab.sciencespo.fr/actu/1
Ptet juste une redirection à régler dans la conf nginx?

**Comment by jri-sp** [comment]
C'est corrigé :)
