### ISSUE TITLE
CMS: conserver la date de la dernière édition

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#34]
La date (précision minute) de dernière édition est utile pour repérer les contenus dans les listes.
A voir comment on stocke ça (attributs technique des objets). Meixu vaut décoréler du versionning par soucis de simplification non ?

Quand on aura des users il faudra mettre l'auteur aussi.

**Comment by Yomguithereal** [comment]
Je gère un timestamp de dernière mise à jour. Est-ce qu'on veut différencier mise à jour et création?

**Comment by paulgirard** [comment]
je ne vois pas trop pourquoi on aurait besoin de la date de création. si vraiment c'était important on pourrait retrouver dans le git. En même temps c'est tout con à garder.

@AmelieVRL  ton avis ?

**Comment by AmelieVRL** [comment]
J'aurais tendance à dire conservons la date de dernière mise à jour.
D'expérience, il y a périodiquement des contenus qui "disparaissent" (pb serveur et/ou CMS)… et c'est utile pour les repérer (oui @paulgirard pas quand c'est bien fait! ^_^).
