### ISSUE TITLE
améliorer le search

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#340]
- [x] pour l'instant appuyer sur entrée n'a aucun effet alors que pour le ctrl+f cela déclenche en général un scroll vers le prochain match - on pourrait essayer de l'implémenter
(keyboard event + focus on mark dom elements)

Search expression entière par défaut. Pour séparer l'expression en sous expression optionnelle j'ai mis comme séparateur " | et '

**Comment by paulgirard** [comment]
@robindemourat je veux bien un coup de main sur le focus

**Comment by robindemourat** [comment]
J'ai ouvert une [PR](https://github.com/medialab/website/pull/367) qui gère l'appui sur entrée et l'ordre des matches, je te laisse me dire si ça convient.

**Comment by paulgirard** [comment]
Merci ! je teste ça
