### ISSUE TITLE
SPIRE des auteurs de type orga sont mal filtrés

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#341]
![image](https://user-images.githubusercontent.com/193478/59937575-1eb6be80-9453-11e9-8bca-85079d087f40.png)

**Comment by Yomguithereal** [comment]
Qui est ce Klaus?

**Comment by paulgirard** [comment]
très bonne question...

**Comment by paulgirard** [comment]
lol
![image](https://user-images.githubusercontent.com/193478/59946912-2c2c7280-946c-11e9-872c-d955280f1f57.png)

**Comment by Yomguithereal** [comment]
Pas mal :)
