### ISSUE TITLE
[onglet twitter] liens hashtags invalides

### ISSUE THREAD

**Issue by robindemourat** [medialab/website#346]
Dans l'onglet twitter les liens vers hashtags renvoient vers un 404 sur twitter. Il semble que c'est parce que le lien est construit en incluant le # (e.g. [`https://twitter.com/hashtag/#funfacts`](https://twitter.com/hashtag/#funfacts)) alors que le lien sans le # est valide (e.g. [`https://twitter.com/hashtag/funfacts`](https://twitter.com/hashtag/funfacts))

**Comment by Yomguithereal** [comment]
Il me semble avoir déjà corrigé ceci dans 3e2de6a73ee90a49fc0561ccd63576bc2add463d. Mais ce n'est pas en production.
