### ISSUE TITLE
npm error and failed

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#348]
@Yomguithereal, @paulgirard, depuis cette semaine, je n'arrive plus à lancer le site. J'ai tout essayé:
- `npm run reinstall` me lance un message d'erreur sur la fin
- `npm install` lance aussi un message d'erreur
- `npm run clean`
- `npm run dev``

Je crois que j'ai fait une upgrade de node pour un autre projet. Peut-être que ça vient de là ? Je ne suis pas sûre. En ce moment j'ai la version node 12.5.0

Message d'erreur avec `npm install`
![Capture d’écran 2019-07-01 à 09 50 44](https://user-images.githubusercontent.com/25477334/60419549-d5e6ce80-9be5-11e9-8b06-5eac7a347949.png)

**Comment by JulieBlanc** [comment]
J'ai réglé le problème, cela venait en effet de la version de node. Je suis retournée sur une version antérieure

**Comment by Yomguithereal** [comment]
Sur quelle version de node as-tu eu des problèmes?

**Comment by oncletom** [comment]
Si tu bascules de version de Node (node 10 vers node 12) après avoir fait un `npm install`, les dépendances comme `node-sass` ont besoin d'un traitement spécial (elles compilent des trucs qui ne sont pas du JS pour causer à Node).

Si tu repasses à Node 12 et que tu fais ça, a priori ça devrait rouler :

```
npm rebuild
npm rebuild --prefix site
npm rebuild --prefix admin
```

**Comment by Yomguithereal** [comment]
Merci @oncletom. Cela semble l'hypothèse la plus plausible en effet. Mais je vais tester node 10/11/12 pour être certain que l'on n'ait pas une dépendance capricieuse.
