### ISSUE TITLE
custom client Javascript et rechargement de page

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#349]
dan gatsby-browser le hook onRouteUpdate est déclenché bien avant (?) le chargement du DOM en cas de rechargement de la même page.
L'élément #search n'est pas trouvé alors qu'il est bien là.

J'ai ajouté un setTimeout mais c'est pas glop.

@yomguithereal : moyen de faire mieux j'aimagine ?

**Comment by Yomguithereal** [comment]
Je ne trouve pas pour le moment :( On va se rabattre sur un bon vieux [`waitFor`](https://github.com/medialab/artoo/blob/master/src/artoo.helpers.js#L292-L315) si je trouve pas mieux.
