### ISSUE TITLE
Ajout script pages ProductionListing.js et NewsListing.js 

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#351]
Script pour fermer les filtres en version mobile lorsqu'on clique sur une année.

Ajouter le script suivant aux pages ProductionListing.js et NewsListing.js
```javascript
let listYears = document.getElementById("list-years").getElementsByTagName("li");



for(let i = 0; i < listYears.length; i++){

       let link = listYears[i].getElementsByTagName("a")[0];

       link.addEventListener("click", closeFilters);

       

}



function closeFilters(){

    document.getElementById("radio-phone-close").checked = true;

}

```

**Comment by paulgirard** [comment]
mais ce script ne doit être executé que en version mobile ? et pas en version desktop ? 
Si oui comment on détecte la version mobile ?

**Comment by JulieBlanc** [comment]
J'ai fait tous les scripts en une seule fois pour pouvoir tout vous fournir et qu'il n'y ai pas de problème d'une page à l'autre. Celui-ci est donc daté. 
Mais pour répondre à ta question @paul, je n'ai pas besoin de repérer la taille de l'écran avec le script car l'input radio n'est actif qu'en version mobile grâce au CSS

**Comment by paulgirard** [comment]
ok
