### ISSUE TITLE
ajouter date aux productions associées ?

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#359]
J'aimerai ajouter les dates aux productions associées.
J'ai commenté le code dans le composant car en l'état la classe CSS DateNews dans ce composant n'est pas gérée.

**Comment by BenjmnG** [comment]
@paulgirard, j'ai ajouté le nécessaire pour les Productions associées.
Est-ce que cela répond à ta demande ?

**Comment by Yomguithereal** [comment]
A vérifier sur la prochaine mise en prod.
