### ISSUE TITLE
npm run fail

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#360]
Navré de vous embété avec cela mais j'ai un comportement incohérent avec `npm run load`
L’exécution de cette commande renvoie l'erreur :

```
> medialab-website-api@1.0.0 load /mnt/e/WORK/Serveur/wamp-3/www/Medialab/website
> node ./scripts/load.js

activities 0bcccc1f-95d6-41d4-b983-7da8fd3c0b70 [ { keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/additionalProperties',
    params: { additionalProperty: 'important' },
    message: 'should NOT have additional properties' } ]
/mnt/e/WORK/Serveur/wamp-3/www/Medialab/website/api/load.js:37
        throw new Error('Failed item validation!');
```

Pour autant la commande suivante `npm run dev` ne pose aucun soucis. Le site est bien compilé en local. 
Etrange ?

**Comment by Yomguithereal** [comment]
C’est « normal ». On a retiré des valeurs du schéma et tu as une ancienne version des donnees avec les propriétés retirées. On va vous envoyer un dump. En attendant le plus simple pour ne pas te bloquer c’est d’aller dans data/activities.json et supprimer toutes les clés « important ».

**Comment by Yomguithereal** [comment]
Ou d’aller dans specs/schemas/activities.json et mettre additionalProperties a true

**Comment by BenjmnG** [comment]
Bon à entendre.
Merci, je suis tes reco'

**Comment by Yomguithereal** [comment]
Dump envoyé.
