### ISSUE TITLE
Attention a #.localeCompare & #.toLocaleDateString

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#365]
Probable que cela produit du code statique sous-optimal...

**Comment by oncletom** [comment]
Ah, c'est-à-dire ?

**Comment by Yomguithereal** [comment]
J'ai l'impression que Gatsby est "intelligent" à ce sujet, ce qui veut dire qu'il va exécuter le code côté client, pour prendre en compte sa locale, plutôt que de le faire en SSR.

Si tu regarde cette [page](https://yomguithereal.github.io/) du blog que je suis en train de drafter par exemple, tu vas voir la date flicker au rendu.

Cela veut dire qu'il a besoin de boostrapper react par dessus et que donc 1. il charge plus de code que nécessaire 2. il doit re-rendre côté JS.
