### ISSUE TITLE
page about : niveau du menu de navigation latéral

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#368]
C'est moi (Firefox 7.0.4 - 64 bits), le menu de la page ne suis pas le scroll.

En image c'est surement plus parlant:
![GIFMaker org_LFbOgo](https://user-images.githubusercontent.com/37452370/60974170-e572bf80-a329-11e9-8f1c-f0bbf5c612ce.gif)

**Comment by BenjmnG** [comment]
Hello Amélie,

Tu as entièrement raison.
J'ai réglé ce problème ce matin normalement.
Peux tu me confirmer que le problème est désormais réglé ?

B.

Le mer. 10 juil. 2019 à 15:48, AmelieVRL <notifications@github.com> a
écrit :

**Comment by JulieBlanc** [comment]
Pour moi, c'est réglé
