### ISSUE TITLE
Page activités - ajout les liens vers les activité associées

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#370]
L'objectif principal de cet ajout est de faire le lien entre deux projets consécutifs ou connexes.
Pas très urgent mais à prévoir à terme.

**Comment by Yomguithereal** [comment]
Tu me rappelles un cas qui ne marchait pas steupl?

**Comment by AmelieVRL** [comment]
La fonctionnalité n'est pas implementée donc tu peux prendre tous les projets.
Mais en l'occurrence, je pensais par exemple à lier "Russia made in France" et "Mapping French Russia".

**Comment by Yomguithereal** [comment]
Related to #182

**Comment by Yomguithereal** [comment]
C'est bon @AmelieVRL.

**Comment by AmelieVRL** [comment]
C'est la méga classe! Merci @Yomguithereal
