### ISSUE TITLE
Iframe & Css print

### ISSUE THREAD

**Issue by BenjmnG** [medialab/website#372]
Je souhaites ajouter une balise `p class="print` après chaque iframe.
Cela afin de supplanter et décrire la source (et idéalement le contenu) de l'Iframe lors d'une impression.

Dans le fichier template.js à la ligne 210, j'ai ajouté un bout de code. 
Qui n'est pas très opérant...

```
      // Iframes
      else {
        const $iframe = $this.find('iframe');
        const internal = !!$iframe.data('internal');

        let src = $iframe.attr('src');

        if (internal)
          src = withPrefix(src);

        output += `<iframe src="${src}"></iframe><p class="print"><span>Iframe</span>${src}</p>`;
      }
    }
```

Est-ce bien le bon endroit pour cela ?

**Comment by Yomguithereal** [comment]
Oui mais il y a un deuxième endroit où il convient d'ajouter ceci et ce n'est pas trivial à faire. Je vais m'en occuper.

**Comment by BenjmnG** [comment]
Merci, tu es bien urbain.
