### ISSUE TITLE
image - légende tronquée

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#377]
Lorsque les légendes sont (trés) longue, elles sont tronquées (cf. l'image de cette page 👍  https://website-prod.medialab.sciences-po.fr/activities/structure-de-lespace-public-numerique)

A defaut d'un affichage complet, ce serait bien d'avoir a minima  un "..." pour indiquer que c'est tronqué.
Qu'en pensez-vous?

**Comment by BenjmnG** [comment]
J'ai enlevé les limitations de tailles pour les légendes.
Disons que l'on fera confiance à l'éditeur·trice pour ne pas tartiner une légende 8000 mots. Et même si tel était le cas, ce n'est pas un réel problème.

**Comment by BenjmnG** [comment]
Précisions :
Selon moi, le choix d'enlever la limitation de taille se justifie par la nécessité de ne pas rajouter une interaction. 
On devrait d'abord pouvoir lire ce que représente l'image et décider ensuite de la visualiser - et non l'inverse.

**Comment by AmelieVRL** [comment]
Je suis Ok avce toi mais pour l'instant je ne le vois pas en prod. Je ré-ouvre, jusqu'à ce que j'ai pu le vérifier.

**Comment by BenjmnG** [comment]
Pas de soucis !

**Comment by Yomguithereal** [comment]
Ca a l'air de marcher mais le footer semble avoir un z-index supérieur au focus sur les images ce qui fait que celle-ci se retrouve dessous sur certains écrans quand l'image est à la fin d'un article.
