### ISSUE TITLE
Version print & Firefox

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#379]
@JulieBlanc @BenjmnG il y a de grosses disparités de versions print entre chrome et firefox. La version firefox n'a pas tout. Regardez algoglitch par exemple.

**Comment by BenjmnG** [comment]
Le problème que j'ai identifié :

- le bloc principal commençait sur la 2e page
- le bloc principal ne dépassait pas quelque soit la longueur du contenu.

Ce problème est résolu, je te laisse clore si il n'y en avait pas d'autre.
