### ISSUE TITLE
caractère d'obfuscation des mails : pb de rendu

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#390]
Pas sure que ce soit très bon pour notre street cred' ce caractère en forme de petit <3

<img width="1099" alt="Capture d’écran 2019-07-29 à 10 38 16" src="https://user-images.githubusercontent.com/37452370/62049435-8361f780-b20f-11e9-9bad-770434935b29.png">

Rendu constaté sous Firefox 68.0.1 (64 bits), Mac.

**Comment by robindemourat** [comment]
Je crois que c'est déjà fixé sur master (mais pas encore poussé en prod).

Sur même config:

<img width="1280" alt="Capture d’écran 2019-07-29 à 14 53 59" src="https://user-images.githubusercontent.com/1876890/62050039-ca9cb800-b210-11e9-8440-d25f6d3b1b6a.png">

**Comment by BenjmnG** [comment]
Même constat que Robin.
La _Loveletter_ est remplacé par un arobase. Cela grâce à une font embarquée.

**Comment by AmelieVRL** [comment]
OK, merci. En effet, je vois bien le @ maintenant.
