### ISSUE TITLE
Nouvelle page "outils"/"tools"

### ISSUE THREAD

**Issue by robindemourat** [medialab/website#395]
Cette issue est dédiée à la conception future d'une nouvelle page outils dans le site. Elle est faite en fonction des objectifs suivants:

* rester au plus proche du design et du modèle de données existant
* davantage situer les outils dans des pratiques, des assemblages, des questions de recherche 
* rendre plus visible la production didactique (tutoriels, manuels)
* ne pas faire quitter le site aux visiteurs pour voir la page outils

# Proposition Modèle/backoffice

* utiliser les productions de type “logiciel” et “code”. Mais permettre l’ajout de productions “hors-médialab” qui n’auraient aucun auteur médialab pour pouvoir intégrer les outils qu’on utilise sans en être pour autant les artisans (les "tools we use")
* ajouter au modèle de ces productions-là :
  * un système de tagging défini à la fin de cette issue

Éditorialement, on ajouterait systématiquement des "attachments" correspondant aux documents liés suivants :

  * code source, page de présentation propre, démo
  * liste de tutoriels et manuels associés à l'outil

# Proposition Design

Pour cette nouvelle page outils, visuellement se caler sur les pages listes :
* système de filtres (cf ci-dessous) - 20 possibilités
* clairement différencier outils médialab et non-médialab au niveau du design des cartes

Pour les pages objet production des logiciels et bibliothèques de code, faire un template spécial mettant en avant :

* les trois types d'attachments importants : code source, page de présentation propre, démo
* les tags du logiciel (sous la forme d'une sorte de cartel ?)
* les ressources associées (manuels et tutoriels) bien mises en avant avec des cartes propres
* \+ bien sûr les objets liés habituels (personnes, productions, activités, news)

# Proposition de taxonomie de tags fermée 

fondée sur [l'expérimentation](https://medialab.github.io/tools/) précédente et sur la taxonomie du [bamboo directory](https://dirtdirectory.org):

- status/statut (radio)
  - stable
  - experimental / expérimental
- public (radio - choix unique)
  - for developers/pour les développeurs
  - for all / tous publics
- practice/pratique (checkbox - choix multiples)
  - data acquisition / acquisition de données
  - data curation / curation de données
  - data processing / traitement de données
  - data exploration / exploration de données
  - writing & communication / écriture & communication

*Question : rajouter "data visualization" ?*.

---

MàJ 25 Novembre après réu Robin-Guillaume et Robin-Amélie

**Comment by robindemourat** [comment]
Un premier mockup est sur la branche https://github.com/medialab/website/tree/mockups-page-tools dans le dossier `page-tools-mockups` (c'est un simple site statique à faire tourner avec par exemple `python -m SimpleHTTPServer` - css non contractuel ;))

**Comment by boogheta** [comment]
Cool! On review ça mardi tous ensemble en réu tech ?

**Comment by robindemourat** [comment]
Oui - amélie nous rejoint en fin de réunion pour en discuter (on a fait un 1er point les mockups auront bougé d'ici là)

**Comment by robindemourat** [comment]
Here is a little sum up of our plan of action:

- [X] December: we stabilize and edit the schema for the needs of the new `tools` listing page and the specific `single production` view for tools - modified files are `specs/schemas/production.json` and `specs/enums.json`

- [ ] January: @mydu updates the admin `production` view to enable editing the new properties

- [ ] ~20 January : we edit the website data to fill some `tools` with real data to enable developping the frontend views with real data

- [ ] February: @mydu integrates new frontend views based on stabilized mockups

@mydu the code base with updated json-schemas is available at branch `dev-page-tools`, I advise you work on this branch when you'll start.

For the records the schema for the productions has the following new properties:

* attachments
* status
* usages (display as "activités" in the mockups)
* audience

These new properties should be editable in the [`ProductionForm`](https://github.com/medialab/website/blob/dev-page-tools/admin/src/components/forms/ProductionForm.js) component when the type of the related production is `tool`, and these properties should be reset to `undefined` if user sets the type of the production to another type than `tool` during editing.

And, for the next steps, the frontend mockups are at branch `mockups-page-tools` and replicated online [here](http://medialab-toolspage-mockup.surge.sh/) (still a work in progress).

**Comment by robindemourat** [comment]
From today's review session with @mydu @Yomguithereal @robindemourat :

- [ ] backoffice: selector for usages should be multi-choices

- [ ] we don't need to process images for the productions (should be modified in the backoffice CoverSelector component call with no prop `processing`)

- [ ] productions listing -> tools and software should not be filtered out

- [ ] tools listing should be at URL `/tools` and `/outils`

- [ ] listing ordering : filter items with following keys:

1. "publication medialab" first, then "publication hors medialab"
2. "status" (in the order : "usable", then "xperimental", then "archived") 
3. by alphabetical order

- [ ] listing: truncate description text if it's too long

**Comment by AmelieVRL** [comment]
We noticed there are two ways to display the main URL of one tool:
-  the URL field,
- the specific attachment.

We suggested to not display the URL field for tools in the backoffice form.

**Comment by robindemourat** [comment]
TODOList from review of March 2nd:

## Listing view

- [ ] filters should be an OR for activities but an AND when mixing activities, publics and status filters

- [ ] usage labels in cards: translate also the last element

## Single tool page

- [ ] first attachment in red

**Comment by boogheta** [comment]
Last fixes from March 12th:

- [ ] in the list of tools, adjust each tool's card size to the content (avoid overflowing)
- [ ] in the list of tools and on a tool's single page, display only the year of the dates 
- [ ] in the list, sort tools first by provenance (medialab or not) then by descending date (completing the incomplete dates such as none by 0000-01-01, 2004 by 2004-01-01 and 2007-10 by 2007-10-01)
- [ ] in a single tool's page, separate title and provenance in two lines
- [ ] add "vizualisation" category inside the backoffice + css lists filter

**Comment by robindemourat** [comment]
Should we close this @AmelieVRL @Yomguithereal ? (🎉🎉🎉)

**Comment by Yomguithereal** [comment]
Be my guest :)

**Comment by AmelieVRL** [comment]
👍  Gogogo @robindemourat !

**Comment by BenjmnG** [comment]
Beau boulot  : ) 
Great to see you got a new room in your house !
