### ISSUE TITLE
RECUP: Github pour la home

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#40]
Pour peupler la home on a besoin d'un script qui récupère les derniers dépôts github qui ont été actifs.
Cette root d'api donne les 30 dernires événements : https://api.github.com/users/medialab/events
elle peut être paginé jusque 10 pages : https://api.github.com/users/medialab/events?page=5
(https://api.github.com/orgs/medialab/events c'est pareil).

On pourrait récupérer les (2-4?) premières pages, aggréger les événements pas dépôts en gardant l'ordre de premier apparition dans le flux, garder tous les auteurs ayant émis ces événements.

Pour obtenir les métadonnées d'un dépôts : https://api.github.com/repos/medialab/website

On génère une liste de dépôt :
- date événement le plus récent (clef d'ordre) 
- le nom du dépôt
- la description courte
- la liste des langages utilisés https://api.github.com/repos/medialab/website/languages sinon le principal est indiqué dans les méta du dépôt
- la liste des login github ayant participé parmis les events récupérés en créant un lien vers les pages people correspondantes dans le CMS si le login github matche
- le lien vers le dépôt

Est ce qu'on ne mettrait pas la licence ? 

On pourrait faire plein d'autres choses : 
- nombre de star
- nombre de download
- courbe des events dans le temps
Mais faut pas hein ?

- [x] script dans l'api
- [ ] exposer les données au composant de la home
- [ ] reprendre le templating

**Comment by paulgirard** [comment]
@boogheta @AmelieVRL des remarques, idées ?

**Comment by boogheta** [comment]
Nombre de stars et de downloads il faudrait regarder ce qu'il en est avant de trancher, si la plupart sont très bas ce n'est pas forcément judicieux, même si quelques uns sont bcp plus haut.

Si une url est renseignée en description d'en-tête on pourrait éventuelelment utiliser celle là plutot que celle du repo mais ça crée une disparité pas forcément judicieuse.

Par ailleurs ca dépend beaucoup de l'espace alloué et je n'ai pas suivi les dernières évolutions, vous pourrez me montrer un peu où ça va aller avant que je commente plus ?

Et sinon je me pose la question (comme pour twitter d'ailleurs) de ce qui est prévu en termes de rafraichissement de ces données ?

**Comment by paulgirard** [comment]
![image](https://user-images.githubusercontent.com/193478/57649354-4c912380-75c8-11e9-9e72-b9616a212c28.png)

la prod interne est à jour.

Star : tu as raison, mauvaise idée, la plupart seront à 0.
URL: perso je préfère renvoyer sur github pour être cohérent avec ce qu'on affiche (et c'est plus simple)

**Comment by boogheta** [comment]
OK je vois mieux.
Je me dis que les dates peuvent un peu poser question aux visiteurs, peut-être ajouter une info recapitulative des evenements récents, genre "date (5 commits)" ou "date (nouvelle release)" (je ne sais pas si les issues/PR rentrent dans les events)

**Comment by AmelieVRL** [comment]
Ok avec @paulgirard pour garder le renvoie sur github
Pas d'avis pour les stars.

**Comment by Yomguithereal** [comment]
Bon le script c'est fait. Reste le Twitter et à hooker tout ça.

**Comment by paulgirard** [comment]
J'ai connecté le templating.
![image](https://user-images.githubusercontent.com/193478/58488116-1b3c5a00-8169-11e9-8041-939ff92c1583.png)

il me semble ques les trois infos, dates, nb contributions et auteurs sont liées.
En l'état les contributeurs sont séparés.
A revoir ?

**Comment by BenjmnG** [comment]
Good !
Je ferais un regroupement date,contributions, auteurs.

A vous de décider si vous préférez les nickname ou les nom complet.
Bonne idée de renvoyer sur votre propre site lorsque l'on click sur ces pseudo / nom.
Toutefois, je postule une pirouette cognitive entre un click sur le pseudo de YomGuiTheReal et l’atterrissage sur le profil d'un bel inconnu en la personne de Guillaume.

**Comment by paulgirard** [comment]
Oui la pirouette cognitive est une sorte de blague histoire de jouer sur la double identité.
Sachant que le nickname github est visible en haut de la page people ça limite la suprise.
Mais oui c'est un choix à arrêter. @AmelieVRL ton avis ?
