### ISSUE TITLE
Description de la catégorie productions en anglais

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#401]
@AmelieVRL elle manque dans le front. Elle est rédigée qqpart?

**Comment by Yomguithereal** [comment]
J'ai fini par mettre celle-ci qui, je pense, est une traduction de @robindemourat:

> In addition to traditional academic publications, "Web publications" also disseminate the laboratory's activities through an interactive medium that opens up new ways of representing and visually exploring findings. Situations – exhibitions, workshops, simulations, etc. – allow for the public’s involvement in the research process and the testing of hypotheses against the reality on the ground.

**Comment by AmelieVRL** [comment]
C'est le bon texte en effet, mais c'est une trad. de la traductrice que où j'ai remanié la dernière phrase avec Paul ou Donato, je ne sais plus.
