### ISSUE TITLE
Bug tricky du caroussel

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#404]
1. aller sur la home du site
2. aller sur une autre page
3. revenir sur la home en cliquant sur le logo
4. problème d'affichage (regarder le lien 'en savoir plus'):

![bug](https://user-images.githubusercontent.com/2571951/63354821-6a0f1f80-c365-11e9-9fac-6f896c06c3d4.png)

**Comment by Yomguithereal** [comment]
Je pense que cela arrive quand la date wrap sur la nouvelle ligne.

**Comment by JulieBlanc** [comment]
J'ai ajouter un `white-space: nowrap` sur la date, peux-tu me dire si tu as toujours le problème d'affichage ? (je ne l'ai jamais eu sur mes installations)

**Comment by paulgirard** [comment]
Je crois que @AmelieVRL avait le même rendu problématique.
Je met à vérifier.

**Comment by AmelieVRL** [comment]
En effet, mais comme c'était un peu aléatoire, difficile de dire si c'est bien fixé.
A priori, ça a l'air de fonctionner correctement donc je clos!
Merci ;)

**Comment by AmelieVRL** [comment]
Ça recommence:
<img width="1300" alt="Capture d’écran 2019-09-05 à 10 46 54" src="https://user-images.githubusercontent.com/37452370/64326577-88faec00-cfca-11e9-9376-31f5e5ee9140.png">

**Comment by JulieBlanc** [comment]
Les modifications n'ont peut être pas encore été déployées ?
Peux-tu me dire ton installation ? Chrome sur windows ?

**Comment by AmelieVRL** [comment]
Normalement ça a été déployé : Paul a fait une mise en prod hier. :(
Je suis sur Firefox 68.0.2 (64 bits)

**Comment by BenjmnG** [comment]
Chrome sur windows ne pose pas de problème chez moi.
Toutefois, Firefox ou Chrome et sauf omission de ma part,  je ne trouve pas la propriété `white-space: nowrap` sur l'élément `date` qui fut pourtant ajouté il y a quelques jours.

**Comment by AmelieVRL** [comment]
remarque, je n'ai pas le problème sur toutes les entrées du carrousel, et cela dépend aussi du dimensionnement de la fenêtre (par exemple en 1723 x 7935)
<img width="1358" alt="Capture d’écran 2019-09-05 à 11 30 42" src="https://user-images.githubusercontent.com/37452370/64330155-be0a3d00-cfd0-11e9-8a2e-311cadffe961.png">

**Comment by Yomguithereal** [comment]
Je crois que ça a été réglé dans wilson.
