### ISSUE TITLE
RECUP: twitter pour la home

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#41]
# modification du template du flux twitter 

@BenjmnG @JulieBlanc voici des précisions pour faire légèrement évoluer le template du flux twitter.
Le but est de faire rentrer les RT et réponse. A votre disposition pour en discuter si besoin.

Le flux twitter peut contenir trois types de tweets : 
- Tweet normaux 
- Replies : tweet normal + un tweet auquel on a répondu
- Retweet/Quotes : date et éventuellement quote du RT + tweet qu'on a retweet/quote.

## structure du bloc tweet du flux

Nous proposons que chaque bloc de tweet du flux soit structuré comme suit : 
- le header qui indique :  icône tweet | @medialab_scpo | date et heure
(y compris pour les retweet et reply)
- texte du tweet du compte du labo (vide si retweet sans quote)
Si réponse, retweet ou quote on ajoute
- un sous-header qui indique : "en réponse à @compte_twitter" ou "retweet de @compte_twitter"
- texte du tweet d'origine avec une indentation pour signifier que c'est le contexte. 
- au click on ouvre dans un nouvel onglet le tweet du labo et non celui d'origine

### modification du header
- On propose donc de faire remonter le nom de notre comtpe dans le header.
- On propose d'ajouter l'heure dans le header
- En revanche on se demande si c'est nécessaire de mettre l'icône tweet dans ce header ? (surtout si on a un chapeau de flux sticky qui indiqeu en permanence qu'on voit du twitter ?)
- On ne préfère pas y mettre le type du tweet car l'info est peu importante et déjà présente dans le sous-header.

### ajout du contexte
- Signifier le contexte en ajoutant le tweet d'origine dans le même bloc mais en dessous et avec une indentation pour distinguer que c'est pas de nous.
- L'idée du sous-header est qu'il soit moins marqué que le header principal. Peut être lui aussi avec indentation ?
- On a préféré ne pas mettre la date du tweet d'origine dans le sous-header car on se focalise sur notre flux et les dates de nos actions.

# récupération des données

Pour peupler la home on a besoin d'un script qui récupère les X (disons 7) derniers tweets fait par le compte du labo (y compris RT).

Pour chaque tweet on a besoin de : 
- le compte auteur (en cas de RT)
- le contenu
- date et heure du tweet par le compte
- le lien

- [ ] script dans l'api
- [ ] exposer les données au composant de la home
- [ ] reprendre le templating

**Comment by paulgirard** [comment]
@BenjmnG @AmelieVRL est ce que j'oublie qq chose ?
Que fait on si il y a :
- une image associée
- un tweet cité ou en réponse à

**Comment by AmelieVRL** [comment]
A priori, je ne reprendrais pas les images/illustrations, par contre OK pour afficher les tweets cités ou les "en réponse à"
Ton avis @BenjmnG ?

**Comment by BenjmnG** [comment]
Les RT sont une richesses il me semble.
Je vous conseil des les intégrer.

Les images ? Cela induit de les passer à la moulinette pour être cohérent avec notre système visuel.
Si je regarde votre timeline en ce moment, vous avez soit des Images d'illustration d'article ( image deja présente sur le site ) soit des images comprenant du texte (Annonce, ... ) Peu utile de les "processer"

RT Ok ! Image Nope

**Comment by paulgirard** [comment]
--------------------DRAFT en atente de validation --------------- 

Le flux twitter peut contenir trois types de tweets : 
- Tweet normaux 
- Replies : tweet normal + un tweet auquel on a répondu
- Retweet : tweet normal + mention de la date du retweet

Les replies font réponse à un tweet d'un autre auteur.
On propose d'ajouter le tweet d'origine en dessous de la réponse faite par le labo.

Les Retweet sont également des tweets d'autres auteurs.
Question : faut-il ajouter un signe graphique pour distinguer les tweets qui ne sont pas écrit par le labo ? 

Enfin pour les retweets il faudrait simplement ajouter des infos supplémentaires par rapport au tweet normaux : le fait qu'il a été retweeté par le compte du labo à telle date/heure.

@AmelieVRL on valide ça ensemble rapidement

- on ajoute en **dessous** au tweet du compte du labo qui est une réponse

**Comment by Yomguithereal** [comment]
Il y a aussi les quotes, qui sont globalement des retweets avec du texte de notre part en plus.

**Comment by paulgirard** [comment]
Ok j'ai mis à jour

**Comment by BenjmnG** [comment]
Top ! On avance !
Dites moi quand le template actuelle est hydraté avec des vrais morceau de tweet dedans.
N’hésitez pas à inclure les balises HTML manquante pour les données concernant RT et Replies
Je alors ferais un passage CSS pour harmoniser avec l'ensemble

**Comment by paulgirard** [comment]
J'ai conencté et revu le templating comme évoqué dans cette issue :
![image](https://user-images.githubusercontent.com/193478/58488382-8e45d080-8169-11e9-857a-b40750bea83c.png)

Voila voila je ne suis pas designer...
A terminer.

**Comment by BenjmnG** [comment]
Merci Paul pour cette injection
On prend la suite
