### ISSUE TITLE
LanguageFallback a été désactivé.

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#412]
Le languageFallback ajoutait une opacité aux titres/bsaeline/description qui n'était pas disponible dans la langue demandée.

L'opacité a été critiquée notamment sur la page production qui n'a de fait peu voire aucune traduction.

Guillaume a désactivé complètement l'opacité au lieu de le virer de seulement le listing production.

On a décidé de finalement laissé tel quel. 
Il faut rediscuter de ce qu'on fait comme indicateur de languagefallback.

**Comment by AmelieVRL** [comment]
Ok pour la désactiver sur la page traduction, ça fait sens avec les titres des articles et ou outils qui ne se traduisent pas.

Par contre je ne trouve pas que ce soit une bonne idée sur les pages listing. Franchement, on ne comprend pas pourquoi d'un coup, il y a un texte dans une autre langue émerge... d'autant qu'on ne le retrouve pas forcément dans les pages des objets.

Perso, j'ai buggé pendant 5 minutes sur le passage de 
<img width="1351" alt="Capture d’écran 2019-08-30 à 15 27 26" src="https://user-images.githubusercontent.com/37452370/64026922-fd074100-cb3f-11e9-90ac-ae66035f73d9.png">

à

<img width="1351" alt="Capture d’écran 2019-08-30 à 15 27 35" src="https://user-images.githubusercontent.com/37452370/64026992-20ca8700-cb40-11e9-9359-228c54d7189a.png">

**Comment by paulgirard** [comment]
Je conviens que d'avoir viré tous les fallback est un peu rustre. Blame @Yomguithereal .
Mais bon maintenant qu'on a débat je vous laisse @AmelieVRL @robindemourat et @dricci nous dire ce que vous souhaitez que l'on fasse.

**Comment by paulgirard** [comment]
On a décidé de : 
- remettre l'opacité pour le language fallback sauf pour les productions
- pour les productions mettre un language fallback silencieux
