### ISSUE TITLE
collision des textes dans le caroussel

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#416]
Voila, je crois que l'on a déjà évoqué cette erreur.
En image ici :
<img width="845" alt="Capture d’écran 2019-08-22 à 21 09 05" src="https://user-images.githubusercontent.com/37452370/63543301-c8353180-c522-11e9-82a8-c563e787cf3e.png">

**Comment by Yomguithereal** [comment]
Duplicat de #404. :)
