### ISSUE TITLE
Remontée des activités en lien à des actualités

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#418]
Avant la mise en prod, on avait pour chaque actualités, une remontée des people, productions et activités liées.
Aujourd'hui, il semblerait que les activités liées aient disparues, ça doit s'être perdu dans un changement de templates car le bug est aussi sur la preview. :(

Par exemple, ici, on n'a pas la remontée de l'activité "structure de l'espace publique" (alors que c'est pourtant bien précisé dans la base) dans la chronique sur les circuits de l'information:

![Capture d’écran 2019-08-27 à 13 55 48 (2)](https://user-images.githubusercontent.com/37452370/63769177-6d108f80-c8d2-11e9-973a-f35dbb1d7497.png)

![Capture d’écran 2019-08-27 à 13 52 56 (2)](https://user-images.githubusercontent.com/37452370/63769110-3c305a80-c8d2-11e9-929d-34fec92a5f95.png)

Bref, ce n'est pas pratique et c'est même assez gênant pour le séminaire, car on voit les événements comme des éléments dissociés (et non faisant partie d'un tout).

**Comment by robindemourat** [comment]
Résolu par le commit ci-dessus (à vérifier à la prochaine mise en prod)

**Comment by paulgirard** [comment]
Merci @robindemourat
