### ISSUE TITLE
Erreur react

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#419]
J'ai essayé de relancer le site avec npm pour faire des modifications de CSS mais je n'y arrive pas, j'ai une erreur React.
Je ne sais pas d'où ça vient.
J'ai essayé de faire `npm run reinstall`puis `npm run dev`mais j'ai toujours la même erreur.
Quelqu'un pour m'aider ?

![Capture d’écran 2019-08-27 à 15 23 23](https://user-images.githubusercontent.com/25477334/63775064-ddbda900-c8de-11e9-8b19-c404c66cc22a.png)

**Comment by BenjmnG** [comment]
Idem.
J'ai accès à certaine page mais pas toute ( ex. Page d'accueil )
Serait-ce dû à un dump qui n'est pas à jour ?

**Comment by paulgirard** [comment]
probablement un problème de données. Je vous envoie un dump.

**Comment by BenjmnG** [comment]
Merci Paul, cela résout le problème chez moi.
@JulieBlanc, confirmes-tu ?

**Comment by JulieBlanc** [comment]
Ça a marché pour moi aussi :)
