### ISSUE TITLE
bug sélecteurs dans settings

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#423]
Je souhaitais actualiser la Home en ajoutant au carrousel une nouvelle actu sur le prochain séminaire Transnum intitulé "Ville et Numérique" et c'est l'échec:

<img width="559" alt="Capture d’écran 2019-08-29 à 18 33 20" src="https://user-images.githubusercontent.com/37452370/63959051-9de7f480-ca8b-11e9-9be9-b77ef0ad351b.png">

Une idée d'où ça peut venir?

**Comment by paulgirard** [comment]
Je confirme le bug. L'api renvoie bien els données mais le composant ne se met pas à jour. Je regarde.

**Comment by paulgirard** [comment]
ok c'est simplement que c'est le titre anglais qui est utilisé pour le label pour une raison que j'ignore. 
Je mets les titres français par défaut et je vois si on peut mettre les deux.

**Comment by paulgirard** [comment]
c'est bon à tester

**Comment by AmelieVRL** [comment]
ça semble fonctionner. merci!
