### ISSUE TITLE
affichage de la date des événements en home dans la colonne de droite

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#424]
Visiblement il y a une mouche dans la soupe... (c'est pour être polie)
Parfois ça s'affiche bien, parfois non :
<img width="773" alt="Capture d’écran 2019-08-29 à 18 48 15" src="https://user-images.githubusercontent.com/37452370/63959918-975a7c80-ca8d-11e9-8d18-c91159a55be5.png">

**Comment by JulieBlanc** [comment]
Il faut ajouter un `white-space: nowrap` sur la date en CSS.
J'ai quelques modifs à faire mais je n'arrive pas à lancer le site en local, j'ai une erreur: https://github.com/medialab/website/issues/419

**Comment by robindemourat** [comment]
@JulieBlanc merci je vais tester ce fix, et sinon je vais regarder si je peux reproduire ton pb d'install

@AmelieVRL n'y aurait-il pas aussi un problème avec l'ordre ? est-ce qu'il ne faudrait pas afficher les RDV les plus proches dans le temps en premier ?

**Comment by JulieBlanc** [comment]
J'ai fait le fix > 7555ee262ba5afe5e55dd1fa78465a066e9db0cb

**Comment by AmelieVRL** [comment]
@robindemourat je trouve aussi que ce n'est pas optimal comme ordre d'affichage: on devrait certainement inversé, ce serait plus logique.

**Comment by paulgirard** [comment]
Ok j'ai corrigé l'ordre

**Comment by AmelieVRL** [comment]
Perfect!
