### ISSUE TITLE
Page séminaire, changement de style ?

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#427]
Je me pose une question concernant la page "séminaire". Pour le moment, elle est dans le style des pages "activités" avec une image en grand sur la gauche. Je trouve cela un peu gênant avec les images de la liste des séminaires en plus.

Je me demande si ça ne serait pas plus judicieux de changer le style et être plutôt dans le style des page "Le médialab" et "L'équipe". C'est-à-dire:
- pas d'image sur la gauche
- remplacer par un menu vers "Séminaire en cours" et "Séminaire passés"

Ça me semblerait plus cohérent avec l'ensemble du site, qu'en pensez-vous ?

**Comment by paulgirard** [comment]
J'ai vu un commit passé de ta part à ce sujet. Je passe en préprod et je laisse Amélie et Robin réagir.
Peros ça me va.

**Comment by AmelieVRL** [comment]
Salut Julie.
Merci pour ton avis sur cette page.
Personnellement, la page me convient bien ainsi. Je laisse Robien donner son avis.

Nous souhaitons mettre en avant le séminaire comme une activité de recherche en soit, c'est pourquoi elle reprend la forme des pages activités (puisque c'en est une).
Nous avions également besoin dans cette page de faire remonter tous les événements liés (les séances de séminaire) de manière plus visibles c'est pourquoi nous avons ajusté le modèle pour que les séances apparaissent en colonne de droite. 

On peut bien sûr en reparler.
