### ISSUE TITLE
interdire le migrate/rollback en prod par sécurité

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#428]
voir #318

**Comment by Yomguithereal** [comment]
En même temps ça peut aussi être utile en prod. Si on se rend compte qu'une grosse bêtise a été faite on peut rollback à la dernière version.

**Comment by paulgirard** [comment]
oui en effet mais j'ai tout de même du mal à imaginer le cas ou ce serait souhaitable.
Sinon on ajoute un paramètre de query qui force mais bon on peut aussi simplement faire attention ?

**Comment by Yomguithereal** [comment]
On va faire attention :)
