### ISSUE TITLE
le lien dans la page production n'est pas forcément vers spire. Supprimer le mot Spire et trouver une autre formulation

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#429]
Le problème c'est qu'on ne sait pas dans les données vers quoi pointe ce lien. Cela peut être une simple notice sur spire, un full texte sur spire, un site de l'outil, une notice sur le site d'un éditeur...

Je ne vois pas quoi mettre à part lien/link si vraiment on veut mettre qq chose.

Avant la modif de Julie on avait mis l'url de destination comme texte avant l'icône.

CF.
 https://github.com/medialab/website/commit/e97f4b65d79c97139b02c24486bc20ee3ed789af

**Comment by AmelieVRL** [comment]
En effet, Spire n'est pas la bonne formulation ; à la limite on pourrait mettre *[Consulter]*
Je pense que ca marche aussi sans rien d'indiquer, la logique du hover appellant le clic pour la consultation.
@robindemourat, un avis?
