### ISSUE TITLE
traduction des valeurs de contacts/resources liées

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#430]
Dans les objets, lorsque l'on ajoute un lien de type "contact" ou "ressources liées", il n'y a qu'une possibilité de langue.
Ceci conduit à quelques info non traduites sur les pages, cf. la copie d'écran suivante:
<img width="1267" alt="Capture d’écran 2019-09-03 à 14 53 47" src="https://user-images.githubusercontent.com/37452370/64184087-36ef8480-ce6b-11e9-862a-a4f617d78ebf.png">

**Comment by Yomguithereal** [comment]
Remplacé par #507.
