### ISSUE TITLE
publish workflow

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#431]
le processus d'update du site statique : 
- [x] récupère la dernière version du git 
- [x] génère une nouvelle version des données github et twitter
- [x] copie toutes les données dans un nouveau dossier
- [x] build une version spécifique
- [x] rsync de ce dossier vers le serveur web

UI :  

- [x] créer une nouvelle page admin qui contient les boutons suivant (les virer de la home)
- [ ] afficher la liste des objets avec leur lien qui ont été modifiés depuis la date du dernier commit dans le git data
- [x] changer le wording du bouton save dans git en "envoyer ces modifications dans le git pour mise à jour su site statique" 
- [x] ajouter un bouton pour forcer la mise en prod "forcer la mise à jour du site statique"
- [x] afficher la date de dernière mise à jour du site statique

**Comment by Yomguithereal** [comment]
J'ai presque fini. Mais il reste quelques soucis pour le dev local quand il est pas synchro avec le gitlab + probablement de 3 trucs qui pètent aux encamblures.

**Comment by Yomguithereal** [comment]
En gros, en local, en dev, il faut par defaut éviter que le deploy ne push si ya pas de repo configuré et que le build se contente de copier data plutôt que de pull.

**Comment by Yomguithereal** [comment]
J'ai changé les comportements du serveur quand les repos dans la config ne sont pas renseignés. Il faut faire gaffe à ne pas trop jouer avec le feu avec website_data en dev. Il y a website-dump-dev pour les tests mais ma connection n'est pas assez bonne pour mettre à jour le repo avec la dernière version des données. @paulgirard je te laisse jeter un coup d'oeil à tout ça et on pourra finaliser / tester tout ça dans le courant de la semaine prochaine.

**Comment by paulgirard** [comment]
Ok on regarde ça cette semaine. Pas de rush. On peut se caser un moment vendredi au pire.
