### ISSUE TITLE
Ajout d'un libellé devant la date des News/Annonces

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#434]
Actuellement la date indiquée les news de type "annonce" est celle de la limite de soumission des candidatures. 
Si on est avant la date, ça fonctionne bien cognitivement; par contre, dès que la date est passée (et donc l'annonce obsolète) on a l'impression que c'est la date de publication de l'annonce.

Pour limiter les risques de confusion, il faudrait peut être prévoir d'ajouter la mention "date limite"/"deadline" devant cette date.

**Comment by Yomguithereal** [comment]
Il faut fermer cette issue du coup?

**Comment by AmelieVRL** [comment]
Je ne vois plus trop à quoi ça correspond mais je dirais que c'est bon avec les dates limites.
