### ISSUE TITLE
Bug - Onglet Setting du back office

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#436]
Nouveau jeu : essaie de supprimer la entrée du carrousel!!!
![Capture d’écran 2019-09-18 à 18 37 49](https://user-images.githubusercontent.com/37452370/65167838-9e006200-da43-11e9-8071-b71cc33dfb6a.png)

Ça a eu le mérite de me faire rire... mais je crois qu'il faudrait couper les titres des entrées dans le carrousel car en l’état la "croix" de suppression de l'item se trouve en dessous des titres des activités mises en avant.
Et ce n'est pas très très pratique.

**Comment by Yomguithereal** [comment]
J’ai vu ce problème en developpant la nouvelle page admin et ai remis les listes toutes les unes sur les autres. Ce sera en prod quand on validera le nouveau process avec paul
