### ISSUE TITLE
CMS: version réduite du modèle mais assurée

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#44]
Afin de commencer à développer les formulaires d'édition du CMS, on a besoin d'identifier tous les types de champs possibles ainsi que les champs dont on est presque sûr qu'ils resteront dans le modèle.

Je propose que Guillaume passe en revue le modèle avec Amélie afin de : 
- rendre le modèle plus techniquement compatible (voir la carte #22)
- ajouter des métadonnées de ratio aux médias
- identifier les champs sûrs

**Comment by Yomguithereal** [comment]
Résultat de notre réunion avec @AmelieVRL 

Activities:
- name
- excerpt
- type
- active
- description
- liste des gens
- change public to draft
- LIST: name + status + draft + type => actif / nom

People:
- firstname + lastname
- bio
- title
- membership
- active
- LIST: fullname status + active + draft => actif / nom
- ajouter draft

Publications:
- title
- abstract
- type
- content
- people
- activities
- publications
- change public to draft
- date => précision variable YMD
- LIST: draft + title + type

News:
- title
- excerpt
- start + end ou date unique
- label (=> suggestion)
- content
- people
- activités
- productions
- chang public to draft
- LIST: draft + title + label



BEWARE:
Automatisation de la date de mise en ligne + draft dans la mise en place du CRON
SPIRE
Cohérence des liens non-dirigés de publication vers publication

**Comment by Yomguithereal** [comment]
Concernant ceci j'ai refait une passe sur le model et ai stabilisé une version lite mais solide. J'ai aussi splitté le dossier de samples en deux: un dossier `markdown` pour vous et un dossier `json` pour m'aider à dev facilement (ya une commande `npm run hydrate:json` pour setup une base de dev). Je peux maintenant avancer sur les formulaire.

@paulgirard ci-dessus, sous la mention "BEWARE" quelques lièvres qu'on a levé avec @AmelieVRL.

**Comment by paulgirard** [comment]
Je ne comprends pas les beware.
je les copie dans une autre issue plus général sur le modèle et clos cette carte

**Comment by AmelieVRL** [comment]
Des éléments de réponses pour les beware:
- Spire : comment on gère les ajouts dans le CMS et les post-modifs dans l'appli SPIRE? ( ie, JE reprends le contenu d'un champs dans le CMS, puis ce même champs est modifié dans SPIRE)
- Liens vers drafts : faire attention à ne pas afficher les relations vers des entités en draft quand on génère le statique
