### ISSUE TITLE
[CSS] Missing line-height in sub-lists

### ISSUE THREAD

**Issue by boogheta** [medialab/website#440]
Whenever we have a `<ul>` within a `<li>`, we're missing a margin making it look weird compared to the distance between each `<li>`
example in the second part of the following article : https://medialab.sciencespo.fr/actu/recrute-ingenieure-de-recherche-data-scientist

**Comment by BenjmnG** [comment]
Well seen blind man!
C'est fixé

**Comment by boogheta** [comment]
Thx!
