### ISSUE TITLE
Images des cartes twitter tronquées

### ISSUE THREAD

**Issue by robindemourat** [medialab/website#442]
Actuellement le partage d'un lien sur twitter est rendu sous la forme "summary", ce qui donne une toute petite image souvent tronquée :

<img width="598" alt="Capture d’écran 2019-10-17 à 11 34 38" src="https://user-images.githubusercontent.com/1876890/66997102-1fdebc00-f0d2-11e9-8300-f622a10fac4f.png">

<img width="596" alt="Capture d’écran 2019-10-17 à 11 25 16" src="https://user-images.githubusercontent.com/1876890/66996321-d3df4780-f0d0-11e9-971b-e9543d9e277f.png">

Ça peut être changé simplement en transformant [cette méta](https://github.com/medialab/website/blob/7104e3994860e19cac6b8e3ce08ab5be6ef7815e/site/src/components/helpers/PageMeta.js#L98) depuis :

```
<meta name="twitter:card" value="summary" />
```

Vers ça :

```
<meta name="twitter:card" value="summary_large_image" />
```

Ce qui nous donnerait plutôt un rendu de ce genre :

<img width="515" alt="Capture d’écran 2019-10-17 à 11 33 33" src="https://user-images.githubusercontent.com/1876890/66997014-fa51b280-f0d1-11e9-86d5-fc3b486d19aa.png">

@AmelieVRL qu'en penses-tu ?

Peut-être lié à l'issue #417 @Yomguithereal (pas sûr) ?

**Comment by boogheta** [comment]
Je plussoie !

**Comment by AmelieVRL** [comment]
Ça me va aussi!

**Comment by Yomguithereal** [comment]
@robindemourat pas moyen de me souvenir si c'était lié. Je suppose que oui.
