### ISSUE TITLE
Rouge incorrect

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#443]
Bonjour @JulieBlanc @BenjmnG. Le rouge du site web n'est pas celui de la charte graphique `#e6142d`. Il y avait une raison à cela ou je peux le changer?

**Comment by JulieBlanc** [comment]
Je ne me souviens pas qu'il y ait une raison particulière de ce changement. Tu peux donc le changer.

**Comment by Yomguithereal** [comment]
@AmelieVRL je viens de créer une branche avec la correction du rouge. Regardons ça ensemble et prenons la décision. @JulieBlanc je me demande si vous n'aviez pas adouci le rouge pour que ce soit plus agréable à l'oeil.

**Comment by AmelieVRL** [comment]
En effet, je n'avais pas remarqué que vous n'aviez pas utilisé le bon rouge.
On peut regarder faire une branche pour regarder ce que ça donne avant de le changer partout?

**Comment by BenjmnG** [comment]
Si je te comprend bien, Guillaume a déjà pourvu à ton attente avec la
branche 'red-correction'

**Comment by AmelieVRL** [comment]
Oui... mais non parce que je ne sais pas où visualiser cette branche.
Une URL pour me faciliter la tâche?

**Comment by Yomguithereal** [comment]
Je peux pas vraiment te fournir d’url. Il faut que tu passes me voir.
