### ISSUE TITLE
Vue HTML du DOM par défaut ?

### ISSUE THREAD

**Issue by JulieBlanc** [medialab/website#446]
Une petite question, dont il me semble nous avons déjà discuté avec @Yomguithereal mais que j'aimerais réouvrir.

Actuellement, lorsqu'on charge le site, on se retrouve sans DOM et avec un script qui est appelé (c'est impossible d'inspecter le DOM du coup). Voir la capture d'écran ci-dessous.

Si on désactive javascript, l'HTML du DOM réapparait.

Est-il possible d'avoir la vue avec le DOM en HTML par défaut ?

<img width="1440" alt="Capture d’écran 2019-11-18 à 14 58 28" src="https://user-images.githubusercontent.com/25477334/69059292-83cc0b80-0a15-11ea-8451-6c0ee4b75c68.png">

**Comment by JulieBlanc** [comment]
C'est bon, @oncletom m'a bien expliqué :)

**Comment by oncletom** [comment]
Yes, de ce que j'ai compris, le `view-source` affiche possiblement 2 choses :

- le code source de la page transmise par le réseau 
- le code source de la page servie par le Service Worker si elle est en cache ; et le service worker injecte le HTML initial dans la page pour une navigation hors-ligne (et plus rapide en ligne, puisqu'on privilégie la version en cache à un appel réseau)

**Comment by Yomguithereal** [comment]
Gatsby est bientôt définitivement mort. Le `view-source` va redevenir bien plus simple dans pas longtemps :)
