### ISSUE TITLE
Twitter parsing bug

### ISSUE THREAD

**Issue by robindemourat** [medialab/website#448]
There seems to be an issue with some links in tweets:

<img width="446" alt="Capture d’écran 2019-11-22 à 09 22 33" src="https://user-images.githubusercontent.com/1876890/69409683-b4f45680-0d09-11ea-817c-174c0833cfba.png">

**Comment by Yomguithereal** [comment]
The tweet's url for further reference: https://twitter.com/medialab_scpo/status/1197516783575588864

**Comment by robindemourat** [comment]
Other one : 

https://twitter.com/medialab_scpo/status/1202269202188505090

-->

![Capture d’écran 2019-12-06 à 15 37 21](https://user-images.githubusercontent.com/1876890/70330735-6f25ab00-183e-11ea-8096-bca5a6456210.png)

**Comment by boogheta** [comment]
Non là ce n'est pas un bug de parsing de notre côté, c'est twitter qui a cru découvrir une url accentuée dans l'écriture inclusive de développeur.se (j'aurai du mettre un middle dot...)
Par contre ce que ça souligne c'est que le texte affiché pourrait être généré en utilisant les extended_entities des métadonnées renvoyées par l'API : elle donne pour chaque url en t.co une url "affichable" avec les coordonnées en caractères dans le message du bout à remplacer.

**Comment by boogheta** [comment]
entities en fait plutot que extended_entities
EN gros il faut utiliser le champ "display_url" pour l'affichage et "extended_url" pour le href, je pense que là on utilise extended_url pour les deux
```
 u'entities': {u'hashtags': [{u'indices': [66, 75], u'text': u'frontend'},
                             {u'indices': [76, 80], u'text': u'web'}],
               u'symbols': [],
               u'urls': [{u'display_url': u'd\xe9veloppeur.se',
                          u'expanded_url': u'http://xn--dveloppeur-b7a.se',
                          u'indices': [42, 65],
                          u'url': u'https://t.co/7p4w5hTtHL'},
                         {u'display_url': u'twitter.com/i/web/status/1\u2026',
                          u'expanded_url': u'https://twitter.com/i/web/status/1202269202188505090',
                          u'indices': [117, 140],
                          u'url': u'https://t.co/4mZpOO5hPZ'}],
               u'user_mentions': []},
```
