### ISSUE TITLE
Cleanup unused CSS variables

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#450]
La stylesheet utilise des variables css jamais utilisées.

**Comment by Yomguithereal** [comment]
@JulieBlanc @BenjmnG vous confirmez que les variables CSS (pas SASS) que vous avez placé sous `:root` ne sont pas utilisées dans la stylesheet?

**Comment by JulieBlanc** [comment]
Tu parles de ces variables ?

```
  --font-size: $font-size;
  --baseline: $baseline;

  --font-main: $font-main;
  --font-mono: $font-mono;
```

En effet elles ne semblent pas utilisées. Je ne me rappelle plus mais avec un rapide outil de recherche, elles ne semblent pas apparaître.

**Comment by BenjmnG** [comment]
Je confirme!

Le sam. 7 déc. 2019 à 09:59, Julie Blanc <notifications@github.com> a
écrit :
