### ISSUE TITLE
wilson favico

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/website#458]
The gatbsy version did not have favicon etc. So I guess right now it is served by the default SciencePo static server. @robindemourat should we add a favico?

**Comment by robindemourat** [comment]
If I'm not mistaken in the existing there is a [custom favicon](view-source:https://medialab.sciencespo.fr/icons/icon-48x48.png?v=ee2348ef454bbd8d5340bd54b853ef37) which is the logo in black.

It is available here : https://github.com/medialab/website/blob/master/site/src/assets/images/icons/icon-specimen.png

I guess this should be the one
