### ISSUE TITLE
fournir des exemples de génération d'image

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#46]
Afin de nourrir la réflexion sur la piste générative pour les illustrations des objets du site, on gagnerait à avoir uen liste des directions possibles sous la forme d'exemples déjà réalisés par d'autre

**Comment by BenjmnG** [comment]
Nous avons regroupé une multitude d'exemple d'image générative ici  : 

[website/docs/2018-10-31-image_generative/index.md](https://github.com/medialab/website/blob/master/docs/2018-10-31-image_generative/index.md)

Vous y trouverez deux parties.
1er : Principes abstraits synthétisant les possibles
2nd : Exemples concrets

Nous avons fait en sorte que les cas évoqués soit suffisamment large pour vous faire pétiller d'envie et que le champs des possible soit suffisamment large pour tenter de répondre aux contraintes pragmatiques ( quelle image pour illustrer ? ) institutionnelles ( est-ce Science Po-compatible ? ) artistiques ( quelle forme singulière et signifiante pour le labo ? )
