### ISSUE TITLE
Bad collection popover alignment on big screens

### ISSUE THREAD

**Issue by robindemourat** [medialab/website#465]
![Capture d’écran 2019-12-12 à 15 16 31](https://user-images.githubusercontent.com/1876890/70719506-6a577000-1cf2-11ea-959f-4997248a68ae.png)

On macos, firefox
Res : 1920x1080px

**Comment by BenjmnG** [comment]
Il y a une typo ici
https://github.com/medialab/website/blob/1ff16f29283793c0999397c9bccb7098a91ce57b/site/assets/scss/pages/pages_list/filtres/_filtre-style-desktop.scss#L83

Qui bizzarement donne :
`left: calc((100vw - 1600px) / 2+250px);`

Le manque d'espace autour du 250px fait que les calculs ne sont pas bon.

**Comment by Yomguithereal** [comment]
Tu ouvres un PR @BenjmnG ou tu push un fix :) ?

**Comment by BenjmnG** [comment]
Looking for a fix,
Mais pour l'instant j'en suis à reinstaller les dépendances...

![image](https://user-images.githubusercontent.com/10298798/70721930-b6a4af00-1cf6-11ea-8071-19d3e3bcbc60.png)

**Comment by BenjmnG** [comment]
Je n'ai pas réussi à faire tourner le machin en local.
J'ai toutefois substitué la variable Scss par un bon vieux _plain text_
Pas très subtile mais cela devrait rouler.

**Comment by robindemourat** [comment]
En fait le code en prod est déjà `calc((100vw - 1600px) / 2+500px)` mais cette expression est invalide (au moins sur firefox).

Suggestion : `calc(100vw - 1600px + 85px)` fonctionne chez moi (je n'ai pas cherché à comprendre les détails du calcul, juste à faire que ça marche donc je loupe peut-être un truc dans votre calcul), à confirmer

**Comment by Yomguithereal** [comment]
@robindemourat je te laisse pusher un fix si tu le souhaites

**Comment by robindemourat** [comment]
Autant pour moi j'ai lu trop vite le fix de benjamin fait déjà le trick !
