### ISSUE TITLE
Build does not list all productions in people page

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#469]
![image](https://user-images.githubusercontent.com/193478/72091389-58c4b080-3310-11ea-83c3-4fb072b0478a.png)

It should list much more productions.

**Comment by Yomguithereal** [comment]
Je crois que c'est dû au fait que je n'ai pas répliqué dans wilson l'utilisation des spire generated fields. Je vérifie.

**Comment by Yomguithereal** [comment]
Nope. Pas ça. Je continue à chercher.
