### ISSUE TITLE
Couleur du texte des tweet dans le flux de la home

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#484]
Hello,
j'ai remarqué un petit pb sur la couleur des liens dans le flux twitter de la home (certaines parties de textes s'affichent comme des liens "rouges" alors qu'il n'en est rien).
A priori, ça n'arrive qu'en début de tweet.

<img width="755" alt="Capture d’écran 2020-03-19 à 11 49 03" src="https://user-images.githubusercontent.com/37452370/77060304-a62c6080-69d8-11ea-83c3-6fcf01ac1dd5.png">

Ce n'est pas urgentissime mais il faudrait ne pas perdre le pb de vue.
Merci

**Comment by robindemourat** [comment]
# Investigation

Apparement il y a une embrouille avec `.tweet-content` qui intègre un lien qu'il ne devrait pas:

![Capture d’écran 2020-03-19 à 13 50 54](https://user-images.githubusercontent.com/1876890/77069845-73d72f00-69e9-11ea-81c8-125bbd3c8081.png)


Ça vient peut-être de [`resolveTweetsUrls`](https://github.com/medialab/website/blob/ab27266fad1ee5002007754acbe7b79b740eb3f3/api/flux.js#L161) au moment du parsing, ou du composant [`Tweet.js`](https://github.com/medialab/website/blob/ab27266fad1ee5002007754acbe7b79b740eb3f3/site/components/home/fragments/flux/Tweet.js) au niveau du rendu.

**Comment by Yomguithereal** [comment]
Je pense que ceci est lié à #464

**Comment by boogheta** [comment]
Oui ça a clairement l'air de venir du même mauvais parsing en regexp

**Comment by mdamien** [comment]
Hello, on dirait que c'est plutôt dut à une subtilité d'HTML qui ne permet pas de mettre des liens dans des liens et qui du coup casse le lien parent:

![image](https://user-images.githubusercontent.com/1469823/77784385-b8eb0900-705a-11ea-8a2e-15f80020873b.png)

Le code problématique en question:

https://github.com/medialab/website/blob/a8f41806a94dc69a6af4436ba0977e2bd00e443d/site/components/home/fragments/flux/Tweet.js#L52-L74
