### ISSUE TITLE
Page tools / collusion des textes

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#489]
On l'avait repéré quand on avait  fait la revue avec Mengying mais je crois que nous n'avions pas ouvert d'issue.
Quand les labels d'usage sont sur 2 lignes, on a des zones qui se superposent (voir la colonne de droite):
<img width="1157" alt="Capture d’écran 2020-03-25 à 15 44 07" src="https://user-images.githubusercontent.com/37452370/77550475-7508d000-6eb1-11ea-8a8c-940997b0eeca.png">

Il faut être dans une config. particulière, donc ce n'est pas très grave mais c'est moche!

**Comment by robindemourat** [comment]
Investigation : ça se produit entre 1300 et 1080 pixels de largeur.

**Comment by robindemourat** [comment]
Ce bug devrait avoir été fixé par https://github.com/medialab/website/commit/593bfabc8e0470ef168b88462c4bb309acc7c307, à vérifier à la prochaine mise en prod.

**Comment by AmelieVRL** [comment]
Cool! Merci beaucoup.

Amélie

Le lun. 30 mars 2020 à 14:52, Robin de Mourat <notifications@github.com> a
écrit :

**Comment by robindemourat** [comment]
C'est maintenant en prod et ça semble réglé pour moi, @AmelieVRL je t'invite à fermer quand tu auras jeté un oeil si c'est bon pour toi aussi !

**Comment by AmelieVRL** [comment]
🥇 @robindemourat !!  👍
