### ISSUE TITLE
The tools page is not accessible in english lang. (auto redirect to the old tools page)

### ISSUE THREAD

**Issue by robindemourat** [medialab/website#497]
How to reproduce this bug:

1. go to the "outils" page in french
1. click on the "en" button in the nav to switch to english

The browser is then redirected to https://tools.medialab.sciences-po.fr/ instead of https://medialab.sciencespo.fr/en/tools. @Yomguithereal wouldn't this be a redirection issue ?

**Comment by Yomguithereal** [comment]
It's not an issue, it's a feature :). We need to finally take the decision to switch to the new tool page with @boogheta and then we'll go and see @jri-sp about this and the old tool page will only remain a vague nightmare.

**Comment by robindemourat** [comment]
OK !

**Comment by boogheta** [comment]
I guess it could be done very soon now, what do you think @AmelieVRL

**Comment by AmelieVRL** [comment]
Hmmm. Good point.
I think Mengying has already done the job. So yes, we should implement the
English template!
