### ISSUE TITLE
Menu parent des tools "recommandés" dans le menu de navigation

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#498]
Depuis la page outils, quand on clique sur un outils "recommandé" par le médialab, on bascule sur la page de l'outil qui est un objet de type "productions" donc logiquement, le menu de navigation met en gras "productions"
<img width="921" alt="Capture d’écran 2020-04-06 à 11 39 59" src="https://user-images.githubusercontent.com/37452370/78545135-8fb93e00-77fb-11ea-8604-a673f1c7a26c.png">

L'outil peut être perçu (à tort) comme une production du médialab quand on vient de la page tools et a fortiori pour toute personne qui arriverait directement sur cette page.
De plus, ça pourrait  être trés mal pris par les producteurs des outils.

Comment pourrait-on faire pour limiter cette confusion?

**Comment by boogheta** [comment]
On en a discuté la semaine dernière, on se proposait deux choses, à tester, valider, améliorer par @rawbin : 
- [ ] ne rien mettre en gras dans le menu dans ces cas là (si c pas trop compliqué à conditionner comme exception @Yomguithereal ?)
- [ ] dans la liste des tools mettre une séparation franche entre nos outils et ceux des autres comme dans la liste des membres entre les actuels et les anciens

**Comment by Yomguithereal** [comment]
Il me semblait qu'on gardait 2 pages pour chaque outil, non? Une page version prod et une page version outil. Auquel cas la solution est évidente?

**Comment by AmelieVRL** [comment]
A mon avis, ces. deux options ne règlent pas le pb.
On pourrait en discuter/brainstormer en réu tech peut être?

**Comment by boogheta** [comment]
@Yomguithereal au vu des urls, j'ai l'impresson que la page d'un outil est  bien la page version production donc a priori non

**Comment by Yomguithereal** [comment]
En tout cas il est clair que pour les outils pas a nous on devrait highlighter outil et pas prod

**Comment by robindemourat** [comment]
Je me suis permis de rajouter une carte dans le trello medialife à ce propos.

En préambule, résumé de nos réflexions avec amélie ce matin :
* option 1 : toutes les prods de type "logiciel" ou "code" ont une page objet à `outils/:slug` et une deuxième page à `productions/:slug` (cf ce qu'avait compris guillaume) -> relativement acceptable mais ça veut dire 2 permaliens pour la même page
* option 2 : toutes les prods de type "logiciel" ou "code" ont leur page objet à `outils/:slug` (ce qui veut dire changer le lien des listings de la page objet mais aussi du listing des productions pour les prods afférentes)
* option 3 : toutes les prods de type "logiciel" ou "code" extérieures au médialab ont leur page objet à `outils/:slug` mais les outils maisons restent à `productions/:slug`

L'option de forcer l'élément highlighté dans le nav (si elle est possible techniquement) serait possible mais quand même dommage en terme d'UX pour le repérage (à la fois dans le nav et dans l'URL).

Partant pour en discuter de vive voix pour continuer la réflexion !

**Comment by boogheta** [comment]
Je crois que l'option 2 est à la fois la plus simple et celle qui me semble la plus cohérente d'un point de vue utilisateur
Discutons en demain matin en réu tech

**Comment by robindemourat** [comment]
Option 2 en prod 🎉 je me permets de fermer

**Comment by boogheta** [comment]
Yeah! J'en réouvre une autre sur la séparation dans la liste pour le garder en tête
