### ISSUE TITLE
RSS not wotking

### ISSUE THREAD

**Issue by EdaNano** [medialab/website#502]
Hi, the RSS feed in https://medialab.sciencespo.fr is not valid

**Comment by Yomguithereal** [comment]
Hello @EdaNano. Which specific feed are you talking about? Can you give me its url and can you tell me what's not valid so we can fix the issue?

**Comment by ip512** [comment]
Hi, I have the same issue, I'm not able to add rss feed on thunderbird.
You can see all validation errors here : https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmedialab.sciencespo.fr%2Ffeed

**Comment by Yomguithereal** [comment]
Thanks @ip512. I'll check this out soon.

**Comment by Yomguithereal** [comment]
@ip512 an upgrade of the website should happen in the afternoon with some tiny fixes. Would you be so kind to tell me whether it fixes the issues you are having?

**Comment by ip512** [comment]
@Yomguithereal yes it fixes the issue on thunderbird. 
Thank you for the update

**Comment by Yomguithereal** [comment]
Ok. I will close the issue then :). Some warnings remain but I don't have enough time to address them properly yet.
