### ISSUE TITLE
new member type

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#503]
Nous n'avons pas prévu le cas des "chercheurs invités". Pour l'instant c'est Isari qui fait foi, mais  Isari n'est pas accessible depuis l'extérieur donc on n'a nul part la liste de nos invités.

Pourrait-on ajouter une nouveau type de membre qui serait  invited/invité tout comme on a déjà member/membre et associated/associé.
Tout comme membre et associé, l'affichage est aléatoire ; et évidemment, c'est exclusif (donc a priori rien a changé sur les anciennes données).
Si besoin, je me joins a vous pour en parler demain en réu tech.

**Comment by Yomguithereal** [comment]
- [ ]: modifier les specs
- [ ]: vérifier la validité du CMS
- [ ]: modifier sur la SCSS

**Comment by Yomguithereal** [comment]
@AmelieVRL prod dans ~30mins
