### ISSUE TITLE
pages EN - gestion des typo

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#512]
Il semblerait que les mises en formes de texte (gras, italique) ne soit pas bien interpretées (voir capture ci desous) dans les pages en anglais :
- le texte en question disparait
- et des sauts de ligne apparaissent à la place
<img width="1144" alt="Capture d’écran 2020-07-20 à 10 35 30" src="https://user-images.githubusercontent.com/37452370/87917694-a8312980-ca75-11ea-81bf-8875687e99c8.png">
<img width="1099" alt="Capture d’écran 2020-07-20 à 10 35 55" src="https://user-images.githubusercontent.com/37452370/87917701-a9625680-ca75-11ea-9863-651b65301fce.png">

**Comment by Yomguithereal** [comment]
Cela semble être un problème de conversion depuis l'ancien CMS. Je vais corriger cette page dans le CMS et fermer cette issue parce que cela est assez complexe à corriger dans le templating autrement. Si jamais qqun recroise un cas identique, rouvrons l'issue et trouvons une solution plus robuste.
