### ISSUE TITLE
Étendre le template de détail d'activité "séminaire" à toutes les pages de séminaire

### ISSUE THREAD

**Issue by robindemourat** [medialab/website#518]
Probablement en se basant sur le titre pour ne pas alourdir le modèle ? ou en rajoutant une propriété au modèle des activités ?

cc discussion avec @AmelieVRL

cc [ici dans le code](https://github.com/medialab/website/blob/master/site/components/details/ActivityDetail.js#L45)

**Comment by robindemourat** [comment]
Discussion en réu tech : ajouter un type `séminaire` aux activités permettrait un code plus propre et le rajout d'un filtre "séminaires" sur la page listing activités.

**Comment by Yomguithereal** [comment]
Je vais commencer par ajouter le type séminaire aux activités et changer la verrue du template.

**Comment by Yomguithereal** [comment]
C'est bon pour le type d'activité séminaire. C'était une purge pour le CSS lol :(
