### ISSUE TITLE
passage en prod du CMS pour mettre en place le process de test/review + production des contenus

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#52]
Il faut qu'on discute avec @BenjmnG et @JulieBlanc de comment on va leur fournir les contenus de tests.
L'idéal serait que le CMS soit la référence le plus tôt possible.
Ce qui est jouable si ce dernier est déployé en local.
Ou alors que le github des contenus soient la référence des contenus ?

Très lié à #63

**Comment by oncletom** [comment]
On est bon sur ça ? 

Merci, c'était top d'avoir tous les contenus à montrer :-)

**Comment by paulgirard** [comment]
yep je ferme
