### ISSUE TITLE
internationalisation des titres des pages activités

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#520]
En saisissant les courants de recherche comme activités, je constate que le choix de ne pas internationaliser les titres des activités (à l'époque, on voulait que l'on appelle un projet par son nom déposée qqsoit la langue, ex: GOPI, FORCCAST, Algoglitch, EMEA, AIME, etc. etc.) ne tient plus dès qu'il y a du rédactionnel en jeu (cf. l'appellation des courant de recherche).

Serait-ce possible de repasser ce titre en 2 langues (et de discuter ensemble des conséquences)?

**Comment by boogheta** [comment]
A confirmer avec @Yomguithereal mais a priori je ne vois pas trop de complications ni d'objection à juste ajouter un champ en plus english_title aux activités, qui est utilisé uniquement s'il existe en se rabattant sur le titre français classique autrement. Ca ne devrait pas nécessiter de migration a priori. Juste trouver du temps de Guillaume pour ajouter la boite dans le backoffice et gérer à la génération du front l'utilisation de ce champ.

**Comment by Yomguithereal** [comment]
Côté modèle c'est pas très problématique mais je vais plutôt changer le champs en champs internationalisé (donc `{en, fr}`). Et il devra y avoir une petite migration mais rien de bien méchant. Ce qui me fait peur c'est plus les implications sur le site statique, à savoir 1. bien identitifer tous les endroits où il faut gérer l'internationalisation et 2. bien remplir les deux champs par défaut (genre fr: GOPI ET en: GOPI) et pas seulement le fr pour éviter d'avoir des titres grisés qui indiquent qu'on a pas la traduction. @robindemourat tu as quelque chose à ajoute?

**Comment by robindemourat** [comment]
Ok pour moi. A première vue il me semble qu'il faudrait màj le listing, page activité, et carousel de home non ? Pour le 2 je me demande juste si on pourrait pas faire une règle spéciale au niveau du template pour pas griser le fallback ? c'est quand même bizarre d'avoir à dupliquer la même chose en EN et FR pour des acronymes non ?

**Comment by Yomguithereal** [comment]
Oui, mais je veux pas avoir à me lancer dans une heuristique de détection des acronymes cela dit. C'est pas aussi trivial que ça en a l'air :)

**Comment by boogheta** [comment]
Je suis d'accord avec Robin, la question n'est pas de détecter automatiquement avec une heuristique ce qui est acronyme ou non, juste pour les activités s'il n'y a pas de titre EN on met le FR sans grisage, rien de plus

**Comment by Yomguithereal** [comment]
Moi ça m'arrange ça fait moins de code :)

**Comment by boogheta** [comment]
C'est toi le lead dev sur cette codebase donc c'est a toi de trancher, mais je pense que c'est l'approche la moins chronophage oui.
@AmelieVRL tu en penses quoi ?
