### ISSUE TITLE
Espace en trop dans le layout de la page séminaire

### ISSUE THREAD

**Issue by AmelieVRL** [medialab/website#522]
Je viens de constater que s'il n'y a pas de séances à venir dans les pages séminaires, le layout affiche un grand blanc (avec une chaussure marron... pardon c'est nase) avant les séances à venir.
Par exemple, dans la capture ci-dessous, il y a des séances passées listées plus bas:
![Capture d’écran 2020-11-06 à 18 05 53](https://user-images.githubusercontent.com/37452370/98394437-0b61be80-205b-11eb-9bba-92f79fb5c05e.png)

Rien d'urgent mais à ne pas perdre de vue.

**Comment by robindemourat** [comment]
Possible fix:

```
.liste_seminaire {

    min-height: 0;
    margin-bottom: 0;

}
```

Ou enlever `.list_seminaire` [ici](https://github.com/medialab/website/blob/master/site/assets/scss/pages/pages_list/item-list/_list-all.scss#L11).

Prochaine étape: le tester extensivement pour vérifier que ça casse rien pour les pages avec quelques chose (normalement demain).
