### ISSUE TITLE
Problème d'accessibilité avec le focus

### ISSUE THREAD

**Issue by yaaax** [medialab/website#547]
Bonjour,

Il ne faudrait pas supprimer le style du focus natif du navigateur :
https://github.com/medialab/website/blob/56a3f3001139ecfef47dfab4ea355470b914254c/prototyping/assets/scss/common/_clean.scss#L55

Cf. [critère RGAA 10.7. Dans chaque page web, pour chaque élément recevant le focus, la prise de focus est-elle visible ?](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#crit-10-7)

Bien sûr il reste possible de changer ce style pour rester cohérent avec le reste de l'UI.
Quelques informations intéressantes ici : [A Complete Guide To Accessible Front-End Components / Accessible :focus Styles](https://www.smashingmagazine.com/2021/03/complete-guide-accessible-front-end-components/#accessible-focus-styles)

P.S. : super site félicitations !

**Comment by Yomguithereal** [comment]
Bonjour @yaaax, pour être tout à fait franc je ne suis même pas certain de savoir pourquoi cette règle CSS existe dans notre stylesheet et cela semble très bien se passer si on l'enlève et on peut alors tabuler sans soucis avec un outline pertinent des éléments. @robindemourat un avis sur la question avant que je supprime cette règle?

**Comment by yaaax** [comment]
Quel réactivité :) Super merci
