### ISSUE TITLE
CMS: page home

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#56]
Pour contrôler la page home on a besoin de pouvoir éditer dans le CMS : 

- [x] une liste ordonnée d'objets tout modèle confondu **sauf People**  (pour le carousel)
- [x] une liste ordinnée d'objets tout modèle confondu (pour la grille)

**Comment by Yomguithereal** [comment]
Le MVP pour ça devrait être bon. Je passe en prod.

**Comment by Yomguithereal** [comment]
Je réouvre pour "recette".
