### ISSUE TITLE
point design / dev sur l'intégration dans le CMS

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#63]
Afin de gagner du temps et d'éviter du codage inutile, je propose que @Yomguithereal et @BenjmnG discutent au tel de comment permettre de réaliser l'intégration directement dans le cadre du CMS.
Le CMS n'est pas loin d'être prêt à accueillir ce travail, reste à définir le bon moment.
Un premier call pourrait être utile rapidement ? 

Ce call aurait pour but de définir al bonen méthode et donc de permettre @Yomguithereal d'écrire la doc qui va bien.

**Comment by BenjmnG** [comment]
Indispensable mais prématuré pour la partie design.
J’envisageai ce moment dans les premiers temps de la prochaine itération.

Bien sur, si cela arrange tes affaires @Yomguithereal ( besoin de planifier, bonne disponibilité actuelle), on prend un moment lundi ou mardi.

**Comment by paulgirard** [comment]
Une première session a été faite ce jour.
On a mis à jour le readme principal.
Il faudra refaire une session "pratique" et un accompagnement en Janvier.
