### ISSUE TITLE
Peuplement des métas pour les réseaux sociaux / biblio

### ISSUE THREAD

**Issue by robindemourat** [medialab/website#65]
Ceci est une issue pense-bête.

A-t-on pensé à la politique de peuplement des métas (avant tout pour les réseaux sociaux) ?

Je pense principalement aux metas open graph pour facebook, et aux metas twitter.

Plusieurs questions :

* les metas seront-elles en français, en anglais ou les deux ?
* les metas devraient-elles être les mêmes pour toutes les pages (e.g. titre = "médialab" description = baseline du site), ou différenciées selon qu'on est sur une page activité, people, publication, ... ?
* si elles sont différenciées, cela devrait-il se faire automatiquement (e.g. pour une page "people" prendre le nom de la personne et sa description, pour une page "publication" le titre et l'abstract, etc.) ou éditorialement via le backoffice ?
* si elles sont différenciées, comment gérer l'image de publication (e.g. pour les cartes twitter) ? automatiquement (en prenant la première image utilisée par la page ou via une screenshot faite avec manet par ex.), ou éditorialement depuis le backoffice (en choisissant par exemple une image déjà associée à la page, ce qui inclurait probablement une passe de redimensionnement pour correspondre aux contraintes des différentes plateformes)

P.S. : la question se pose peut-être également pour les questions d'indexation/référencement du site, engageant aussi à un "design" des balises meta.

**Comment by paulgirard** [comment]
J'ajoute que des métas peuvent intéressantes aussi pour le référencement bibliographique notamment pour les pages "publication"

**Comment by robindemourat** [comment]
Note pour exposer les pages à des usages de référencement bibliographique (avec zotero/mendeley notamment) : possibilité d'implémenter les métas appropriées selon les specs [dublincore](http://dublincore.org/documents/dcq-html/) (pour un référencement de chaque page, au niveau de la \<meta>) et/ou d'utiliser la spec [Context Object in Span](https://en.wikipedia.org/wiki/COinS) (pour un référencement de n objets dans la \<body>) - un exemple d'implémentation de COinS en react [ici](https://github.com/peritext/peritext-rendering-utils/blob/master/src/StructuredCOinS.js)

**Comment by Yomguithereal** [comment]
Ca tombe bien, @boogheta est un expert des méta-données nécessaires à l'affichage correct des articles dans les cards twitter.

**Comment by boogheta** [comment]
pas compris la question

**Comment by robindemourat** [comment]
Fermée par https://github.com/medialab/website/commit/0c6c53a59225664b83822e5e91bb7a9344f61cdf
