### ISSUE TITLE
Accès VPN prestataire

### ISSUE THREAD

**Issue by oncletom** [medialab/website#68]
Accès pour :

- Amélie
- Thomas
- Benjamin

**Comment by paulgirard** [comment]
j'ai demandé la réactivation du compte

**Comment by oncletom** [comment]
C'est bon de mon côté 👍 merci !

**Comment by BenjmnG** [comment]
Nope !
Quelles sont les identifiants et l'adresse du VPN, please ?
Je pensais les avoir mais non.

Le jeu. 6 déc. 2018 à 17:26, Thomas Parisot <notifications@github.com> a
écrit :

**Comment by AmelieVRL** [comment]
Ok pour moi!

Amélie
