### ISSUE TITLE
récupérer les vieux contenus

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#7]
## création des redirections
Les objets qui contiennent des informations qui étaient déjà présentes dans le site actuel du médialab auront un champs supplémentaire indiquant leur slug dans l’ancien CMs (wordpress). Il faudra ajouter au CMS un template de configuration nginx générant les règles de redirection à partir des champs legacy_slug présents dans le modèle. 

- [x] listing complets des contenus
- [x] Scraping du backoffice
- [ ] format HTML riches
- [x] récupération des images
- [x] récupération des liens
- [x] status previously
- [x] récupération des dates (début/fin) ?

**Comment by boogheta** [comment]
Wordpress REST API : https://v2.wp-api.org

**Comment by farjasju** [comment]
Le script de scraping du backoffice est dispo dans la branche dédiée.

**Comment by paulgirard** [comment]
- [ ]  faire tourner le scrap de Jules
- [ ] vérifier les données
- [ ] écrire la spec d'insertion des anciennes données par le format du dump

**Comment by Yomguithereal** [comment]
Draft de la spec du HTML [ici](https://github.com/medialab/website/blob/master/specs/HTML.md).

**Comment by paulgirard** [comment]
JE clos celle issue et crée une nouvelle sur les points restants : HTML et load.
