### ISSUE TITLE
Session : point UX sur le CMS

### ISSUE THREAD

**Issue by oncletom** [medialab/website#75]
Question de mettre plusierus par ligne + page de liste.

**Comment by robindemourat** [comment]
Ressources sur détails UX concernant le backoffice à garder sous la main pour support aux décisions :

Formulaires :

https://uxdesign.cc/design-better-forms-96fadca0f49c
https://uxdesign.cc/the-ux-behind-designing-better-forms-d6ebe7a817d2
https://uxplanet.org/the-18-must-do-principles-in-the-form-design-fe89d0127c92
https://www.ventureharbour.com/form-design-best-practices/

Listes :

https://uxdesign.cc/making-lists-easy-e7c5d971d1f7

Cartes (dans listes) :

https://uxdesign.cc/design-better-cards-c0d12ab581c4

**Comment by robindemourat** [comment]
[Autre ressource (notes et recos préliminaires)](https://github.com/medialab/website/blob/master/docs/2018-11-28-notes%20interface%20du%20backoffice/index.md#premi%C3%A8re-r%C3%A9flexion-sur-les-vues-listes)

**Comment by robindemourat** [comment]
Première session de réflexion :

# Actualités

Critères de tri :

* date
* tri par type (alphabétique)

Critères de filtrage :

* chronique ou rendez-vous ou les deux

Indicateurs éditoriaux (pour les cartes et comme critères de filtrage) :

* complétion des traductions (ok, déséquilibré (choisi par rapport à l'autre langue - pourcentage de déséquilibre en nombre de caractères), ou inexistant)


# Personnes

Tri:

* nom (A-Z)

Filtres :

* parti ou pas parti
* projet lié

Indicateurs éditoriaux (pour les cartes et comme critères de filtrage) :

* complétion des traductions (ok, déséquilibré (choisi par rapport à l'autre langue - pourcentage de déséquilibre en nombre de caractères), ou inexistant)
* date d'ajout de la dernière publi

# Publications

# Activités


Indicateurs éditoriaux (pour les cartes et comme critères de filtrage) :

* complétion des traductions (ok, déséquilibré (choisi par rapport à l'autre langue - pourcentage de déséquilibre en nombre de caractères), ou inexistant)
