### ISSUE TITLE
Comment on nomme les pages (slugify) pour le SEO ?

### ISSUE THREAD

**Issue by oncletom** [medialab/website#76]
- [ ] slug définitif vérifiable à la création puis non éditable
- [ ] slug composé de : human readable slug + ID 
- [ ] slug human readable : tokens sans accent séparés par des _ longueu max 5? tokens
- [ ] génération et stokcage de plusieurs slugs à la création pour permettre un changement si besoin

**Comment by Yomguithereal** [comment]
Ceci est notamment lié à la question des redirections des pages de l'ancien site web.

**Comment by AmelieVRL** [comment]
URL composée de ID + Slug de 50 caractères max
Slug à valider lors du premier enregistrement puis non editable dans l'interface

Prévoir une liste de slugs pour chaque objet au cas où il faille modifier le slug

**Comment by oncletom** [comment]
Questions qui restent : 

- est-ce qu'on garde un ID ou non
- est-ce qu'on garde `fr/` et `en/` dans l'URL ?
