### ISSUE TITLE
Définir ce qu'on veut sur la home

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#84]
- [x] quelle est la structure de la home en terme de blocs ?
- [x] Que met on dans ces blocs ?
- [x] Quel type de contenu ? 
- [x] Quelles info par type contenu ?

**Comment by AmelieVRL** [comment]
@paulgirard et @robindemourat je viens de finir le peuplement de la home.
Je vous laisse y jeter un oeil et modifier au besoin avant d'envoyer à Julie et Benjamin en début de semaine.

C'est par là que ca se passe : 👉 
https://github.com/medialab/website/blob/master/docs/2018-12-18-atelier2/peuplement-home.md
