### ISSUE TITLE
CMS : image de couverture

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#9]
@AmelieVRL a besoin de pouvoir ajouter des contenus image, vidéo, audio, document, site. 
- [x] création de média contextuel
- [x] upload et remplacement par un nouvel upload
- [ ] édition des métadonnée (voir modèle)
- [ ] ajout de vidéos hébergées sur vimeo (upload fait en dehors du CMS, gestion du embed)
- [x] gestion d’éventuels format de gabarit des images en fonction du design
- [x] les contraintes de ratio des images sont définies au niveau des champs contenant des médias (le champs illustrations et documentations n'auraont pas les memes cotnraintes et ;les illustrations dans les peoples et dans les activités ne seront pas les mêmes)

**Comment by boogheta** [comment]
« medias are nice, but we need something better ! »
