### ISSUE TITLE
un script de déploiement configurer avec @jri-sp qui copie le résultat du builde sur le serveur de prod

### ISSUE THREAD

**Issue by paulgirard** [medialab/website#93]
@Yomguithereal @jri-sp je propose qu'on mette en place le script de déploiement du statique en prod. Dans un premier temps on peut juste créer un dossier statique accessible sur l'image de prod mais tant qu'à faire autant simuler de suite le rsync qui envoie sur le serveur final ? 

Ce sera utile pour faire des tests de performance (voir #266)

**Comment by jri-sp** [comment]
J'ai un vague souvenir que vous vouliez pusher les fichiers statiques buildés depuis le back-office sur un repo prévu à cet effet, j'ai rêvé ? Est-ce toujours d'actualité ?
Si c'est toujours le cas ça pourrait être assez simple d'intégrer le déploiement automatique...

**Comment by Yomguithereal** [comment]
C'est pas tant de pousser les fichiers statiques buildés sur un repo que sur le serveur, probablement à Reims, qui va héberge le site en production.

**Comment by paulgirard** [comment]
@jri-sp en faite il faudrait décider de où on héberge le nouveau site statique.
Si c'est sur le même serveru que le site actuel on a déjà un accès rsync.
Si tu préfères qu'on le mette ailleurs car plus besoin de PHP and co alors je propose qu'on teste rapidement des transferts pour préparer la mise en prod.

**Comment by jri-sp** [comment]
Ah ok! Pour le moment vous pouvez le mettre sur le serveur du site actuel. On le changera de serveur si nécessaire.
