### ISSUE TITLE
Discussion sur la stratégie d'import des anciens contenus

### ISSUE THREAD

**Issue by oncletom** [medialab/website#94]
On a besoin de produire des guidelines pour que l'import de Jules s'imbrique bien dans le nouveau modèle.

**Comment by paulgirard** [comment]
J'ai commencé à écrire le script d'import : 
https://github.com/medialab/website/blob/master/scripts/rewrite_old_data.js

**Comment by paulgirard** [comment]
On va importer toutes les données de l'anciens sites le plus tôt possible pour rendre disponibles des données réelles pour le templating. On décidera de la bascule en prod quand on aura tester quand ce sera nécessaire de commencer à écrire des nouveaux contenus/retravailler les anciens. Ce choix demandera d'ensuite filtrer ce qu'on réimporte ensuite par date de création.
Pour le moment il manque spire et le traitement des HTML.
J'ai créer des issues pour ces points
