### ISSUE TITLE
Impossible de voir une news dans l'admin

### ISSUE THREAD

**Issue by oncletom** [medialab/website#98]
Ça me fait ça sous Firefox

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/138627/49957426-fe3c0380-ff07-11e8-8898-cd68f7bc39f6.png">

**Comment by Yomguithereal** [comment]
La pprd n’est pas à jour. Il faut que je réaligne les données.

**Comment by oncletom** [comment]
Du coup c'est réglé depuis la semaine dernière 👍  Merci !
